const {chromium}=require(require('node:path').resolve(__dirname,'../../gothtechnology2/node_modules/playwright'));
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path');
const base=process.env.RAHBE_QA_URL||'http://127.0.0.1:4198',out=path.resolve(__dirname,'../output/playwright');
(async()=>{
 await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,...(process.env.CI?{}:{channel:'chrome'})});const report={checks:[],errors:[],missing:[],fixtures:'Isolated input and save fixtures; complete-route proof remains in browser.cjs.'};
 const check=(name,ok)=>{report.checks.push({name,passed:!!ok});assert.ok(ok,name);};
 try{
  const ctx=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'reduce'});
  await ctx.addInitScript(()=>{window.audioQA={contexts:0,notes:0};const Original=window.AudioContext;window.AudioContext=class extends Original{constructor(...args){super(...args);audioQA.contexts++;}createOscillator(){const osc=super.createOscillator(),start=osc.start.bind(osc);osc.start=(...args)=>{audioQA.notes++;return start(...args);};return osc;}};});
  const p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.status()>=400)report.missing.push(r.url());});
  const ready=()=>p.waitForFunction(()=>document.body.dataset.ready==='true');
  await p.goto(base+'/?debug');await ready();await p.screenshot({path:out+'/polish-title-desktop.png'});await p.locator('#start').click();await p.waitForTimeout(200);
  check('music requires opt-in',await p.evaluate(()=>audioQA.contexts===0&&audioQA.notes===0));
  await p.locator('#sound').click();await p.waitForTimeout(300);check('opt-in score plays synthesized notes',await p.evaluate(()=>audioQA.contexts===1&&audioQA.notes>3));await p.locator('#sound').click();await p.waitForTimeout(200);const notes=await p.evaluate(()=>audioQA.notes);await p.waitForTimeout(300);check('sound off stops scheduling',await p.evaluate(n=>audioQA.notes===n,notes));
  await p.locator('#game canvas').focus();await p.evaluate(()=>{Object.assign(__underground.state.player,{x:570,y:440,vx:0,vy:0,grounded:true});});await p.keyboard.down('Space');await p.waitForTimeout(400);await p.keyboard.up('Space');const climbed=await p.evaluate(()=>__underground.state.player.y);check('Space climbs a real ladder',climbed<400);
  await p.keyboard.down('s');await p.keyboard.down('Space');await p.waitForTimeout(400);await p.keyboard.up('Space');await p.keyboard.up('s');check('Space + S descends a real ladder',await p.evaluate(y=>__underground.state.player.y>y+30,climbed));
  await p.evaluate(async()=>{const {ropeEnd}=await import('./src/simulation.js');const s=__underground.state,r=s.world.ropes[0],end=ropeEnd(r,s.time);Object.assign(s.player,{x:end.x,y:end.y+45,vx:0,vy:0,grounded:false,rope:-1});});await p.keyboard.press('Space');await p.waitForTimeout(150);check('Space grabs a swinging rope',await p.evaluate(()=>__underground.state.player.rope>=0));await p.keyboard.press('w');await p.waitForTimeout(60);check('W releases rope with jump momentum',await p.evaluate(()=>__underground.state.player.rope===-1&&__underground.state.player.vy<0));
  await p.emulateMedia({reducedMotion:'no-preference'});await p.evaluate(()=>{__underground.start();__underground.state.hitStop=.2;});await p.keyboard.press('w');await p.waitForFunction(()=>__underground.state.player.vy<0,null,{timeout:2000});check('brief jump presses survive combat hit-stop',true);await p.emulateMedia({reducedMotion:'reduce'});
  await p.evaluate(()=>{__underground.start();__underground.state.coins=600;});await p.locator('#upgrades').click();await p.locator('[data-upgrade="shield"]').click();check('shop purchases shield and disables repeat purchase',await p.locator('[data-upgrade="shield"]').isDisabled()&&await p.evaluate(()=>__underground.state.coins===400&&__underground.state.upgrades.shield));await p.screenshot({path:out+'/polish-workbench.png'});await p.locator('#shop-resume').click();
  await p.evaluate(()=>{__underground.state.kills=4;__underground.state.time=97.5;__underground.state.deaths=2;RahbeArcadeGame.save();});await p.reload();await ready();await p.locator('#continue').click();check('continue retains shield and does not double-count arcade stats',await p.evaluate(()=>__underground.state.upgrades.shield&&__underground.state.coins===400&&__underground.state.deaths===2&&RahbeArcadeGame.getStats().kills===4&&RahbeArcadeGame.getStats().seconds<100));
  await p.locator('#pause').click();await p.locator('#return-title').click();await p.locator('#daily').click();check('daily button starts todays shared seed',await p.evaluate(async()=>{const {seedForDay}=await import('./src/progression.js');return __underground.state.runMode==='daily'&&__underground.state.seed===seedForDay();}));
  await p.evaluate(async()=>{const {recordRun}=await import('./src/progression.js');const s=__underground.state;s.time=240;s.secrets=2;localStorage.setItem('rahbe-underground-profile-v2',JSON.stringify(recordRun(s)));});await p.reload();await ready();await p.locator('#records').click();check('earned medals and costumes appear',await p.locator('[data-costume="riverwalk"]').count()===1&&await p.locator('[data-costume="vault-gold"]').count()===1&&await p.locator('#panel-content').innerText().then(t=>t.includes('240 seconds')&&t.includes('Detroit explorer')));await p.screenshot({path:out+'/polish-records.png'});await p.locator('[data-costume="riverwalk"]').click();await p.reload();await ready();check('selected costume persists',await p.evaluate(()=>JSON.parse(localStorage.getItem('rahbe-underground-profile-v2')).costume==='riverwalk'));await p.locator('#start').click();await p.waitForTimeout(500);await p.screenshot({path:out+'/polish-riverwalk-desktop.png'});await p.evaluate(()=>__underground.place(1,2500));await p.locator('#shop-resume').click();await p.waitForTimeout(500);await p.screenshot({path:out+'/polish-cut-desktop.png'});await ctx.close();
  for(const viewport of [{width:390,height:844},{width:844,height:390}]){
   const mobile=await browser.newContext({viewport,isMobile:true,hasTouch:true,reducedMotion:'reduce'}),page=await mobile.newPage(),sources=[];page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{const u=new URL(r.url());if(u.pathname.includes('/src/')&&u.pathname.endsWith('.js'))sources.push(u);});await page.goto(base+'/?debug&touch');await page.waitForFunction(()=>document.body.dataset.ready==='true');check('entire module graph uses current release URLs '+viewport.width,sources.length>8&&sources.every(u=>u.searchParams.get('v')==='2.0.1'));
   const bounds=await page.locator('#start,#daily,#records,#howto').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};}));check('title actions fit '+viewport.width,bounds.every(r=>r.x>=0&&r.y>=0&&r.x+r.w<=viewport.width&&r.y+r.h<=viewport.height));await page.screenshot({path:out+'/polish-title-'+viewport.width+'.png'});
   await page.locator('#start').click();await page.locator('#pause').click();check('HUD pause is unobstructed '+viewport.width,await page.evaluate(()=>__underground.state.mode==='paused'));await page.locator('#resume').click();await page.waitForTimeout(500);await page.screenshot({path:out+'/polish-riverwalk-'+viewport.width+'.png'});await page.evaluate(()=>__underground.place(1,2500));await page.locator('#shop-resume').click();check('access beacon offers an upgrade choice '+viewport.width,true);await page.waitForTimeout(500);await page.screenshot({path:out+'/polish-cut-'+viewport.width+'.png'});
   await page.locator('#upgrades').click();await page.locator('#shop-resume').click();check('workbench accessible and dismissible '+viewport.width,await page.evaluate(()=>__underground.state.mode==='playing'));await mobile.close();
  }
  check('no runtime errors',report.errors.length===0);check('no missing artwork',report.missing.length===0);report.passed=true;
 }catch(e){report.passed=false;report.failure=e.stack;process.exitCode=1;}finally{await fs.writeFile(out+'/polish-features.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();}
})();
