const canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),W=1280,H=720,FLOOR=598,GRAVITY=2200;
const AS={bg:'../gothtechnology-canvas/assets/user-stage/forest-fight-background.jpg',ezra:'../gothtechnology/assets/GOTHTECHNOLOGY_EXPANDED_SPRITE_PACK_V2/characters/MASTER_EZRA/runtime_atlas_user/MASTER_EZRA_RUNTIME_ATLAS.png',kalyx:'../gothtechnology/assets/GOTHTECHNOLOGY_EXPANDED_SPRITE_PACK_V2/characters/KALYX/runtime_atlas_user/KALYX_RUNTIME_ATLAS.png'};
const M={air:[0,8],crouch:[5,8],hurt:[15,6],idle:[16,8],jump:[19,6],punch:[24,6],run:[27,12],special:[28,12],walk:[38,12],kick:[12,8]};
const img={},keys=new Set(),press=new Set();let loaded=0,state='title',time=0,scroll=0,spawn=.9,enemies=[],shots=[],eshots=[],bursts=[],gems=[],combo=0,last=performance.now();
for(const [k,s] of Object.entries(AS)){img[k]=new Image;img[k].onload=img[k].onerror=()=>loaded++;img[k].src=s}
const player={x:150,y:FLOOR,vx:0,vy:0,w:88,h:156,hp:100,score:0,fc:0,mc:0,act:'idle',hurt:0};
addEventListener('keydown',e=>{if(!keys.has(e.code))press.add(e.code);keys.add(e.code);if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault()});
addEventListener('keyup',e=>keys.delete(e.code));
document.querySelectorAll('[data-key]').forEach(b=>{const c=b.dataset.key,d=e=>{e.preventDefault();if(!keys.has(c))press.add(c);keys.add(c)},u=e=>{e.preventDefault();keys.delete(c)};b.addEventListener('pointerdown',d);b.addEventListener('pointerup',u);b.addEventListener('pointercancel',u);b.addEventListener('pointerleave',u)});
function reset(){Object.assign(player,{x:150,y:FLOOR,vx:0,vy:0,hp:100,score:0,fc:0,mc:0,act:'idle',hurt:0});state='play';time=scroll=combo=0;spawn=.65;enemies=[];shots=[];eshots=[];bursts=[];gems=[]}
function spawnEnemy(){enemies.push({x:W+90,y:FLOOR,vx:-145-Math.min(140,time*5),hp:42+Math.min(36,time*1.4),w:94,h:156,cd:.75+Math.random()*.55,act:'run',hurt:0})}
function rect(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y-a.h<b.y&&a.y>b.y-b.h}
function hit(e,d,fx='gold'){e.hp-=d;e.hurt=.18;bursts.push({x:e.x+42,y:e.y-88,t:0,fx});if(e.hp<=0){player.score+=250+combo*25;combo++;gems.push({x:e.x+36,y:e.y-88,vy:-420,t:0});return true}return false}
function update(dt){if(state!=='play'){if(press.has('Enter')||press.has('Space')||press.has('KeyZ'))reset();press.clear();return}time+=dt;scroll+=dt*86;player.fc=Math.max(0,player.fc-dt);player.mc=Math.max(0,player.mc-dt);player.hurt=Math.max(0,player.hurt-dt);let l=keys.has('ArrowLeft')||keys.has('KeyA'),r=keys.has('ArrowRight')||keys.has('KeyD'),jump=press.has('ArrowUp')||press.has('KeyW')||press.has('Space'),fire=press.has('KeyZ')||press.has('KeyJ'),slash=press.has('KeyX')||press.has('KeyK'),ground=player.y>=FLOOR-.5;player.vx=(r-l)*330;if(jump&&ground)player.vy=-840;if(fire&&player.fc<=0){player.fc=.24;player.act='special';shots.push({x:player.x+player.w*.76,y:player.y-100,vx:720,r:18,life:1.3})}if(slash&&player.mc<=0){player.mc=.34;player.act='punch';let z={x:player.x+56,y:player.y-34,w:118,h:96};enemies=enemies.filter(e=>!(rect(z,e)&&hit(e,28,'orange')))}player.x=Math.max(34,Math.min(W-190,player.x+player.vx*dt));player.vy+=GRAVITY*dt;player.y+=player.vy*dt;if(player.y>=FLOOR){player.y=FLOOR;player.vy=0}if(!ground)player.act=player.vy<0?'jump':'air';else if(player.fc>.1)player.act='special';else if(player.mc>.12)player.act='punch';else if(Math.abs(player.vx)>5)player.act='walk';else player.act='idle';spawn-=dt;if(spawn<=0){spawnEnemy();spawn=Math.max(.48,1.3-time*.012)+Math.random()*.42}for(const e of enemies){e.x+=e.vx*dt;e.cd-=dt;e.hurt=Math.max(0,e.hurt-dt);e.act=e.hurt>0?'hurt':'run';if(e.cd<=0&&e.x>player.x+130&&e.x<W+20){e.cd=1.05+Math.random()*.55;e.act='special';eshots.push({x:e.x-12,y:e.y-96,vx:-430,r:18,life:1.15})}if(rect({x:player.x+15,y:player.y,w:player.w-30,h:player.h-12},e)){e.x+=120;player.hp-=12;player.hurt=.24;combo=0;bursts.push({x:player.x+62,y:player.y-96,t:0,fx:'red'})}}enemies=enemies.filter(e=>e.x>-180&&e.hp>0);for(const s of shots){s.x+=s.vx*dt;s.life-=dt;for(const e of enemies)if(s.x>e.x&&s.x<e.x+e.w&&s.y>e.y-e.h&&s.y<e.y){s.life=0;hit(e,34,'blue');break}}shots=shots.filter(s=>s.life>0&&s.x<W+90);enemies=enemies.filter(e=>e.hp>0);for(const s of eshots){s.x+=s.vx*dt;s.life-=dt;if(s.x>player.x&&s.x<player.x+player.w&&s.y>player.y-player.h&&s.y<player.y){s.life=0;player.hp-=9;player.hurt=.18;combo=0;bursts.push({x:player.x+58,y:player.y-98,t:0,fx:'orange'})}}eshots=eshots.filter(s=>s.life>0&&s.x>-80);for(const g of gems){g.t+=dt;g.vy+=GRAVITY*.55*dt;g.y+=g.vy*dt;g.x-=120*dt;if(g.y>FLOOR-42)g.y=FLOOR-42;if(Math.abs(g.x-player.x)<70&&Math.abs(g.y-(player.y-80))<90){player.score+=100;g.t=99}}gems=gems.filter(g=>g.t<8);bursts.forEach(b=>b.t+=dt);bursts=bursts.filter(b=>b.t<.38);if(player.hp<=0)state='lost';if(player.score>=5000)state='win';press.clear()}
function frameImage(im,m,f,x,y,sc,flip=false,a=1){if(!im.complete||!im.naturalWidth)return;let col=f%8,row=m[0],dw=256*sc,dh=256*sc;ctx.save();ctx.globalAlpha=a;ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.drawImage(im,col*256,row*256,256,256,-dw/2,-dh,dw,dh);ctx.restore()}
function fireball(x,y,r,a,b,dir=1){let g=ctx.createRadialGradient(x,y,2,x,y,r*2.2);g.addColorStop(0,'#fff9c8');g.addColorStop(.35,a);g.addColorStop(1,'rgba(255,90,16,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r*2.2,0,Math.PI*2);ctx.fill();ctx.strokeStyle=b;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x-dir*r*2.8,y);ctx.quadraticCurveTo(x-dir*r*.5,y-r*1.3,x+dir*r*1.8,y);ctx.stroke()}
function bg(){if(img.bg.complete&&img.bg.naturalWidth){ctx.drawImage(img.bg,0,0,W,H);ctx.fillStyle='rgba(0,0,0,.34)';ctx.fillRect(0,0,W,H)}else{ctx.fillStyle='#07100e';ctx.fillRect(0,0,W,H)}for(let i=0;i<7;i++){let x=((i*220-scroll*(.3+i*.025))%(W+220))-110;ctx.fillStyle=`rgba(9,7,5,${.28+i*.05})`;ctx.fillRect(x,0,44+i*7,H)}ctx.fillStyle='#120d08';ctx.fillRect(0,FLOOR,W,H-FLOOR);ctx.fillStyle='#2e2110';for(let x=-80+((-scroll*1.8)%84);x<W+80;x+=84){ctx.fillRect(x,FLOOR+7,52,10);ctx.fillRect(x+18,FLOOR+32,38,8)}}
function hud(){ctx.fillStyle='rgba(4,3,2,.72)';ctx.fillRect(26,22,340,72);ctx.strokeStyle='rgba(255,214,109,.55)';ctx.strokeRect(26,22,340,72);ctx.fillStyle='#ffd66d';ctx.font='900 20px system-ui';ctx.fillText('LOTTO MIND VAULT RUN',46,50);ctx.fillStyle='#f8f1d4';ctx.fillText(`SCORE ${String(player.score).padStart(4,'0')}`,46,78);ctx.fillStyle='rgba(0,0,0,.55)';ctx.fillRect(W-386,32,320,28);ctx.fillStyle='#54151c';ctx.fillRect(W-382,36,312,20);ctx.fillStyle='#f0c24d';ctx.fillRect(W-382,36,312*Math.max(0,player.hp/100),20);ctx.strokeStyle='rgba(255,214,109,.75)';ctx.strokeRect(W-386,32,320,28);ctx.fillStyle='#f8f1d4';ctx.fillText('EZRA',W-386,82);if(combo>1){ctx.fillStyle='#9d4edd';ctx.fillText(`${combo} HIT`,W-148,82)}}
function title(){bg();ctx.fillStyle='rgba(0,0,0,.52)';ctx.fillRect(0,0,W,H);ctx.textAlign='center';ctx.fillStyle='#ffd66d';ctx.font='900 64px Georgia';ctx.fillText('LOTTO MIND',W/2,220);ctx.fillStyle='#f8f1d4';ctx.font='900 42px system-ui';ctx.fillText('VAULT RUN',W/2,272);ctx.fillStyle='rgba(248,241,212,.78)';ctx.font='700 21px system-ui';ctx.fillText('Ezra runs the forest vault. Kalyx guards the jackpot path.',W/2,328);ctx.fillStyle='#ffd66d';ctx.font='900 24px system-ui';ctx.fillText('PRESS START / ENTER',W/2,398);ctx.textAlign='start'}
function end(titleText,line,color){bg();enemies.forEach((e,i)=>frameImage(img.kalyx,M.idle,i%8,e.x+52,e.y,.82,true,.9));frameImage(img.ezra,M.hurt,2,player.x+56,player.y,.82,false,.86);ctx.fillStyle='rgba(0,0,0,.68)';ctx.fillRect(0,0,W,H);ctx.textAlign='center';ctx.fillStyle=color;ctx.font='900 58px Georgia';ctx.fillText(titleText,W/2,246);ctx.fillStyle='#f8f1d4';ctx.font='800 24px system-ui';ctx.fillText(line,W/2,304);ctx.fillStyle='#ffd66d';ctx.fillText(`FINAL SCORE ${player.score}`,W/2,356);ctx.fillText('PRESS START / ENTER TO RUN AGAIN',W/2,424);ctx.textAlign='start'}
function draw(now){let dt=Math.min(1/30,(now-last)/1000);last=now;update(dt);if(loaded<Object.keys(AS).length){ctx.fillStyle='#030302';ctx.fillRect(0,0,W,H);ctx.fillStyle='#ffd66d';ctx.font='900 34px system-ui';ctx.fillText('LOADING LOTTO MIND...',420,360);requestAnimationFrame(draw);return}if(state==='title'){title();requestAnimationFrame(draw);return}if(state==='lost'){end('VAULT OVERRUN','Kalyx fire reached the vault before Ezra could break through.','#ff7043');requestAnimationFrame(draw);return}if(state==='win'){end('JACKPOT CLEARED','Ezra cracked the vault run and kept the fire back.','#ffd66d');requestAnimationFrame(draw);return}bg();gems.forEach(g=>{ctx.fillStyle='#36d6ff';ctx.beginPath();ctx.moveTo(g.x,g.y-24);ctx.lineTo(g.x+24,g.y);ctx.lineTo(g.x,g.y+24);ctx.lineTo(g.x-24,g.y);ctx.closePath();ctx.fill()});enemies.forEach((e,i)=>{let mo=e.hurt>0?M.hurt:e.act==='special'?M.special:M.run;frameImage(img.kalyx,mo,Math.floor(time*13+i*2)%mo[1],e.x+56,e.y,.84,true,e.hurt>0?.72:1)});let pm=player.hurt>0?M.hurt:M[player.act]||M.idle;frameImage(img.ezra,pm,Math.floor(time*14)%pm[1],player.x+62,player.y,.78,false,player.hurt>0?.68:1);shots.forEach(s=>fireball(s.x,s.y,s.r,'#66e7ff','rgba(88,210,255,.9)',1));eshots.forEach(s=>fireball(s.x,s.y,s.r,'#ff9a2d','rgba(255,130,32,.92)',-1));bursts.forEach(b=>{let t=b.t/.38;ctx.strokeStyle=b.fx==='blue'?`rgba(90,210,255,${1-t})`:`rgba(255,170,55,${1-t})`;ctx.lineWidth=5;ctx.beginPath();ctx.arc(b.x,b.y,16+t*52,0,Math.PI*2);ctx.stroke()});hud();requestAnimationFrame(draw)}
requestAnimationFrame(draw);
