import Phaser from "phaser";
import { boardNodes } from "../content/board";
import { districts } from "../content/districts";
import { ventures } from "../content/ventures";
import type { GameState } from "../engine/state";

export class BoardScene extends Phaser.Scene {
  private state?:GameState; private tokens=new Map<string,Phaser.GameObjects.Container>(); private board!:Phaser.GameObjects.Container; private dragging=false; private lastPointer?:Phaser.Math.Vector2;
  constructor(){super("board")}
  create(){this.cameras.main.setBackgroundColor("#05040a");this.board=this.add.container(0,0);this.drawEnvironment();this.drawBoard();this.setupCamera();this.scale.on("resize",()=>this.fitOverview());this.fitOverview();}
  private pos(id:number){const n=boardNodes[id];return{x:n.x*14,y:n.y*12}}
  private drawEnvironment(){const river=this.add.graphics();river.fillStyle(0x0a4e73,.55);river.fillRoundedRect(70,690,1190,120,50);for(let i=0;i<14;i++){const line=this.add.graphics();line.lineStyle(2,0x59e8ff,.16);line.beginPath();line.moveTo(80+i*90,720);line.lineTo(150+i*90,760);line.strokePath();this.tweens.add({targets:line,x:40,duration:2200+i*80,yoyo:true,repeat:-1,ease:"Sine.InOut"});}const skyline=this.add.graphics();skyline.fillStyle(0x171027,.9);for(let i=0;i<18;i++)skyline.fillRect(100+i*62,130-(i%4)*20,42,170+(i%4)*20);const vault=this.add.graphics();vault.fillStyle(0x120b20,.95);vault.lineStyle(5,0xf5c451,.9);vault.fillCircle(700,410,96);vault.strokeCircle(700,410,96);vault.lineStyle(2,0x61e7ff,.7);vault.strokeCircle(700,410,66);this.tweens.add({targets:vault,angle:360,duration:18000,repeat:-1});}
  private drawBoard(){const route=this.add.graphics();route.lineStyle(8,0x563784,.65);const seen=new Set<string>();boardNodes.forEach(n=>n.edges.forEach(e=>{const key=[n.id,e].sort().join("-");if(seen.has(key))return;seen.add(key);const a=this.pos(n.id),b=this.pos(e);route.lineBetween(a.x,a.y,b.x,b.y)}));this.board.add(route);boardNodes.forEach((node)=>{const p=this.pos(node.id);const group=this.add.container(p.x,p.y);const disc=this.add.circle(0,0,node.kind==="venture"?18:24,node.kind==="venture"?0x21143b:0xb78432,1).setStrokeStyle(3,node.kind==="venture"?0x8b68cb:0xffdf76);const label=node.kind==="venture"?ventures[node.ventureId!].name:node.label;const text=this.add.text(0,28,label,{fontFamily:"Arial",fontSize:"12px",color:"#f8f3ff",align:"center",wordWrap:{width:110}}).setOrigin(.5,0);const marker=this.add.text(0,0,node.kind==="venture"?districts[Math.floor(node.ventureId!/3)].symbol:"✦",{fontFamily:"Arial",fontSize:"15px",color:"#fff"}).setOrigin(.5);group.add([disc,marker,text]);this.board.add(group);});}
  private setupCamera(){const cam=this.cameras.main;cam.setBounds(0,0,1400,850);this.input.on("wheel",(_p:any,_g:any,_dx:number,dy:number)=>cam.setZoom(Phaser.Math.Clamp(cam.zoom-dy*.001,.55,1.7)));this.input.on("pointerdown",(p:Phaser.Input.Pointer)=>{this.dragging=true;this.lastPointer=new Phaser.Math.Vector2(p.x,p.y)});this.input.on("pointerup",()=>this.dragging=false);this.input.on("pointermove",(p:Phaser.Input.Pointer)=>{if(!this.dragging||!this.lastPointer)return;cam.scrollX-=(p.x-this.lastPointer.x)/cam.zoom;cam.scrollY-=(p.y-this.lastPointer.y)/cam.zoom;this.lastPointer.set(p.x,p.y)});this.input.keyboard?.on("keydown",(event:KeyboardEvent)=>{const amount=45/cam.zoom;if(event.key==="ArrowLeft"||event.key==="a")cam.scrollX-=amount;if(event.key==="ArrowRight"||event.key==="d")cam.scrollX+=amount;if(event.key==="ArrowUp"||event.key==="w")cam.scrollY-=amount;if(event.key==="ArrowDown"||event.key==="s")cam.scrollY+=amount;if(event.key==="0")this.fitOverview();});}
  fitOverview(){const cam=this.cameras.main;const size=this.scale.gameSize;cam.setZoom(Math.min(size.width/1400,size.height/850)*.94);cam.centerOn(700,425)}
  followPlayer(){if(!this.state)return;const p=this.pos(this.state.players[this.state.currentPlayer].nodeId);this.cameras.main.pan(p.x,p.y,this.state.settings.reducedMotion?0:400,"Sine.easeInOut")}
  setState(state:GameState){this.state=state;state.players.forEach((player,index)=>{let token=this.tokens.get(player.id);if(!token){const p=this.pos(player.nodeId);const halo=this.add.circle(0,0,15,Phaser.Display.Color.HexStringToColor(player.color).color,.28);const sphere=this.add.circle(0,0,10,Phaser.Display.Color.HexStringToColor(player.color).color,1).setStrokeStyle(3,0xffffff);const number=this.add.text(0,0,String(index+1),{fontSize:"10px",fontStyle:"bold",color:"#080510"}).setOrigin(.5);token=this.add.container(p.x,p.y,[halo,sphere,number]).setDepth(20);this.tokens.set(player.id,token);}else{const p=this.pos(player.nodeId);token.setPosition(p.x,p.y);}})}
  async animateRoute(playerId:string,route:number[],reduced:boolean){const token=this.tokens.get(playerId);if(!token)return;for(const nodeId of route.slice(1)){const p=this.pos(nodeId);if(reduced){token.setPosition(p.x,p.y);continue;}await new Promise<void>((resolve)=>this.tweens.add({targets:token,x:p.x,y:p.y,duration:260,ease:"Sine.InOut",onComplete:()=>resolve()}));}}
}
