import type { Collection, Product } from '../commerce/types.ts';
import { fromDecimal } from '../commerce/money.ts';
import { productInformation } from './launch.ts';
import { cinematicModels } from './cinematic-models.ts';

export const collections: Collection[] = [
  ['night-protocol', 'Knight Protocol', 'The first transmission. Apparel for the hours you make your own.'],
  ['detroit-2084', 'Detroit 2084', 'A love letter to the city, stitched into a new world.'],
  ['static-saints', 'Static Saints', 'Small symbols. A signal that stays with you.'],
  ['cyber-cathedral', 'Cyber Cathedral', 'Architecture, shadow, and objects for your personal sanctuary.'],
  ['black-signal', 'Black Signal', 'Quiet essentials with a distinct frequency.'],
  ['founder-transmission', 'Founder Transmission', 'An introduction to the world of GOTHTECHNOLOGY.'],
  ['combat-systems', 'Combat Systems', 'From the character vault to your everyday equipment.'],
  ['original-artwork', 'Original Artwork', 'Detroit horizons and original photography presented through the armory.'],
].map(([handle, title, description]) => ({ handle, title, description }));

export const characters = [
  { id: 'MASTER_EZRA', name: 'Master Ezra', collection: 'night-protocol', image: 'master-ezra-headshot.webp', signal: 'Discipline / Light' },
  { id: 'KALYX', name: 'Kalyx', collection: 'black-signal', image: 'kalyx-headshot.webp', signal: 'Shadow / Precision' },
  { id: 'DETROIT_LENS_NOIR', name: 'Detroit Lens Noir', collection: 'detroit-2084', image: 'detroit-lens-noir-headshot.webp', signal: 'Guardian / Detroit' },
  { id: 'AMARA_VALENTINE', name: 'Amara Valentine', collection: 'static-saints', image: 'amara-valentine-headshot.webp', signal: 'Heart / Devotion' },
];
export const categories = ['Apparel', 'Accessories', 'Collectibles', 'Digital', 'Bundles'];
const reference = (name: string, alt: string, label = 'Reference') => ({ src: `media/${name}.webp`, alt, label, width: 1376, height: 768 });
const featuredOrder = ['night-protocol-hoodie', 'detroit-2084-shirt', 'detroit-winter-sunset-artwork', 'black-signal-beanie', 'gothtechnology-luggage-charm', 'cyber-cathedral-art-print'];
const featuredHandles = new Set(featuredOrder);
const seeds = [
  { handle: 'night-protocol-hoodie', title: 'Knight Protocol Embroidered Hoodie', subtitle: '313 / Detroit embroidery reference', dollars: 89, type: 'Apparel', collection: 'night-protocol', character: 'MASTER_EZRA', images: [reference('night-protocol-hoodie-no-charm-reference', 'Black 313 embroidered hoodie displayed without accessories in a Detroit boutique', 'Front reference'), reference('embroidery', 'Close view of the multicolor Detroit skyline and heart embroidery', 'Embroidery reference'), reference('apparel', 'Detroit sweatshirt and hoodie with a separate LottoMind charm on a brown bag', 'Styling reference'), { ...reference('night-protocol-hoodie-cathedral-styling-reference', 'Model wearing the Knight Protocol hoodie in a gold-lit cathedral; the separate beanie and LottoMind charm shown are styling accessories and are not included with the hoodie', 'Cathedral styling reference'), width: 1600, height: 900 }], sizes: ['S', 'M', 'L', 'XL', '2XL'] },
  { handle: 'boogeyman-graphic-hoodie', title: 'Boogeyman Graphic Hoodie', subtitle: 'Supplied hoodie design / armory campaign concept', dollars: 0, pricePending: true, type: 'Apparel', collection: 'black-signal', character: 'KALYX', cardImage: { ...reference('boogeyman-graphic-hoodie-campaign', 'Black Boogeyman graphic hoodie displayed on a black stone pedestal in a gold-lit cathedral armory', 'Armory campaign concept'), width: 1600, height: 900 }, images: [{ ...reference('boogeyman-graphic-hoodie-campaign', 'Black Boogeyman graphic hoodie displayed on a black stone pedestal in a gold-lit cathedral armory', 'Armory campaign concept'), width: 1600, height: 900 }, { ...reference('boogeyman-graphic-hoodie-supplied', 'Supplied front view of a black Boogeyman hoodie with oversized red and green lettering and red sleeve marks on a wood background', 'Supplied design reference'), width: 1600, height: 893 }], colors: ['As shown'], sizes: ['Size pending'], description: 'A supplied black Boogeyman graphic hoodie concept, restaged as armory campaign artwork. Final materials, sizing, price, production, and availability await owner confirmation.' },
  { handle: 'detroit-2084-shirt', title: 'Detroit 2084 Graphic T-Shirt', subtitle: 'Detroit skyline-heart graphic / supplied product reference', dollars: 36, type: 'Apparel', collection: 'detroit-2084', character: 'DETROIT_LENS_NOIR', images: [{ ...reference('detroit-2084-tee-reference', 'Black Detroit 2084 graphic T-shirt with skyline lettering and a heart emblem on a gray pedestal', 'Front reference'), width: 768, height: 768 }], sizes: ['S', 'M', 'L', 'XL', '2XL'] },
  { handle: 'black-signal-beanie', title: 'Detroit Skyline Embroidered Beanie', subtitle: 'Black / Detroit skyline embroidery reference', dollars: 19, type: 'Apparel', collection: 'detroit-2084', character: 'DETROIT_LENS_NOIR', images: [{ ...reference('detroit-skyline-beanie-reference', 'Black cuffed Detroit skyline beanie with multicolor city lettering on a dark pedestal', 'Front reference'), width: 768, height: 768 }], colors: ['Black'] },
  { handle: 'detroit-skull-cap-alt', title: 'Detroit Embroidered Skull Cap — Alt Version', subtitle: 'Black knit / alternate Detroit embroidery reference', dollars: 22, type: 'Apparel', collection: 'detroit-2084', character: 'DETROIT_LENS_NOIR', images: [{ ...reference('detroit-skull-cap-alt-reference', 'Alternate black knit skull cap with multicolor I Love Detroit skyline embroidery on a dark marble pedestal', 'Alternate front reference'), width: 896, height: 1200 }], colors: ['Black'], description: 'An alternate black knit skull-cap concept featuring the Detroit skyline-heart embroidery. Supplied product reference; final materials, measurements, and production details await owner confirmation.' },
  { handle: 'gothtechnology-luggage-charm', title: 'GOTHTECHNOLOGY Luggage Charm', subtitle: 'LottoMind character / gold hardware reference', dollars: 19.99, type: 'Accessories', collection: 'detroit-2084', character: 'DETROIT_LENS_NOIR', cardImage: { ...reference('gothtechnology-luggage-charm-armory-higgsfield-v1', 'LottoMind character luggage charm with gold hardware and a black circuit strap on a black stone pedestal in a gold-lit cathedral armory', 'Higgsfield armory campaign concept'), width: 1600, height: 900 }, images: [{ ...reference('gothtechnology-luggage-charm-armory-higgsfield-v1', 'LottoMind character luggage charm with gold hardware and a black circuit strap on a black stone pedestal in a gold-lit cathedral armory', 'Higgsfield armory campaign concept'), width: 1600, height: 900 }, reference('charm', 'Purple LottoMind mascot key charm with gold clasp and black circuit-pattern strap', 'Product reference'), reference('charm-bags', 'LottoMind charm and gold clasp attached to a brown backpack', 'Scale reference'), reference('sling-bag', 'LottoMind charm attached to a black Detroit sling bag', 'Placement reference')] },
  { handle: 'static-saints-patch-set', title: 'Static Saints Embroidered Patch Set', subtitle: 'Wear your signal / proposed patch set', dollars: 20, type: 'Accessories', collection: 'static-saints', character: 'AMARA_VALENTINE', images: [reference('patch', 'Round Detroit embroidered patch with a gold edge, skyline, red heart, and sunrise; set contents are unconfirmed', 'Patch reference'), { ...reference('static-saints-patch-white-reference', 'Close-up of a round white I Love Detroit embroidered patch with black border, red heart, gold sunrise, and multicolor skyline lettering', 'White embroidery reference'), width: 1680, height: 945 }] },
  { handle: 'cyber-cathedral-art-print', title: 'I Love Detroit Ashtray', subtitle: 'Detroit mascot / leaf-shaped ashtray concept', dollars: 28, type: 'Collectibles', collection: 'cyber-cathedral', character: 'MASTER_EZRA', cardImage: { ...reference('i-love-detroit-ashtray-armory-campaign-v2', 'I Love Detroit mascot holding a sculpted gray leaf-shaped ashtray on a black stone pedestal in a gold-lit cathedral armory', 'Armory campaign concept'), width: 1600, height: 900 }, images: [{ ...reference('mascot-leaf-collectible', 'LottoMind mascot wearing a Detroit cap and hoodie, holding a sculpted gray leaf-shaped ashtray against a dark background', 'Product reference'), width: 1200, height: 1604 }] },
  { handle: 'mobster-luggage-charm', title: 'Mobster Luggage Charm', subtitle: 'Gold hardware / Mobster character reference', dollars: 19.99, type: 'Accessories', collection: 'cyber-cathedral', character: 'KALYX', cardImage: { ...reference('mobster-luggage-charm-armory-campaign-v2', 'Mobster-themed LottoMind luggage charm in a pinstripe suit, fedora and sunglasses with gold hardware and a black circuit strap on a black stone pedestal in a gold-lit cathedral armory', 'Armory campaign concept'), width: 1600, height: 900 }, images: [{ ...reference('mobster-luggage-charm-cyan-arch-reference', 'Mobster-themed LottoMind luggage charm in a pinstripe suit, fedora and sunglasses with gold hardware, a black circuit strap and an illuminated cyan arch', 'Product reference'), width: 1600, height: 893 }, { ...reference('mobster-luggage-charm-equipment-context-reference', 'Mobster-themed LottoMind luggage charm in a pinstripe suit with gold hardware and a black circuit strap displayed with black sporting equipment', 'Equipment context'), width: 1376, height: 768 }] },
  {
    handle: 'key-knife-keychain', title: 'Key Knife Keychain — 2-Inch Utility Pocketknife', subtitle: 'Key-shaped folding utility knife / Black and Silver references', dollars: 11.99, type: 'Accessories', collection: 'black-signal', character: 'KALYX',
    cardImage: { ...reference('key-knife-gothic-open-side-campaign', 'Black key-shaped folding utility pocketknife with its silver blade fully extended, displayed horizontally on a black stone pedestal in a gold-lit Gothic cathedral with cyan portal light', 'Open-blade Gothic armory campaign concept'), width: 2752, height: 1536 },
    images: [{ ...reference('key-knife-black-reference', 'Black key-shaped folding utility pocketknife shown against a white background with its two-inch blade partially visible', 'Black reference'), width: 1080, height: 1080 }, { ...reference('key-knife-silver-reference', 'Silver key-shaped folding utility pocketknife shown against a white background with its two-inch blade partially visible', 'Silver reference'), width: 1280, height: 1280 }, { ...reference('key-knife-gothic-open-side-campaign', 'Black key-shaped folding utility pocketknife with its silver blade fully extended, displayed horizontally on a black stone pedestal in a gold-lit Gothic cathedral with cyan portal light', 'Open-blade Gothic armory campaign concept'), width: 2752, height: 1536 }, { ...reference('key-knife-signal-ensemble-campaign', 'Four LottoMind signal figures displayed together with black key-shaped folding utility knives attached to their keychain hardware in a dark Gothic armory', 'Signal ensemble campaign concept'), width: 1254, height: 1254 }, { ...reference('key-knife-cyan-mobster-campaign', 'Cyan-circuit Mobster LottoMind figure with a black key-shaped folding utility knife connected to the same keychain hardware in a dark Gothic armory', 'Cyan Mobster campaign concept'), width: 1254, height: 1254 }, { ...reference('key-knife-champ-campaign', 'Champ LottoMind figure with a black key-shaped folding utility knife connected to the same keychain hardware in a dark Gothic armory', 'Champ campaign concept'), width: 1254, height: 1254 }, { ...reference('key-knife-gold-mobster-campaign', 'Gold Mobster LottoMind figure with a black key-shaped folding utility knife connected to the same keychain hardware in a dark Gothic armory', 'Gold Mobster campaign concept'), width: 1254, height: 1254 }, { ...reference('key-knife-observer-campaign', 'Observer LottoMind figure with a black key-shaped folding utility knife connected to the same keychain hardware in a dark Gothic armory', 'Observer campaign concept'), width: 1254, height: 1254 }],
    colors: ['Black', 'Silver'], sizes: ['One size'], description: 'Looks like a key and is designed to cut like a small utility blade. Its slim profile is intended to fit neatly on a keyring without excessive bulk for convenient carrying. The supplied reference shows a pointed two-inch blade intended to fold into the housing; treat it as sharp. Final blade measurement, fold security or locking mechanism, materials, age requirements, safety guidance, permitted uses, legal carry and shipping restrictions, production, and availability require owner approval before launch. Supplied references and campaign composites only.'
  },
  { handle: 'black-signal-digital-pack', title: 'Black Signal Gun Charm Rail Adapter Pack', subtitle: 'Heavy-duty rail adapter / supplied product references', dollars: 12, type: 'Accessories', collection: 'black-signal', character: 'KALYX', images: [{ ...reference('black-signal-gun-charm-rail-adapter-black-group-reference', 'Black rail adapter displayed with two LottoMind character charms and gold hardware on a black background', 'Black-background group reference'), width: 1376, height: 768 }, { ...reference('black-signal-gun-charm-rail-adapter-equipment-context-reference', 'Black rail adapter photographed on a white surface in front of black sporting equipment', 'Equipment context'), width: 1600, height: 893 }, { ...reference('black-signal-gun-charm-rail-adapter-charm-group-reference', 'Black rail adapter displayed between two LottoMind character charms with gold hardware on a white background', 'White-background group reference'), width: 1600, height: 893 }, { ...reference('black-signal-gun-charm-rail-adapter-black-fabric-reference', 'Black metal heavy-duty rail adapter photographed from the front on textured black fabric', 'Front reference'), width: 1376, height: 768 }, { ...reference('black-signal-gun-charm-rail-adapter-underside-reference', 'Black metal heavy-duty rail adapter showing the clamp, spring and underside hardware on a white background', 'Underside reference'), width: 300, height: 300 }] },
  { handle: 'key-knife-gun-attachment-bundle', title: 'Key Knife + Gun Attachment Bundle', subtitle: 'Key-shaped utility knife / Black Signal rail attachment', dollars: 39, type: 'Bundles', collection: 'black-signal', character: 'KALYX', images: [{ ...reference('key-knife-gun-attachment-bundle-closed-reference', 'Black Key Knife Keychain folded closed beside a Black Signal rail attachment and a Mobster charm used as styling reference on a black background', 'Closed bundle reference'), width: 1376, height: 768 }, { ...reference('key-knife-gun-attachment-bundle-open-reference', 'Black Key Knife Keychain with its silver blade open beside a Black Signal rail attachment and a Mobster charm used as styling reference on a black background', 'Open bundle reference'), width: 1376, height: 768 }], colors: ['Black'], sizes: ['One size'], description: 'A proposed two-item bundle pairing the black Key Knife Keychain with the Black Signal gun charm rail attachment for $39. The Mobster luggage charm pictured in the supplied references is styling only and is not included. Final blade measurement, fold security or locking mechanism, rail compatibility and fit, materials, age requirements, safety guidance, permitted uses, legal carry and shipping restrictions, production, inventory, and availability require owner approval before launch. Supplied campaign references only.' },
  { handle: 'founder-loadout-bundle', title: 'Founder Loadout Bundle', subtitle: 'Your first transmission / contents awaiting confirmation', dollars: 129, type: 'Bundles', collection: 'founder-transmission', character: 'MASTER_EZRA', images: [reference('apparel', 'Detroit apparel and charm styling reference; proposed bundle contents are unconfirmed', 'Styling reference')] },
  { handle: 'detroit-skyline-cap', title: 'Detroit Skyline Embroidered Cap', subtitle: 'Black / Detroit skyline embroidery reference', dollars: 32, type: 'Apparel', collection: 'detroit-2084', character: 'DETROIT_LENS_NOIR', images: [{ ...reference('detroit-skyline-cap-reference', 'Black Detroit skyline embroidered baseball cap on a dark marble pedestal', 'Front reference'), width: 768, height: 768 }], colors: ['Black'] },
  { handle: 'detroit-riverfront-sunset-artwork', title: 'Detroit Riverfront Sunset Artwork', subtitle: 'Detroit riverfront / supplied original artwork reference', dollars: 0, pricePending: true, type: 'Collectibles', collection: 'original-artwork', character: 'DETROIT_LENS_NOIR', cardImage: { ...reference('detroit-riverfront-sunset-artwork-armory-campaign', 'Framed orange-sunset Detroit riverfront artwork displayed on a black stone pedestal in a gold-lit cathedral armory', 'Armory campaign concept'), width: 1600, height: 900 }, images: [{ ...reference('detroit-riverfront-sunset-artwork-armory-campaign', 'Framed orange-sunset Detroit riverfront artwork displayed on a black stone pedestal in a gold-lit cathedral armory', 'Armory campaign concept'), width: 1600, height: 900 }, { ...reference('detroit-riverfront-sunset-artwork-gothic-frame-alt', 'Detroit riverfront sunset artwork in a carved black wooden Gothic frame with antique-gold corner details', 'Gothic frame alt'), width: 1600, height: 900 }, { ...reference('detroit-riverfront-sunset-artwork-supplied', 'Supplied reference photograph of a framed orange-sunset Detroit skyline and riverfront artwork on a workshop table', 'Supplied artwork reference'), width: 960, height: 638 }], colors: ['As shown'], sizes: ['Dimensions pending'], description: 'A supplied framed Detroit riverfront artwork reference, restaged as armory campaign artwork with an alternate black-and-gold wooden Gothic frame concept. Price, dimensions, edition details, framing, production, and availability await owner confirmation.' },
  { handle: 'detroit-winter-sunset-artwork', title: 'Detroit Winter Sunset Artwork', subtitle: 'Detroit winter riverfront / supplied original photograph', dollars: 0, pricePending: true, type: 'Collectibles', collection: 'original-artwork', character: 'DETROIT_LENS_NOIR', cardImage: { ...reference('detroit-winter-sunset-artwork-armory-campaign', 'Framed winter-sunset Detroit riverfront photograph displayed on a black stone pedestal in a gold-lit cathedral armory', 'Armory campaign concept'), width: 1600, height: 900 }, images: [{ ...reference('detroit-winter-sunset-artwork-armory-campaign', 'Framed winter-sunset Detroit riverfront photograph displayed on a black stone pedestal in a gold-lit cathedral armory', 'Armory campaign concept'), width: 1600, height: 900 }, { ...reference('detroit-winter-sunset-artwork-gothic-frame-alt', 'Detroit winter sunset photograph in a carved black wooden Gothic frame with antique-gold corner details', 'Gothic frame alt'), width: 1600, height: 900 }, { ...reference('detroit-winter-sunset-artwork-supplied', 'Supplied Detroit winter sunset photograph with a bare tree, frozen river and city skyline', 'Supplied artwork reference'), width: 720, height: 478 }], colors: ['As shown'], sizes: ['Dimensions pending'], description: 'A supplied Detroit winter sunset photograph, restaged as a framed armory campaign concept with an alternate black-and-gold wooden Gothic frame. Price, dimensions, edition details, framing, production, and availability await owner confirmation.' },
];

export const demoProducts: Product[] = seeds.map((seed, index) => {
  const sizes = seed.sizes ?? ['One size'];
  const colors = seed.colors ?? ['Obsidian'];
  const pricePending = 'pricePending' in seed && seed.pricePending === true;
  const price = fromDecimal(String(seed.dollars), 'USD');
  return { id: `demo-${seed.handle}`, handle: seed.handle, title: seed.title, subtitle: seed.subtitle,
    description: 'description' in seed && seed.description ? seed.description : `${seed.subtitle}. Part of the ${collections.find(c => c.handle === seed.collection)?.title} collection. A concept from the GOTHTECHNOLOGY fighting-game world.`,
    price, compareAtPrice: null, productType: seed.type, collection: seed.collection, collections: [seed.collection, 'combat-systems'], tags: [seed.type, seed.collection, ...(pricePending ? ['Price pending'] : [])],
    images: seed.images.map(image => ({...image, kind: /campaign|gothic frame alt/i.test(image.label) ? 'CAMPAIGN CONCEPT' as const : /scale|placement/i.test(image.label) ? 'SCALE REFERENCE' as const : /embroidery/i.test(image.label) ? 'DETAIL REFERENCE' as const : 'SUPPLIED PRODUCT REFERENCE' as const})),
    cardImage: seed.handle === 'detroit-winter-sunset-artwork'
      ? {...seed.images[1], kind: 'CAMPAIGN CONCEPT' as const}
      : seed.cardImage ? {...seed.cardImage, kind: /campaign/i.test(seed.cardImage.label) ? 'CAMPAIGN CONCEPT' as const : 'SUPPLIED PRODUCT REFERENCE' as const} : undefined,
    model: seed.handle === 'mobster-luggage-charm' ? cinematicModels.mobsterCharm : null,
    video: seed.handle === 'night-protocol-hoodie' ? 'media/knight-protocol-supplied-product-film-v1.mp4'
      : seed.handle === 'black-signal-digital-pack' ? 'media/black-signal-rail-adapter-supplied-film-v1.mp4'
      : seed.handle === 'mobster-luggage-charm' ? 'https://www.youtube-nocookie.com/embed/0yPqZEvKnFU?rel=0&autoplay=1' : null,
    colors, sizes,
    information: productInformation(seed.handle),
    variants: colors.flatMap(color => sizes.map(size => ({ id: `demo-${seed.handle}-${color.toLowerCase().replaceAll(' ', '-')}-${size.toLowerCase().replaceAll(' ', '-')}`, title: `${size} / ${color}`, size, color, available: !pricePending, price }))),
    inventory: null, materials: null, fabricWeight: null, finish: null, careInstructions: null, shippingMessage: null, returnMessage: null,
    featured: featuredHandles.has(seed.handle), digital: seed.type === 'Digital', preorder: false, demo: true, characterAssociation: seed.character,
    seo: { title: seed.title, description: `${seed.title} — a GOTHTECHNOLOGY demo catalog concept.` },
  };
});

export function selectVariant(product: Product, size: string, color: string) {
  return product.variants.find(v => v.size === size && v.color === color) ?? null;
}
export function filterProducts(products: Product[], filters: { search?: string; category?: string; collection?: string; size?: string; color?: string; availability?: string; sort?: string } = {}) {
  const term = (filters.search ?? '').trim().toLocaleLowerCase();
  const items = products.filter(p => (!term || `${p.title} ${p.description} ${p.tags.join(' ')}`.toLowerCase().includes(term))
    && (!filters.category || p.productType === filters.category)
    && (!filters.collection || p.collections.includes(filters.collection))
    && p.variants.some(v => (!filters.size || v.size === filters.size) && (!filters.color || v.color === filters.color)
      && (!filters.availability || (filters.availability === 'available' ? v.available : !v.available))));
  return items.sort((a, b) => {
    const pendingOrder = Number(a.price.amount <= 0) - Number(b.price.amount <= 0);
    if (pendingOrder && (filters.sort === 'price-low' || filters.sort === 'price-high')) return pendingOrder;
    return filters.sort === 'price-low' ? a.price.amount - b.price.amount
    : filters.sort === 'price-high' ? b.price.amount - a.price.amount
    : filters.sort === 'name' ? a.title.localeCompare(b.title)
    : filters.sort === 'newest' ? products.indexOf(b) - products.indexOf(a)
    : a.featured && b.featured ? featuredOrder.indexOf(a.handle) - featuredOrder.indexOf(b.handle)
    : Number(b.featured) - Number(a.featured);
  });
}

