$ErrorActionPreference='Stop'
$engineRoot=Split-Path -Parent $PSScriptRoot
$packRoot=Resolve-Path "$engineRoot/../.."
$engineSdk='C:\Users\digit\Documents\Unity\Editors\6000.3.24f1\Editor\Data\PlaybackEngines\WebGLSupport\BuildTools\Emscripten'
$env:EM_CONFIG=Join-Path $engineSdk '.emscripten'
$out=Join-Path $packRoot 'ride-core/src/engine'
New-Item -ItemType Directory -Force $out | Out-Null
$exports=[regex]::Matches((Get-Content "$PSScriptRoot/runtime.cpp" -Raw),'(?:int|double) (bf_\w+)\(') | ForEach-Object { "'_$($_.Groups[1].Value)'" }
$exportArgument='-sEXPORTED_FUNCTIONS=['+($exports -join ',')+']'
& "$engineSdk/python/python.exe" "$engineSdk/emscripten/emcc.py" "$PSScriptRoot/runtime.cpp" "-I$engineRoot/upstream/src" '-std=c++17' '-O2' '-fno-exceptions' '-sSTANDALONE_WASM=1' '-sFILESYSTEM=0' '-sINITIAL_MEMORY=16777216' '-sTOTAL_STACK=1048576' $exportArgument '--no-entry' '-o' "$out/breadflower.wasm"
if($LASTEXITCODE -ne 0){exit $LASTEXITCODE}
$hash=(Get-FileHash "$out/breadflower.wasm" -Algorithm SHA256).Hash.ToLowerInvariant()
@"
// Generated by the pinned Unity Emscripten build; public handshake identity.
export const ENGINE_ID = Object.freeze({ engine: '6b4d4e1f10dee9b1c8932db95f91b92e3eceb7db', module: '$hash', bridgeAbi: 4, engineRules: 'static-royale-cpp-2' });
"@ | Set-Content "$out/identity.ts"
Write-Output "PASS selected C++ Wasm artifact SHA256 $hash"

