/** Manufacturer speed/power/proportion references; handling coefficients are game tuning. */
export const EBIKES=[
  {
    "id": "talaria",
    "name": "Talaria Sting Pro MX5",
    "topKph": 95,
    "mass": 76,
    "peakWatts": 13400,
    "torque": 500,
    "wheelbase": 1.25,
    "frontRadius": 0.32,
    "rearRadius": 0.32,
    "seat": 0.84,
    "acceleration": 5,
    "braking": 7.5,
    "steering": 0.57,
    "steerResponse": 9,
    "grip": 0.88,
    "suspension": 0.18,
    "regen": 0.32,
    "color": 1526921,
    "feel": "Light trail bike · quick direction changes · regenerative coasting",
    "source": "https://www.talariamoto.it/wp-content/uploads/2024/10/sting-talaria-mx5-pro.pdf"
  },
  {
    "id": "ultra",
    "name": "Sur-Ron Ultra Bee HP (2025)",
    "topKph": 95,
    "mass": 91,
    "peakWatts": 21000,
    "torque": 511.8,
    "wheelbase": 1.38,
    "frontRadius": 0.321,
    "rearRadius": 0.318,
    "seat": 0.91,
    "acceleration": 6.5,
    "braking": 8.3,
    "steering": 0.52,
    "steerResponse": 7,
    "grip": 0.93,
    "suspension": 0.24,
    "regen": 0.5,
    "color": 9273441,
    "feel": "Balanced enduro · strong low-speed pull · 240 mm suspension",
    "source": "https://sur-ron.jp/lineup/ultra-bee/"
  },
  {
    "id": "sr",
    "name": "E Ride Pro SR (2025)",
    "topKph": 112.654,
    "mass": 83,
    "peakWatts": 25000,
    "torque": 560,
    "wheelbase": 1.35,
    "frontRadius": 0.321,
    "rearRadius": 0.318,
    "seat": 0.83,
    "acceleration": 7.8,
    "braking": 8.6,
    "steering": 0.54,
    "steerResponse": 8,
    "grip": 0.94,
    "suspension": 0.2,
    "regen": 0.43,
    "color": 2107433,
    "feel": "Fast sprinter · sharp throttle · adjustable sport suspension",
    "source": "https://www.eridepro.com/products/pro-sr"
  },
  {
    "id": "varg",
    "name": "Stark VARG MX 1.2 Alpha",
    "topKph": 154,
    "mass": 118,
    "peakWatts": 60000,
    "torque": 938,
    "wheelbase": 1.48,
    "frontRadius": 0.347,
    "rearRadius": 0.34,
    "seat": 0.947,
    "acceleration": 8.8,
    "braking": 9.2,
    "steering": 0.48,
    "steerResponse": 5.8,
    "grip": 0.98,
    "suspension": 0.31,
    "regen": 0.58,
    "color": 12133658,
    "feel": "Full-size motocross · highest power · stable sweeping turns · 310 mm travel",
    "source": "https://assets.starkfuture.com/technical-documents/Stark_VARG_MX_1_2_Owners_Manual_ENG_2025-08_Rev_2.pdf"
  }
] as const;
export const EUC_MODELS=[
  {
    "id": "city",
    "name": "City 16 · V8S-inspired",
    "topKph": 34.923,
    "mass": 16,
    "watts": 2000,
    "suspension": 0,
    "driveAcceleration": 3.4,
    "brakeAcceleration": 5.8,
    "launchJerk": 11,
    "lowSpeedYaw": 3,
    "highSpeedYaw": 0.72,
    "maxLean": 0.7,
    "hopSpeed": 2.3,
    "color": 2727382,
    "feel": "Lightweight · tight turns · firm, unsuspended ride",
    "source": "https://inmotionworld.com/products/inmotion-v8s"
  },
  {
    "id": "tour",
    "name": "Touring 18 · V11Y-inspired",
    "topKph": 59.546,
    "mass": 30,
    "watts": 7000,
    "suspension": 0.085,
    "driveAcceleration": 5,
    "brakeAcceleration": 7,
    "launchJerk": 15,
    "lowSpeedYaw": 2.55,
    "highSpeedYaw": 0.58,
    "maxLean": 0.8,
    "hopSpeed": 2.5,
    "color": 15246404,
    "feel": "Smooth air suspension · progressive throttle · relaxed touring",
    "source": "https://inmotionworld.com/products/inmotion-v11y"
  },
  {
    "id": "trail",
    "name": "Trail 16 · V14 Pro-inspired",
    "topKph": 80.467,
    "mass": 39,
    "watts": 9000,
    "suspension": 0.085,
    "driveAcceleration": 7.8,
    "brakeAcceleration": 9.4,
    "launchJerk": 24,
    "lowSpeedYaw": 2.8,
    "highSpeedYaw": 0.6,
    "maxLean": 0.9,
    "hopSpeed": 2.7,
    "color": 15952672,
    "feel": "High torque · knobby tire · progressive suspension · agile trail response",
    "source": "https://inmotionworld.com/products/inmotionadventure"
  },
  {
    "id": "speed",
    "name": "Speed 22 · V13 Pro-inspired",
    "topKph": 90.123,
    "mass": 50,
    "watts": 10000,
    "suspension": 0.09,
    "driveAcceleration": 6.8,
    "brakeAcceleration": 8.8,
    "launchJerk": 18,
    "lowSpeedYaw": 2.05,
    "highSpeedYaw": 0.45,
    "maxLean": 0.84,
    "hopSpeed": 2.2,
    "color": 11747151,
    "feel": "Large wheel · planted high-speed handling · wider turning arc",
    "source": "https://eu.inmotionworld.com/products/inmotion-challenger-pro"
  }
] as const;
export type EbikeProfile=typeof EBIKES[number];
export type EucProfile=typeof EUC_MODELS[number];
export const isCycle=(value:string)=>value==='bicycle'||value.startsWith('ebike:');
export const ebikeProfile=(value:string)=>EBIKES.find(p=>value==='ebike:'+p.id);
export const eucProfile=(value:string)=>EUC_MODELS.find(p=>value==='euc:'+p.id);
export function vehicleOptions(select:HTMLSelectElement){const previous=select.value;select.replaceChildren(new Option('Classic electric unicycle','euc'),...EUC_MODELS.map(p=>new Option(p.name+' · '+Math.round(p.topKph)+' km/h','euc:'+p.id)));select.value=[...select.options].some(o=>o.value===previous)?previous:'euc';}
export function vehicleSummary(value:string){const p=ebikeProfile(value)||eucProfile(value);return p?p.name+' · '+Math.round(p.topKph)+' km/h ceiling ('+Math.round(p.topKph/1.609344)+' mph) · '+p.feel:value==='bicycle'?'Bicycle · pedal, coast and brake.':'Original electric unicycle · familiar ride and tricks.';}
export function eucHandling(p:EucProfile){return {maxSpeed:p.topKph/3.6,reverseSpeed:2.8,driveAcceleration:p.driveAcceleration,brakeAcceleration:p.brakeAcceleration,launchJerk:p.launchJerk,brakeJerk:60,releaseJerk:25,lowSpeedYaw:p.lowSpeedYaw,highSpeedYaw:p.highSpeedYaw,maxLean:p.maxLean,hopSpeed:p.hopSpeed,version:'Digital Static Motion 4.1 / '+p.name};}

export function eucSteering(p:EucProfile,speed:number,input:number){const blend=Math.exp(-Math.abs(speed)/4.8),base=.62+(2.55-.62)*blend,wanted=p.highSpeedYaw+(p.lowSpeedYaw-p.highSpeedYaw)*blend;return Math.max(-1,Math.min(1,input*wanted/base));}
