import * as T from 'three';
import {BicycleView} from './riding/bicycleView.ts';
import {GLTFLoader,type GLTF} from './compressedGLTFLoader.ts';
import type {RidePose} from '@digital-static/ridecore';
import {EBIKES,EUC_MODELS,ebikeProfile,eucProfile,type EbikeProfile} from './electricVehicles.ts';
const pending=new Map<string,Promise<GLTF>>();
export async function loadElectricAssets(data:Map<string,GLTF>,value:string,race=false){const bike=ebikeProfile(value),euc=eucProfile(value),ids=bike?(race?EBIKES:[bike]).map(p=>'Ebike_'+p.id):euc?(race?EUC_MODELS:[euc]).map(p=>'Euc_'+p.id):[];await Promise.all(ids.map(async id=>{if(data.has(id))return;let p=pending.get(id);if(!p){p=new GLTFLoader().loadAsync('/exports/electric/'+id+'.glb');pending.set(id,p);p.catch(()=>pending.delete(id));}data.set(id,await p);}));}
const v=()=>new T.Vector3(),q=()=>new T.Quaternion();
type Limb={a:T.Object3D;b:T.Object3D;c:T.Object3D;rotation:T.Quaternion;side:number};
function point(a:T.Object3D,b:T.Object3D,target:T.Vector3){const from=a.getWorldPosition(v()),rotation=a.getWorldQuaternion(q()).premultiply(q().setFromUnitVectors(b.getWorldPosition(v()).sub(from).normalize(),target.clone().sub(from).normalize()));a.quaternion.copy(a.parent!.getWorldQuaternion(q()).invert().multiply(rotation));a.updateWorldMatrix(false,true);}
function fit(l:Limb,target:T.Vector3,pole:T.Vector3,rotation:T.Quaternion){const a=l.a.getWorldPosition(v()),b=l.b.getWorldPosition(v()),c=l.c.getWorldPosition(v()),l1=a.distanceTo(b),l2=b.distanceTo(c),dir=target.clone().sub(a),d=Math.max(.02,Math.min(dir.length(),l1+l2-.001));dir.normalize();pole.addScaledVector(dir,-pole.dot(dir)).normalize();const along=(l1*l1+d*d-l2*l2)/(2*d),bend=Math.sqrt(Math.max(0,l1*l1-along*along));point(l.a,l.b,a.clone().addScaledVector(dir,along).addScaledVector(pole,bend));point(l.b,l.c,a.clone().addScaledVector(dir,d));l.c.quaternion.copy(l.c.parent!.getWorldQuaternion(q()).invert().multiply(rotation));l.c.updateWorldMatrix(false,true);}
/** Saddle/footpeg fit with stationary boots; wheels and fork are animated from physics. */
export class EbikeView extends BicycleView {
 readonly profile:EbikeProfile;private motoLegs:Limb[]=[];private motoArms:Limb[]=[];
 constructor(asset:GLTF,human:GLTF,profile:EbikeProfile,npc=false){super(asset,human,2,npc);this.profile=profile;this.root.name='Electric moto · '+profile.name;for(const o of [...this.bike.children])if(!o.name)o.removeFromParent();this.root.updateMatrixWorld(true);for(const side of ['Left','Right'])for(const arm of [false,true]){const a=this.rider.getObjectByName(side+(arm?'Arm':'UpLeg'))!,b=this.rider.getObjectByName(side+(arm?'ForeArm':'Leg'))!,c=this.rider.getObjectByName(side+(arm?'Hand':'Foot'))!;(arm?this.motoArms:this.motoLegs).push({a,b,c,rotation:c.getWorldQuaternion(q()),side:Math.sign(c.getWorldPosition(v()).x)||1});}}
 override apply(p:RidePose,steering=0,_pedals=0){super.apply(p,steering,0);if(!this.profile)return;const f=this.profile;this.frame.position.y=-Math.max(-.015,Math.min(.065,p.suspensionOffset*.4));const hips=this.frame.localToWorld(new T.Vector3(-p.rollAngle*.035,f.seat+.18,-.20-p.brakeAmount*.025));this.hips.position.copy(this.hips.parent!.worldToLocal(hips));this.root.updateMatrixWorld(true);const forward=new T.Vector3(0,0,1).transformDirection(this.frame.matrixWorld),right=new T.Vector3(1,0,0).transformDirection(this.frame.matrixWorld),rotation=this.frame.getWorldQuaternion(q());for(const l of this.motoLegs){const target=this.frame.localToWorld(new T.Vector3(l.side*.19,.405,-.09));if(l===this.motoLegs[0]&&p.stopFoot>.01)target.lerp(this.root.localToWorld(new T.Vector3(l.side*.31,.07,-.16)),p.stopFoot);fit(l,target,forward.clone(),rotation.clone().multiply(l.rotation));}for(const l of this.motoArms){const grip=this.bike.getObjectByName(l.side>0?'Grip001':'Grip')!,target=grip.getWorldPosition(v()).addScaledVector(forward,-.025).add(new T.Vector3(0,.015,0));fit(l,target,forward.clone().multiplyScalar(-.6).addScaledVector(right,l.side*.6),rotation.clone().multiply(l.rotation));}const front=this.bike.getObjectByName('Bicycle_Front_Wheel_Pivot');if(front)front.rotation.x=p.wheelSpin*f.rearRadius/f.frontRadius;this.root.updateMatrixWorld(true);}
}
