import {makeRidePicker} from './ridePicker.ts';
import {isCycle,vehicleSummary} from './electricVehicles.ts';
import {MODES,type RunMode} from './elmwood-gameplay.ts';
export function makeElmwoodMainMenu(canvas:HTMLCanvasElement,pause:()=>void,resume:()=>void,start:(mode:RunMode,players:number)=>Promise<void>,settings:()=>void){
  const dialog=document.createElement('dialog');dialog.id='elmwood-main-menu';dialog.setAttribute('aria-labelledby','elmwood-menu-title');
  dialog.style.setProperty('--title-art',`url("${new URL(import.meta.env.BASE_URL+'elmwood/title-screen.png',location.href).href}")`);
  dialog.innerHTML=`<div class="menu-inner"><p class="menu-eyebrow">DIGITAL STATIC · DETROIT</p><h1 id="elmwood-menu-title">Elmwood Explorer</h1><p>Pick a ride. Press Play. Explore at your own pace.</p><label for="menu-players">Players</label><select id="menu-players"><option value="1">Solo ride</option><option value="2">2 players · split screen</option></select><fieldset><legend>Game mode</legend>${MODES.map(([id,label],i)=>`<label class="mode-card"><input type="radio" name="menu-mode" value="${id}" ${i===0?'checked':''}><span><strong>${label}</strong><small>${id==='free'?'Explore the cemetery at your own pace.':id==='sprint'?'Race three riders through Creek Lane. No time limit.':id==='tricks'?'Two minutes to land tricks and build your score.':'Follow the creek route with no time limit.'}</small></span></label>`).join('')}</fieldset><div class="menu-actions"><button id="menu-play">Play · free ride</button><button id="menu-resume">Resume current ride</button><button id="menu-settings">Controls &amp; settings</button><button id="menu-explore">Explore landmarks</button></div><a href="../swoop-detroit/" target="_top">← Back to Swoop Detroit</a><p id="menu-feedback" role="status"></p></div>`;
  dialog.querySelector('#elmwood-menu-title')!.innerHTML='Elmwood<span>Explorer</span>';
  dialog.querySelector('.menu-inner > h1 + p')!.textContent='Ride, race, or play tag. New here? Try Practice first.';
  const caption=document.createElement('p');caption.className='menu-art-caption';caption.textContent='DETROIT, MICHIGAN / ELMWOOD';dialog.append(caption);
  document.body.append(dialog);const get=<E extends HTMLElement>(id:string)=>dialog.querySelector<E>('#'+id)!;
  const selectors=document.createElement('div');selectors.className='menu-selectors';const vehicleInfo=document.createElement('p');vehicleInfo.id='menu-vehicle-performance';vehicleInfo.setAttribute('role','status');
  for(const [sourceId,id,label] of [['ride-outfit','menu-rider','Rider'],['elmwood-quality','menu-quality','Graphics'],['session-vehicle','menu-vehicle','Vehicle'],['session-bike-style','menu-bike-style','Bicycle color and style'],['session-race-difficulty','menu-race-difficulty','Race difficulty']]){const source=document.getElementById(sourceId) as HTMLSelectElement,field=document.createElement('label'),copy=document.createElement('select');field.htmlFor=id;field.textContent=label;copy.id=id;copy.replaceChildren(...[...source.options].map(o=>new Option(o.text,o.value)));copy.value=source.value;copy.onchange=()=>{source.value=copy.value;source.dispatchEvent(new Event('change'));if(id==='menu-vehicle'){vehicleInfo.textContent=vehicleSummary(copy.value);get('menu-bike-style').parentElement!.hidden=copy.value!=='bicycle';}};field.append(copy);selectors.append(field);}
  selectors.append(vehicleInfo);
  const wheels=makeRidePicker(get<HTMLSelectElement>('menu-vehicle'));dialog.querySelector('fieldset')!.before(wheels.root);
  const more=document.createElement('details');more.id='menu-more-options';more.innerHTML='<summary>More options <small>Rider, bike, graphics &amp; playing together</small></summary>';
  more.append(get('menu-players').previousElementSibling!,get('menu-players'),selectors);
  const extraModes=document.createElement('fieldset');extraModes.innerHTML='<legend>More activities</legend>';
  for(const card of [...dialog.querySelectorAll<HTMLElement>('.mode-card')]){const mode=card.querySelector<HTMLInputElement>('input')!.value;card.querySelector('strong')!.textContent=mode==='free'?'Explore freely':mode==='sprint'?'Race the riders':mode==='tricks'?'Try tricks':'Follow the creek';if(mode==='tricks'||mode==='tour')extraModes.append(card);}
  more.append(extraModes);const extras=document.createElement('div');extras.id='menu-more-activities';extras.className='menu-extra-actions';extras.append(get('menu-settings'),get('menu-explore'));more.append(extras);get('menu-feedback').before(more);
  const how=document.createElement('p');how.className='menu-simple-help';how.textContent='1. Choose a ride.  2. Press Play.  3. Use the left stick or arrow keys to move. Pause whenever you like.';get('menu-play').parentElement!.after(how);
  const select=get<HTMLSelectElement>('menu-players'),play=get<HTMLButtonElement>('menu-play'),back=get<HTMLButtonElement>('menu-resume');
  const updatePlay=()=>{const m=dialog.querySelector<HTMLInputElement>('input[name="menu-mode"]:checked')!.value;play.textContent=m==='free'?'Play · free ride':m==='sprint'?'Play · race':m==='tricks'?'Play · tricks':'Play · creek adventure';if(m==='tricks'||m==='tour')more.open=true;};
  dialog.querySelectorAll<HTMLInputElement>('input[name="menu-mode"]').forEach(input=>input.addEventListener('change',updatePlay));
  function open(){pause();get<HTMLSelectElement>('menu-rider').value=(document.getElementById('ride-outfit') as HTMLSelectElement).value;get<HTMLSelectElement>('menu-quality').value=(document.getElementById('elmwood-quality') as HTMLSelectElement).value;for(const [src,dst] of [['session-vehicle','menu-vehicle'],['session-bike-style','menu-bike-style'],['session-race-difficulty','menu-race-difficulty']])get<HTMLSelectElement>(dst).value=(document.getElementById(src) as HTMLSelectElement).value;wheels.update();vehicleInfo.textContent=vehicleSummary(get<HTMLSelectElement>('menu-vehicle').value);get('menu-bike-style').parentElement!.hidden=get<HTMLSelectElement>('menu-vehicle').value!=='bicycle';get('menu-feedback').textContent='';select.value=document.querySelector<HTMLSelectElement>('#session-players')!.value;const mode=document.querySelector<HTMLSelectElement>('#session-mode')!.value;dialog.querySelector<HTMLInputElement>(`input[value="${mode}"]`)!.checked=true;back.hidden=canvas.dataset.riding!=='true';updatePlay();if(!dialog.open)dialog.showModal();play.focus();}
  back.onclick=()=>{dialog.close();resume();canvas.focus();};dialog.oncancel=()=>{canvas.focus();};
  play.onclick=async()=>{play.disabled=true;get('menu-feedback').textContent='Loading your ride…';if(isCycle(get<HTMLSelectElement>('menu-vehicle').value)&&(select.value!=='1'||dialog.querySelector<HTMLInputElement>('input[name="menu-mode"]:checked')!.value==='tricks')){get('menu-feedback').textContent='Choose Solo + Free ride, Creek lane race or Discovery for the bicycle. Split and tricks use the EUC.';play.disabled=false;return;}try{await start(dialog.querySelector<HTMLInputElement>('input[name="menu-mode"]:checked')!.value as RunMode,Number(select.value));if(canvas.dataset.riding==='true')dialog.close();else get('menu-feedback').textContent=document.querySelector('#session-message')?.textContent||'Choose controls in Settings before starting.';}finally{play.disabled=false;}};
  get<HTMLButtonElement>('menu-settings').onclick=()=>{dialog.close();settings();};get<HTMLButtonElement>('menu-explore').onclick=()=>{dialog.close();canvas.dispatchEvent(new Event('elmwood-stop-ride'));canvas.focus();};
  canvas.addEventListener('elmwood-main-menu',open);return {open};
}
