import {VoiceChat} from '../../../ride-core/src/voiceChat.ts';
import {voiceChannel,voiceRecipient,voiceSignal,type VoiceChannel} from '../../../ride-core/src/voiceProtocol.ts';
import {RoomChatPanel,cleanChatText,ChatRateGate} from '@digital-static/ridecore/chat';
import {ONLINE_CONFIG} from './onlineConfig.ts';
import {NEUTRAL_ACTIONS,type RideActions} from '@digital-static/ridecore';
import {ELMWOOD_CAMERAS} from './elmwood-camera.ts';
import {RIDER_CHOICES} from './riderChoices.ts';
const CHALLENGES=[{id:'tricks',title:'Two-minute trick session'},{id:'tour',title:'Creek lane discovery'}];
import {roomActions,roomCode,roomFrame,roomMatch,roomMember,roomRoster,fillRaceRoster,ROOM_PROTOCOL,type RoomMatch,type RoomMember,type RoomFrame} from './onlineProtocol.ts';

import type {Binding as SplitBinding} from './elmwood-session-input.ts';
import './onlineRooms.css';
import {inviteSharing} from './inviteSharing.ts';
type Channel={on:(type:string,filter:object,fn:(v:any)=>void)=>Channel;subscribe:(fn:(status:string)=>void)=>Channel;track:(v:object)=>Promise<unknown>;presenceState:()=>Record<string,unknown[]>;send:(v:object)=>Promise<unknown>};
type Client={channel:(name:string,config:object)=>Channel;removeChannel:(channel:Channel)=>Promise<unknown>;disconnect:()=>void};
/** Ephemeral invited games use only Realtime presence/broadcast, never store tables or rewards. */
export class ElmwoodOnlineRooms{
 readonly panel=document.createElement('section');readonly hud=document.createElement('section');readonly self=crypto.randomUUID();
 private client?:Client;private channel?:Channel;private owner='';private members:RoomMember[]=[];private connected=false;private generation=0;private joined=0;private code='';private lastFrame=-1;private next=0;private seq=0;private lastReceived=0;private inputSeq=0;
 private pending=new Map<string,{seq:number;at:number;actions:RideActions;camera:boolean;photo:boolean}>();private frozen=false;private launchButton=document.createElement('button');private status=document.createElement('p');private invite=document.createElement('input');private codeInput=document.createElement('input');private mode=document.createElement('select');private roster=document.createElement('ol');private hudStatus=document.createElement('p');
 match?:RoomMatch;frame?:RoomFrame;private lastReady=false;private lastInput:RideActions={...NEUTRAL_ACTIONS};
 private voice=new VoiceChat();private voiceMembers=new Map<string,VoiceChannel>();
 private updateVoice(){const members=this.members.filter(m=>this.voiceMembers.has(m.id)).map((m,i)=>({id:m.id,name:'Player '+(i+1),channel:this.voiceMembers.get(m.id)!}));this.voice.setMembers(members);}
 private receiveVoice(envelope:any){if(envelope?.protocol!==ROOM_PROTOCOL||envelope.data?.room!==this.code||!this.members.some(m=>m.id===envelope.sender))return;const data=envelope.data;if(data.state){const fresh=!this.voiceMembers.has(envelope.sender);if(fresh&&data.state.enabled&&this.voiceMembers.has(this.self))void this.send('voice',{room:this.code,state:{enabled:true,channel:this.voiceMembers.get(this.self)}});if(data.state.enabled&&voiceChannel(data.state.channel))this.voiceMembers.set(envelope.sender,data.state.channel);else this.voiceMembers.delete(envelope.sender);this.updateVoice();}else{const signal=voiceSignal(data.signal);if(signal&&voiceRecipient(envelope.sender,signal,[...this.voiceMembers].map(([id,channel])=>({id,name:id,channel}))))this.voice.receive(envelope.sender,signal);}}
 private chat:RoomChatPanel;private chatRate=new ChatRateGate();private fill=document.createElement('input');private botDifficulty=document.createElement('select');
 private sharing:ReturnType<typeof inviteSharing>;private share=document.createElement('div');private roomCodeField=document.createElement('input');private copyCode=document.createElement('button');private copyLink=document.createElement('button');
 private map='elmwood' as const;private ready:()=>boolean;private onLaunch:(match:RoomMatch,slot:number)=>void;private stop:()=>void;private rider=document.createElement('select');private startSelect=document.createElement('select');
 constructor(ready:()=>boolean,onLaunch:(match:RoomMatch,slot:number)=>void,stop:()=>void){
  this.voice.root.addEventListener('toggle',()=>{if(this.voice.root.open)document.querySelector('canvas')?.dispatchEvent(new Event('online-release-input'));});
 this.ready=ready;this.onLaunch=onLaunch;this.stop=stop;
  this.chat=new RoomChatPanel(text=>{if(!this.connected)return;const message={id:crypto.randomUUID(),player:this.self,name:'Player '+(this.members.findIndex(m=>m.id===this.self)+1),text,at:Date.now()};this.chat.receive(message);void this.send('chat',{room:this.code,message});},()=>document.querySelector('canvas')?.dispatchEvent(new Event('online-release-input')),()=>this.connected);
  this.panel.id='onlineRooms';this.panel.className='lobbyPanel';this.panel.hidden=true;this.panel.setAttribute('aria-label','Online multiplayer rooms');
  const title=document.createElement('h2');title.textContent='Online multiplayer';const copy=document.createElement('p');copy.textContent='Play together from separate devices. Host a room, share its code or link, and invite up to three friends. Choose Free ride, a Creek Lane race, a trick session, or a discovery ride. Each player controls their own rider. Settings lets you choose your view and display quality on this device.';
  const modeLabel=document.createElement('label');modeLabel.textContent='ROOM MODE';this.mode.setAttribute('aria-label','Online room mode');for(const [value,label]of [['free','Free ride'],['race','Creek Lane race'],...CHALLENGES.map(c=>[c.id,c.title])])this.mode.add(new Option(label,value));modeLabel.append(this.mode);const fillLabel=document.createElement('label');this.fill.type='checkbox';this.fill.checked=false;fillLabel.append(this.fill,document.createTextNode('Fill a four-rider race with AI rivals'));this.botDifficulty.setAttribute('aria-label','AI race difficulty');this.botDifficulty.add(new Option('Expert · fastest rivals','expert'));this.botDifficulty.add(new Option('Club · competitive','club'));fillLabel.append(this.botDifficulty);modeLabel.append(fillLabel);this.fill.onchange=()=>this.refresh();
  const inputLabel=document.createElement('label');inputLabel.textContent='YOUR CONTROLS';const input=document.createElement('select');input.id='onlineInput';input.setAttribute('aria-label','Your online controls');for(const[value,label]of [['wasd','Keyboard · WASD'],['arrows','Keyboard · Arrow keys'],['ijkl','Keyboard · IJKL'],['numpad','Keyboard · Number pad'],['touch','Touch controls'],...Array.from({length:4},(_,i)=>['pad:'+i,'Controller '+(i+1)])])input.add(new Option(label,value));inputLabel.append(input);
  const spawnLabel=document.createElement('label');spawnLabel.textContent='FREE RIDE START';const start=document.createElement('select');start.setAttribute('aria-label','Online free ride starting location');this.startSelect=start;for(const [i,label]of ['Main entrance','Creek Lane south','Pond lane','Chapel lane'].entries())start.add(new Option(label,String(i)));spawnLabel.append(start);this.mode.onchange=()=>{spawnLabel.hidden=this.mode.value!=='free';fillLabel.hidden=this.mode.value!=='race';this.refresh();};fillLabel.hidden=true;
  const create=document.createElement('button');create.textContent='Host room';create.onclick=()=>{const b=crypto.getRandomValues(new Uint8Array(16));void this.connect(Array.from(b,x=>x.toString(16).padStart(2,'0')).join(''),true);};
  const codeLabel=document.createElement('label');codeLabel.textContent='JOIN WITH A ROOM CODE OR LINK';this.codeInput.setAttribute('aria-label','Online invitation code or link');this.codeInput.placeholder='Paste a room code or invitation link';codeLabel.append(this.codeInput);const join=document.createElement('button');join.textContent='Join room';join.onclick=()=>{let code=this.codeInput.value;try{code=new URL(code).hash.replace('#room=','');}catch{}const parsed=roomCode(code);if(!parsed){this.status.textContent='Paste the complete room code or invitation link.';return;}void this.connect(parsed,false);};
  this.invite.readOnly=true;this.invite.setAttribute('aria-label','Online room invitation');this.invite.hidden=true;
  this.launchButton.textContent='Start online match';this.launchButton.hidden=true;this.launchButton.onclick=()=>this.start();const leave=document.createElement('button');leave.textContent='Leave room';leave.onclick=()=>void this.leave();const controls=document.createElement('div');controls.className='onlineActions';controls.append(create,join,this.launchButton,leave);
  this.share.className='onlineShare';this.share.hidden=true;const roomLabel=document.createElement('label');roomLabel.textContent='YOUR ROOM CODE';this.roomCodeField.readOnly=true;this.roomCodeField.setAttribute('aria-label','Online room code');roomLabel.append(this.roomCodeField);
  const inviteLabel=document.createElement('label');inviteLabel.textContent='INVITATION LINK';inviteLabel.append(this.invite);this.copyCode.textContent='Copy room code';this.copyLink.textContent='Copy invitation link';this.copyCode.onclick=()=>void this.copyInvitation(this.code,this.roomCodeField);this.copyLink.onclick=()=>void this.copyInvitation(this.invite.value,this.invite);
  const shareActions=document.createElement('div');shareActions.className='onlineActions';shareActions.append(this.copyCode,this.copyLink);const hint=document.createElement('p');hint.textContent='Keep this room open. Start once two or more riders are ready.';this.sharing=inviteSharing(()=>this.connected?{code:this.code,link:this.invite.value,title:this.map==='elmwood'?'Elmwood Explorer':'Swoop . Detroit'}:undefined,text=>{this.status.textContent=text;});this.share.append(roomLabel,inviteLabel,shareActions,this.sharing.element,hint);
  const preview=document.createElement('p');preview.className='onlinePreview';preview.hidden=!['localhost','127.0.0.1','[::1]'].includes(location.hostname);preview.textContent='Local preview: this invitation address opens on this computer. Friends on other computers need the same published game build, then can join with your room code.';
  this.status.setAttribute('role','status');this.roster.setAttribute('aria-label','Connected online players');this.panel.append(title,copy,modeLabel,spawnLabel,inputLabel,codeLabel,controls,this.share,preview,this.status,this.roster);document.querySelector('#elmwood-main-menu .menu-inner')!.append(this.panel);
  const menu=document.querySelector<HTMLDialogElement>('#elmwood-main-menu')!;
  const placeVoice=()=>{const parent=menu.open?this.panel:document.body;if(this.voice.root.parentElement!==parent)parent.append(this.voice.root);};
  new MutationObserver(placeVoice).observe(menu,{attributes:true,attributeFilter:['open']});placeVoice();
  const tab=document.createElement('button');tab.textContent='Online multiplayer';tab.setAttribute('aria-label','Online multiplayer');document.querySelector('#elmwood-main-menu .menu-actions')!.append(tab);
  const onlineBack=document.createElement('button');onlineBack.textContent='Back to ride menu';this.panel.prepend(onlineBack);
  const show=()=>{for(const node of [...menu.querySelector('.menu-inner')!.children])if(node!==this.panel)(node as HTMLElement).hidden=true;this.panel.hidden=false;if(!menu.open)menu.showModal();this.panel.querySelector('button')?.focus();};
  onlineBack.onclick=()=>{for(const node of [...menu.querySelector('.menu-inner')!.children])(node as HTMLElement).hidden=false;this.panel.hidden=true;document.querySelector<HTMLButtonElement>('#menu-resume')!.hidden=document.querySelector('canvas')?.getAttribute('data-riding')!=='true';tab.focus();};
  tab.onclick=()=>{menu.dispatchEvent(new Event('elmwood-prepare-online'));show();};
  menu.addEventListener('elmwood-show-online',show);
  const riderLabel=document.createElement('label');riderLabel.textContent='YOUR RIDER';this.rider.setAttribute('aria-label','Your online rider');for(const r of RIDER_CHOICES)this.rider.add(new Option(r.label,r.id));this.rider.value='DS_Armored_Rider_01';inputLabel.after(riderLabel);riderLabel.append(this.rider);this.rider.onchange=()=>{if(this.connected&&!this.match)void this.channel?.track({id:this.self,rider:this.rider.value,joined:this.joined,host:this.isHost,map:this.map,protocol:ROOM_PROTOCOL,ready:this.ready()});};
  const viewLabel=document.createElement('label');viewLabel.textContent='YOUR VIEW';const view=document.createElement('select');view.id='elmwood-online-view';view.setAttribute('aria-label','Online camera view');for(const [id,label]of [...ELMWOOD_CAMERAS,['split','Watch all riders · split screen']])view.add(new Option(label,id));viewLabel.append(view);this.panel.append(viewLabel);
  this.hud.id='onlineHUD';this.hud.hidden=true;const quit=document.createElement('button');quit.textContent='Leave online match';quit.onclick=()=>void this.leave();this.hud.append(this.hudStatus,quit);document.body.append(this.hud);
  const code=roomCode(location.hash.replace('#room=',''));if(code){this.codeInput.value=code;tab.click();this.status.textContent='Invitation ready. Select Join room.';}
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&this.match){void this.send('input',{id:this.self,match:this.match.id,seq:++this.inputSeq,actions:{...NEUTRAL_ACTIONS},camera:false,photo:false});if(this.isHost)this.frozen=true;}});
  window.addEventListener('pagehide',()=>{this.voice.disconnect();this.client?.disconnect();});
  window.setInterval(()=>{if(this.connected&&this.lastReady!==this.ready()){this.lastReady=this.ready();void this.channel?.track({id:this.self,rider:this.rider.value,joined:this.joined,host:this.isHost,map:this.map,protocol:ROOM_PROTOCOL,ready:this.lastReady});}},1000);
 }
 get active(){return !!this.match;}
 get inputBlocked(){return this.chat.root.open||this.voice.root.open;}
 get binding(){return (document.getElementById('onlineInput') as HTMLSelectElement).value as SplitBinding;}
 get isHost(){return this.owner===this.self;}
 get slot(){return this.match?.members.findIndex(m=>m.id===this.self)??-1;}
 get healthy(){return this.connected&&!this.frozen&&(!this.match||this.isHost||performance.now()-this.lastReceived<1800);}
 private async copyInvitation(value:string,field:HTMLInputElement){if(!this.connected||!value)return;try{await navigator.clipboard.writeText(value);this.status.textContent='Invitation copied. Share it with your riders.';}catch{field.focus();field.select();this.status.textContent='Select and copy the invitation above.';}}
 private async send(event:string,payload:unknown){if(this.connected)await this.channel?.send({type:'broadcast',event,payload:{protocol:ROOM_PROTOCOL,sender:this.self,data:payload}});}
 private async connect(code:string,host:boolean){
  await this.leave(false);const generation=++this.generation;this.code=code;this.owner=host?this.self:'';this.joined=Date.now();this.status.textContent='Connecting to LottoMind live rooms…';
  try{const module=await import(/* @vite-ignore */ new URL(ONLINE_CONFIG.sdk,document.baseURI).href);if(generation!==this.generation)return;this.client=new module.RealtimeClient(ONLINE_CONFIG.url+'/realtime/v1',{params:{apikey:ONLINE_CONFIG.key},heartbeatIntervalMs:10000});
   const channel=this.channel=this.client!.channel('swoop:rooms:'+code,{config:{broadcast:{ack:false,self:false},presence:{key:this.self},private:false}});
   const current=()=>generation===this.generation&&this.channel===channel;
   channel.on('presence',{event:'sync'},()=>{if(current())this.presence();});channel.on('broadcast',{event:'control'},v=>{if(current())this.receiveControl(v.payload);});channel.on('broadcast',{event:'frame'},v=>{if(current())this.receiveFrame(v.payload);});channel.on('broadcast',{event:'input'},v=>{if(current())this.receiveInput(v.payload);});channel.on('broadcast',{event:'chat'},v=>{if(current())this.receiveChat(v.payload);});channel.on('broadcast',{event:'voice'},v=>{if(current())this.receiveVoice(v.payload);});
   channel.subscribe(status=>{if(generation!==this.generation)return;this.connected=status==='SUBSCRIBED';if(this.connected){this.voice.bind(this.self,{state:(enabled,channel)=>{if(enabled)this.voiceMembers.set(this.self,channel);else this.voiceMembers.delete(this.self);void this.send('voice',{room:this.code,state:{enabled,channel}});this.updateVoice();},signal:signal=>void this.send('voice',{room:this.code,signal})});this.status.textContent=host?'Room connected. Share your invitation, then start when another rider joins.':'Connected. Waiting for the host.';this.lastReady=this.ready();void channel.track({id:this.self,rider:this.rider.value,joined:this.joined,host,map:this.map,protocol:ROOM_PROTOCOL,ready:this.lastReady});this.invite.hidden=false;this.share.hidden=false;this.roomCodeField.value=code;const url=new URL(location.href);url.hash='room='+code;this.invite.value=url.href;history.replaceState(null,'',url);}else {this.voice.disconnect();this.status.textContent='Room connection interrupted. Reconnecting…';this.hudStatus.textContent='Connection interrupted · local controls held';}this.refresh();});
  }catch{this.status.textContent='Live rooms could not connect. Retry Host / Join; local split screen remains available.';}
 }
 private presence(){
  const raw=Object.values(this.channel?.presenceState()??{}).flat().filter((v:any)=>v.protocol===ROOM_PROTOCOL&&v.map===this.map);const peers=raw.map(roomMember).filter((v):v is RoomMember=>!!v);const hosts=peers.filter(p=>p.host).sort((a,b)=>a.joined-b.joined||a.id.localeCompare(b.id));
  if(!this.owner&&hosts.length)this.owner=hosts[0].id;
  if(this.owner&&!peers.some(m=>m.id===this.owner)&&(!this.isHost||!!this.match)){if(this.match){this.status.textContent='Host disconnected. This match has ended.';this.match=undefined;this.frame=undefined;this.stop();}this.owner='';}
  if(this.isHost){const absent=this.match?.members.some(m=>!m.bot&&!peers.some(p=>p.id===m.id));this.members=roomRoster(peers,this.owner);if(absent){this.match=undefined;this.frame=undefined;this.hud.hidden=true;this.status.textContent='A player disconnected. Match ended; reconnect and start another room.';this.stop();}void this.send('control',{owner:this.owner,members:this.members,match:this.match??null,ended:absent?'A player disconnected. Match ended.':undefined});}
  else if(this.match){const ids=new Set(peers.map(p=>p.id));this.hudStatus.textContent=this.match.members.filter(p=>ids.has(p.id)).length+' / '+this.match.members.length+' players connected';}
  else if(!this.owner){this.members=roomRoster(peers,'');this.status.textContent='No host is in this room yet. Ask the host to open it, or choose Host room to create a new room.';}
  this.refresh();
 }
 private receiveControl(envelope:any){if(envelope?.protocol!==ROOM_PROTOCOL||envelope.sender!==this.owner||!envelope.data||envelope.data.owner!==this.owner||!Array.isArray(envelope.data.members))return;const roster=envelope.data.members.map(roomMember);if(roster.some((m:unknown)=>!m)||roster.length<1||roster.length>4||new Set(roster.map((m:RoomMember)=>m.id)).size!==roster.length)return;this.members=roster;
  if(!roster.some((m:RoomMember)=>m.id===this.self)){this.status.textContent='This room is full (four players). Create another room.';return;}
  if(envelope.data.match===null&&this.match){this.match=undefined;this.frame=undefined;this.hud.hidden=true;this.status.textContent='The match ended. Reconnect the players and start again.';this.stop();}
  const m=roomMatch(envelope.data.match,roster,this.owner,this.map,['free','race',...CHALLENGES.map(c=>c.id)]);if(m&&m.id!==this.match?.id){this.match=m;this.lastFrame=-1;this.lastReceived=performance.now();this.frozen=false;this.launch(m);}
  this.refresh();
 }
 private receiveChat(envelope:any){if(envelope?.protocol!==ROOM_PROTOCOL||envelope.data?.room!==this.code||envelope.data.message?.player!==envelope.sender||!this.members.some(m=>m.id===envelope.sender)||!cleanChatText(envelope.data.message?.text)||!this.chatRate.allow(envelope.sender,performance.now()))return;this.chat.receive({...envelope.data.message,name:'Player '+(this.members.findIndex(m=>m.id===envelope.sender)+1)});}
 private launch(m:RoomMatch){const slot=m.members.findIndex(p=>p.id===this.self);if(slot<0)return;this.hud.hidden=false;this.chat.show(true);this.launchButton.disabled=true;this.status.textContent='Live match started.';this.onLaunch(m,slot);}
 private start(){if(!this.isHost||!this.connected||!this.ready()||this.members.length<(this.mode.value==='race'&&this.fill.checked?1:2)||this.members.some(m=>m.ready===false))return;const m=this.match={id:crypto.randomUUID(),owner:this.self,members:this.mode.value==='race'&&this.fill.checked?fillRaceRoster(this.members,this.self):this.members.map(p=>({...p})),botFill:this.mode.value==='race'&&this.fill.checked,difficulty:this.botDifficulty.value as 'club'|'expert',mode:this.mode.value,spawn:Number(this.startSelect.value),seed:crypto.getRandomValues(new Uint32Array(1))[0],startAt:Date.now()+3000,map:this.map,wheel:(document.querySelector<HTMLSelectElement>('#session-vehicle')?.value??'euc')};this.seq=0;this.pending.clear();this.frozen=false;this.launch(m);void this.send('control',{owner:this.owner,members:this.members,match:m});}
 private receiveFrame(envelope:any){if(this.isHost||envelope?.protocol!==ROOM_PROTOCOL||envelope.sender!==this.owner||!this.match)return;const frame=roomFrame(envelope.data,this.match.members.length,this.match.id,this.lastFrame);if(!frame)return;this.lastFrame=frame.seq;this.frame=frame;this.lastReceived=performance.now();this.hudStatus.textContent='LIVE / '+this.match.members.length+' PLAYERS / '+this.match.mode.toUpperCase();}
 private receiveInput(envelope:any){if(!this.isHost||envelope?.protocol!==ROOM_PROTOCOL||!this.match)return;const v=envelope.data;if(v?.id!==envelope.sender||v.match!==this.match.id||!this.match.members.some(m=>m.id===v.id&&!m.bot)||!Number.isInteger(v.seq)||v.seq<0||v.seq<=(this.pending.get(v.id)?.seq??-1))return;const actions=roomActions(v.actions);if(!actions)return;const previous=this.pending.get(v.id);this.pending.set(v.id,{seq:v.seq,at:performance.now(),actions:{...actions,hop:actions.hop||!!previous?.actions.hop,reset:actions.reset||!!previous?.actions.reset,trick:actions.trick||previous?.actions.trick||0},camera:!!v.camera||!!previous?.camera,photo:!!v.photo||!!previous?.photo});}
 inputs(local:RideActions){if(!this.match)return [];return this.match.members.map(m=>{if(m.bot)return {...NEUTRAL_ACTIONS};if(m.id===this.self)return this.healthy?local:{...NEUTRAL_ACTIONS};const input=this.pending.get(m.id);if(!input||performance.now()-input.at>600)return {...NEUTRAL_ACTIONS};const actions={...input.actions};input.actions.hop=input.actions.reset=false;input.actions.trick=0;return actions;});}
 events(slot:number){const v=this.pending.get(this.match!.members[slot].id);if(!v)return {camera:false,photo:false};const out={camera:v.camera,photo:v.photo};v.camera=v.photo=false;return out;}
 command(actions:RideActions,camera=false,photo=false){if(this.isHost)return;this.lastInput={...actions};void this.send('input',{id:this.self,match:this.match?.id,seq:++this.inputSeq,actions,camera,photo});}
 update(dt:number,snapshot:Omit<RoomFrame,'match'|'seq'>,local:RideActions){if(!this.match)return;this.next-=dt;if(this.next>0)return;this.next=.1;
  this.hud.hidden=!!document.querySelector<HTMLDialogElement>('#elmwood-main-menu')?.open;this.chat.show(!this.hud.hidden);this.hudStatus.textContent=this.isHost?'LIVE / HOST / '+this.match.members.filter(m=>!m.bot).length+' HUMANS / '+this.match.members.filter(m=>m.bot).length+' AI':this.healthy?'LIVE / PLAYER '+(this.slot+1)+' / '+this.match.members.length+' RIDERS':'Connection stalled · waiting for host';
  if(this.isHost){this.frozen=false;void this.send('frame',{...snapshot,match:this.match.id,seq:++this.seq});}else this.command(local);
 }
 private refresh(){this.updateVoice();this.rider.disabled=!!this.match;this.sharing.update(this.connected);this.copyCode.disabled=this.copyLink.disabled=!this.connected;this.launchButton.hidden=!this.isHost;this.launchButton.disabled=!this.connected||this.members.length<(this.mode.value==='race'&&this.fill.checked?1:2)||this.members.some(m=>m.ready===false)||!!this.match;this.roster.replaceChildren(...this.members.map((m,i)=>{const item=document.createElement('li');item.textContent='Player '+(i+1)+' · '+m.rider.replace('DS_','').replaceAll('_',' ')+(m.id===this.self?' · You':'')+(m.id===this.owner?' · Host':'')+(m.ready===false?' · Loading Elmwood…':' · Ready');return item;}));}
 async leave(stop=true){this.voice.disconnect();this.voiceMembers.clear();this.generation++;this.connected=false;this.match=undefined;this.frame=undefined;this.members=[];this.pending.clear();this.hud.hidden=true;this.invite.hidden=true;this.share.hidden=true;this.chat.show(false);this.chat.clear();this.chatRate.clear();this.status.textContent='You have left the room.';this.owner='';if(stop&&location.hash==='#room='+this.code){const url=new URL(location.href);url.hash='';history.replaceState(null,'',url);}this.refresh();if(stop)this.stop();if(this.channel&&this.client)await this.client.removeChannel(this.channel);this.client?.disconnect();this.channel=undefined;this.client=undefined;}
 get state(){return {bots:this.match?.members.filter(m=>m.bot).length??0,difficulty:this.match?.difficulty,connected:this.connected,room:this.code,host:this.isHost,slot:this.slot,players:this.members.length,match:this.match?.id,mode:this.match?.mode,sequence:this.lastFrame,healthy:this.healthy,sentInput:this.lastInput,remoteInputs:this.match?.members.map(m=>{const v=this.pending.get(m.id);return v?{seq:v.seq,age:performance.now()-v.at,throttle:v.actions.throttle}:null;})};}
}
