import {createPose,type RideActions,type RidePose} from '@digital-static/ridecore';
import {RIDER_CHOICES,type RiderId} from './riderChoices.ts';
export const ROOM_PROTOCOL='elmwood-rooms-v1';
export type RoomMember={id:string;rider:RiderId;joined:number;host:boolean;ready?:boolean;bot?:boolean};
export type RoomMatch={id:string;owner:string;members:RoomMember[];mode:string;spawn:number;seed:number;startAt:number;map:'cut'|'elmwood';botFill?:boolean;difficulty?:'club'|'expert';wheel?:string};
export type RoomFrame={match:string;seq:number;countdown:number;elapsed:number;done:boolean;riders:{pose:RidePose;gate:number;station:number;finish:number|null;missed:boolean;banked:number;message:string;crashed:boolean;fallPhase?:string;challenge?:{count:number;gateCount:number;elapsed:number;done:boolean;failed:boolean;reason:string;photos:string[]}}[]};
export function roomCode(value:string){const v=value.trim().toLowerCase();return /^[a-f0-9]{32}$/.test(v)?v:undefined;}
export function roomMember(value:unknown):RoomMember|undefined{if(!value||typeof value!=='object')return;const v=value as RoomMember;if(v.bot===true||!/^[a-f0-9-]{36}$/.test(v.id)||!RIDER_CHOICES.some(r=>r.id===v.rider)||!Number.isFinite(v.joined)||v.joined<0||typeof v.host!=='boolean')return;return {id:v.id,rider:v.rider,joined:v.joined,host:v.host,ready:v.ready!==false};}
export function roomRoster(members:RoomMember[],owner:string){return members.filter((v,i,a)=>a.findIndex(m=>m.id===v.id)===i).sort((a,b)=>Number(b.id===owner)-Number(a.id===owner)||a.joined-b.joined||a.id.localeCompare(b.id)).slice(0,4).map(m=>({...m}));}
export function fillRaceRoster(humans:RoomMember[],owner:string){const out=humans.map(m=>({...m,bot:false}));while(out.length<4){const i=out.length;out.push({id:'ai-'+owner+'-'+i,rider:RIDER_CHOICES[i].id,joined:0,host:false,ready:true,bot:true});}return out;}
export function roomActions(value:unknown):RideActions|undefined{if(!value||typeof value!=='object')return;const v=value as RideActions;if(!Number.isFinite(v.throttle)||!Number.isFinite(v.steer)||Math.abs(v.throttle)>1||Math.abs(v.steer)>1||!Number.isInteger(v.trick)||v.trick<0||v.trick>6)return;for(const k of ['hop','hopHeld','crouch','reset'] as const)if(typeof v[k]!=='boolean')return;return {throttle:v.throttle,steer:v.steer,trick:v.trick,hop:v.hop,hopHeld:v.hopHeld,crouch:v.crouch,reset:v.reset};}
export function roomMatch(value:unknown,roster:RoomMember[],owner:string,map:string,modes:readonly string[]):RoomMatch|undefined{
 if(!value||typeof value!=='object')return;const m=value as RoomMatch;
 if(m.wheel!==undefined&&!['euc','euc:city','euc:tour','euc:trail','euc:speed'].includes(m.wheel))return;
 if(m.botFill!==undefined&&typeof m.botFill!=='boolean'||m.difficulty!==undefined&&!['club','expert'].includes(m.difficulty))return;
 const expected=m.mode==='race'&&m.botFill?fillRaceRoster(roster,owner):roster;
 if(!/^[a-f0-9-]{36}$/.test(m.id)||m.owner!==owner||m.map!==map||!Array.isArray(m.members)||m.members.length<2||m.members.length>4||m.members.length!==expected.length||!modes.includes(m.mode)||!Number.isInteger(m.spawn)||m.spawn<0||m.spawn>100||!Number.isInteger(m.seed)||m.seed<0||m.seed>0xffffffff||!Number.isFinite(m.startAt)||m.members.some((p,i)=>!p||p.id!==expected[i]?.id||p.rider!==expected[i]?.rider||!!p.bot!==!!expected[i]?.bot||(!p.bot&&!roomMember(p))))return;
 return {...m,members:expected};
}
export function roomFrame(value:unknown,count:number,match:string,lastSequence:number):RoomFrame|undefined{if(!value||typeof value!=='object')return;const v=value as RoomFrame;if(v.match!==match||!Number.isInteger(v.seq)||v.seq<=lastSequence||!Number.isFinite(v.elapsed)||v.elapsed<0||!Number.isFinite(v.countdown)||v.countdown<0||v.countdown>5||typeof v.done!=='boolean'||!Array.isArray(v.riders)||v.riders.length!==count)return;
 for(const r of v.riders){if(!r?.pose||!Number.isInteger(r.gate)||r.gate<0||r.gate>100||!Number.isFinite(r.station)||r.finish!==null&&(!Number.isFinite(r.finish)||r.finish<0)||!Number.isFinite(r.banked)||r.banked<0||typeof r.message!=='string'||r.message.length>240||typeof r.crashed!=='boolean'||typeof r.missed!=='boolean'||r.fallPhase!==undefined&&!['none','brace','separate','impact','slide','settled'].includes(r.fallPhase))return;for(const key of Object.keys(createPose()) as (keyof RidePose)[]){if(!Number.isFinite(r.pose[key])||Math.abs(r.pose[key])>1e6)return;}if(Math.abs(r.pose.speed)>35||r.pose.y< -500||r.pose.y>2000)return;
 if(r.challenge){const c=r.challenge;if(!Number.isFinite(c.count)||!Number.isFinite(c.gateCount)||!Number.isFinite(c.elapsed)||typeof c.done!=='boolean'||typeof c.failed!=='boolean'||typeof c.reason!=='string'||c.reason.length>200||!Array.isArray(c.photos)||c.photos.length>50||c.photos.some(p=>typeof p!=='string'||p.length>100))return;}}
 return v;}
