import type { CaseFile,User } from './types';
import { evidenceStatuses } from './types';
const $=<T extends HTMLElement=HTMLElement>(s:string,root:ParentNode=document)=>root.querySelector<T>(s);
const $$=<T extends HTMLElement=HTMLElement>(s:string,root:ParentNode=document)=>Array.from(root.querySelectorAll<T>(s));
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const https=(s:unknown)=>{try{const u=new URL(String(s));return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}};
const date=(s:string)=>new Date(s).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
export async function initCFiles(){
 const config=JSON.parse($('#cf-config')!.textContent!);const root:string=config.root;
 let cases:CaseFile[]=config.seed,user:User|null=null,connected=false;
 async function request(route:string,data?:unknown):Promise<any>{
  const response=await fetch(config.api+route,{method:data===undefined?'GET':'POST',credentials:'same-origin',headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data),signal:AbortSignal.timeout(15000)});
  const result=await response.json().catch(()=>({error:'Contribution service is unavailable.'}));if(!response.ok)throw Error(result.error||'The request could not be completed.');return result;
 }
 try{const health=await request('health');connected=health.connected===true;$('[data-service]')!.textContent=health.note;user=(await request('me')).user;const result=await request('cases');cases=result.cases;}
 catch{connected=false;$('[data-service]')!.textContent='Source archive · contributions are not connected on this host. You can still browse the published research.';}
 if(user)$('[data-account-link]')!.textContent='Your account';
 const link=(id:string)=>config.seed.some((c:CaseFile)=>c.id===id)?root+'cases/'+encodeURIComponent(id)+'/':root+'case/?id='+encodeURIComponent(id);
 const form=$<HTMLFormElement>('.cf-filters');let shown=cases;let renderMarkers:((c:CaseFile[])=>void)|undefined;
 function renderIndex(){
  const f=form?Object.fromEntries(new FormData(form)):{};const q=String(f.q||'').trim().toLowerCase().split(/\s+/).filter(Boolean);
  shown=cases.filter(c=>q.every(word=>[c.title,c.location,c.narrative,c.source_name].join(' ').toLowerCase().includes(word))&&(!f.year||String(c.year)===f.year)&&(!f.type||c.event_type===f.type)&&(!f.status||c.credibility===f.status)&&(!f.witness||c.witness_type===f.witness));
  const rows=$('[data-case-rows]');if(rows)rows.innerHTML=shown.map(c=>`<tr><td><a href="${esc(link(c.id))}">${esc(c.title)}</a></td><td>${esc(c.location)}</td><td>${esc(c.year)}</td><td class="cf-gold">${esc(c.credibility)}</td><td aria-hidden="true">↗</td></tr>`).join('');
  const empty=$('[data-case-empty]');if(empty)empty.hidden=shown.length>0;const count=$('[data-case-count]');if(count){count.setAttribute('role','status');count.textContent=`${shown.length} of ${cases.length} published records`;}
  renderMarkers?.(shown);
 }
 if(form){const year=$<HTMLSelectElement>('[name=year]',form)!;year.innerHTML='<option value="">All years</option>'+[...new Set(cases.map(c=>c.year))].sort((a,b)=>b-a).map(y=>`<option value="${y}">${y}</option>`).join('');const query=new URLSearchParams(location.search);for(const field of $$<HTMLInputElement|HTMLSelectElement>('input,select',form))if(query.has(field.name))field.value=query.get(field.name)!;
  form.addEventListener('submit',e=>e.preventDefault());form.addEventListener('input',()=>{const url=new URL(location.href);new FormData(form).forEach((v,k)=>v?url.searchParams.set(k,String(v)):url.searchParams.delete(k));history.replaceState(null,'',url);renderIndex();});form.addEventListener('reset',()=>{setTimeout(()=>{history.replaceState(null,'',location.pathname);renderIndex();},0);});
 }
 renderIndex();
 const mapElement=$('[data-case-map]');if(mapElement){
  try{const L=await import('leaflet');const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
   const map=L.map(mapElement,{scrollWheelZoom:false,minZoom:1,maxZoom:7,zoomAnimation:!reduced,fadeAnimation:!reduced,markerZoomAnimation:!reduced}).setView([29,-30],2);
   const geography=await fetch(root+'../media/cfiles-world.json').then(r=>{if(!r.ok)throw Error('Map unavailable');return r.json();});
   L.geoJSON(geography,{interactive:false,style:{color:'#3d4b53',fillColor:'#202e38',weight:.7,fillOpacity:1}}).addTo(map);
   map.attributionControl.addAttribution('<a href="https://www.naturalearthdata.com/">Natural Earth</a> · regional reference');
   const layer=L.layerGroup().addTo(map);
   renderMarkers=list=>{layer.clearLayers();for(const c of list){if(c.lat==null||c.lon==null)continue;const popup=document.createElement('div');const a=document.createElement('a');a.href=link(c.id);a.textContent=c.title;popup.append(a,document.createElement('br'),document.createTextNode(c.location_note||'Approximate region.'));
    L.marker([c.lat,c.lon],{icon:L.divIcon({className:'cf-pin',iconSize:[16,16]}),title:c.title,alt:c.title,keyboard:true}).addTo(layer).bindPopup(popup);
   }const points=list.filter(c=>c.lat!=null&&c.lon!=null).map(c=>L.latLng(c.lat!,c.lon!));if(points.length)map.fitBounds(L.latLngBounds(points),{padding:[40,40],maxZoom:points.length===1?4:2,animate:false});};renderMarkers(shown);
  }catch{mapElement.textContent='The map could not load. All case files remain available in the index below.';}
 }
 const ticker=$('[data-ticker]'),toggle=$<HTMLButtonElement>('[data-ticker-toggle]');if(ticker&&toggle){const items=JSON.parse($('#cf-news')?.textContent||'[]');let index=0,paused=matchMedia('(prefers-reduced-motion:reduce)').matches;const sync=()=>{toggle.textContent=paused?'▶':'Ⅱ';toggle.setAttribute('aria-label',paused?'Play news ticker':'Pause news ticker');toggle.setAttribute('aria-pressed',String(paused));};sync();toggle.addEventListener('click',()=>{paused=!paused;sync();});const timer=setInterval(()=>{if(paused||document.hidden||!items.length)return;const n=items[++index%items.length];const a=$<HTMLAnchorElement>('a',ticker)!;a.textContent=n.title;a.href=https(n.url);$('time',ticker)!.textContent=n.published_at?date(n.published_at):'Date unavailable';},8000);window.addEventListener('pagehide',()=>clearInterval(timer),{once:true});}
 function requireUser(status:HTMLElement){if(!connected){status.textContent='Contributions are unavailable on this host. Your information has not been sent.';return false;}if(!user){status.innerHTML=`<a class="cf-text-link" href="${esc(root+'account/')}">Sign in before submitting a report or evidence.</a>`;return false;}return true;}
 async function photo(form:HTMLFormElement){const f=$<HTMLInputElement>('[name=photo]',form)?.files?.[0];if(!f||f.size===0)return undefined;if(f.size>4194304)throw Error('Choose a photo smaller than 4 MB.');if(!['image/jpeg','image/png','image/webp'].includes(f.type))throw Error('Choose a JPEG, PNG or WebP photo.');return await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('The image could not be read.'));reader.readAsDataURL(f);});}
 async function evidenceList(id:string){const container=$('[data-evidence-list]');if(!container)return;try{const result=await request('evidence?case='+encodeURIComponent(id));container.innerHTML=result.evidence.length?result.evidence.map((e:any)=>`<article><span class="cf-mono cf-gold">${esc(e.kind)} · ${esc(e.status)}</span><p>${esc(e.narrative)}</p>${https(e.source_url)?`<a class="cf-text-link" href="${esc(https(e.source_url))}" target="_blank" rel="noopener noreferrer">Open source ↗</a>`:''}${e.has_image?`<img src="${esc(config.api+'image/'+encodeURIComponent(e.id))}" alt="Community evidence preview, ${esc(e.status)}" loading="lazy"/>`:''}</article>`).join(''):'<p class="cf-empty">No community evidence published yet.</p>';}catch{container.textContent='Community evidence is not available on this host.';}}
 const detail=$('[data-case-detail]');if(detail){const id=detail.dataset.caseId||new URLSearchParams(location.search).get('id');const c=cases.find(c=>c.id===id);if(!c){detail.innerHTML='<h1>File not found.</h1><p>This record is unavailable or has not been published.</p>';$<HTMLFormElement>('[data-evidence-form]')!.hidden=true;}else{document.title=c.title+' | C-Files | GOTHTECHNOLOGY';detail.innerHTML=`<h1>${esc(c.title)}</h1><div class="cf-case-meta"><span>${esc(c.source_name||'Community report')}</span><span>${esc(c.location)}</span><span>${esc(c.year)}</span><span class="cf-gold">${esc(c.credibility)}</span></div><div class="cf-dossier-grid"><div><h2>The record.</h2><p>${esc(c.narrative)}</p><p class="cf-notice">A released recording is not a confirmed explanation. This archive distinguishes source provenance from claims about the event.</p></div><aside><h3>Source & metadata</h3><dl><dt>Source</dt><dd>${esc(c.source_name||'Community submission')}</dd><dt>Event date</dt><dd>${esc(c.event_date)} · ${esc(c.timezone)}</dd><dt>Recording equipment</dt><dd>${esc(c.gear||'Not provided')}</dd><dt>Location accuracy</dt><dd>${esc(c.location_note||'Approximate region')}</dd><dt>File ID</dt><dd>${esc(c.id)}</dd></dl>${https(c.source_url)?`<a class="cf-text-link" href="${esc(https(c.source_url))}" target="_blank" rel="noopener noreferrer">Read the official record ↗</a>`:''}</aside></div>`;await evidenceList(c.id);
   const ef=$<HTMLFormElement>('[data-evidence-form]')!;ef.addEventListener('submit',async event=>{event.preventDefault();const status=$('[data-form-status]',ef)!;if(!requireUser(status))return;const button=$<HTMLButtonElement>('[type=submit]',ef)!;button.disabled=true;try{const b=Object.fromEntries(new FormData(ef));await request('evidence',{...b,photo:undefined,case_id:c.id,consent:b.consent==='on',image:await photo(ef)});status.textContent='Evidence received and queued for review. It is not public yet.';ef.reset();await evidenceList(c.id);}catch(e){status.textContent=(e as Error).message;}finally{button.disabled=false;}});
  }}
 const report=$<HTMLFormElement>('[data-report-form]');if(report){const draftKey='gothtechnology.cfiles.report-draft.v1';try{const draft=JSON.parse(localStorage.getItem(draftKey)||'null');if(draft)for(const field of $$<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>('input,textarea,select',report))if(field.type!=='file'&&field.type!=='checkbox'&&draft[field.name]!=null)field.value=draft[field.name];}catch{}
  $('[data-save-draft]',report)?.addEventListener('click',()=>{const status=$('[data-form-status]',report)!;try{const b=Object.fromEntries(new FormData(report));delete b.photo;delete b.consent;localStorage.setItem(draftKey,JSON.stringify(b));status.textContent='Draft saved on this device. Photos are not saved with drafts.';}catch{status.textContent='This browser could not save the draft.';}});
  report.addEventListener('submit',async event=>{event.preventDefault();const status=$('[data-form-status]',report)!;if(!requireUser(status))return;const button=$<HTMLButtonElement>('[type=submit]',report)!;button.disabled=true;let created=false;try{const image=await photo(report);const b=Object.fromEntries(new FormData(report));const result=await request('reports',{...b,photo:undefined,consent:b.consent==='on'});created=true;try{localStorage.removeItem(draftKey);}catch{}if(image)await request('evidence',{case_id:result.id,kind:'Corroboration',narrative:'Photo supplied by the reporting witness. '+String(b.gear||''),consent:true,image});status.innerHTML=`Report received and queued for review. It is not public yet. <a class="cf-text-link" href="${esc(root+'account/')}">Track your report</a>`;report.reset();}catch(e){status.textContent=created?'Your report was saved, but the photo upload failed: '+(e as Error).message+'. You can track the report from Your account.':(e as Error).message;}finally{button.disabled=created;}});
 }
 const auth=$<HTMLFormElement>('[data-auth-form]');if(auth){let mode='login';function tab(value:string){mode=value;$$('[data-auth-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.authTab===mode)));$('[data-name-field]')!.hidden=mode!=='signup';$<HTMLInputElement>('[name=name]',auth!)!.required=mode==='signup';$('[data-auth-submit]')!.textContent=mode==='signup'?'Create account':'Sign in';$<HTMLInputElement>('[name=password]',auth!)!.autocomplete=mode==='signup'?'new-password':'current-password';}
  $$('[data-auth-tab]').forEach(b=>b.addEventListener('click',()=>tab(b.dataset.authTab!)));
  if(user){$('[data-signed-out]')!.hidden=true;$('[data-signed-in]')!.hidden=false;$('[data-welcome]')!.textContent='Welcome, '+user.name+'.';try{const result=await request('mine');$('[data-my-reports]')!.innerHTML=result.reports.length?result.reports.map((c:any)=>`<article class="cf-queue-item"><h3>${esc(c.title)}</h3><p class="cf-mono">${esc(c.status)} · ${esc(date(c.created_at))}</p>${c.status==='published'?`<a href="${esc(link(c.id))}" class="cf-text-link">Open published file ↗</a>`:''}</article>`).join(''):'<p>You have not submitted any reports yet.</p>';}catch(e){$('[data-my-reports]')!.textContent=(e as Error).message;}}
  auth.addEventListener('submit',async event=>{event.preventDefault();const status=$('[data-form-status]',auth)!;if(!connected){status.textContent='Accounts are not connected on this host.';return;}const button=$<HTMLButtonElement>('[type=submit]',auth)!;button.disabled=true;try{const result=await request('auth/'+mode,Object.fromEntries(new FormData(auth)));if(mode==='signup'){status.textContent=result.message;tab('login');}else location.reload();}catch(e){status.textContent=(e as Error).message;}finally{button.disabled=false;}});
  $('[data-sign-out]')?.addEventListener('click',async()=>{try{await request('auth/logout',{});location.reload();}catch(e){$('[data-welcome]')!.textContent=(e as Error).message;}});
 }
 const moderation=$('[data-moderation]');if(moderation){
  async function queue(){try{const result=await request('queue');const items=[...result.reports.map((i:any)=>({...i,table:'cases'})),...result.evidence.map((i:any)=>({...i,table:'evidence'}))];moderation!.innerHTML=items.length?items.map((i:any)=>`<article class="cf-queue-item"><span class="cf-mono cf-gold">${esc(i.table==='cases'?'REPORT':i.kind)} · ${esc(i.id)}</span><h2>${esc(i.title||'Evidence for '+i.case_id)}</h2><p>${esc(i.narrative)}</p><p>${esc(i.location||'')} ${esc(i.gear||'')}</p>${https(i.source_url)?`<a href="${esc(https(i.source_url))}" target="_blank" rel="noopener noreferrer">View source ↗</a>`:''}${i.has_image?`<img src="${esc(config.api+'image/'+encodeURIComponent(i.id))}" alt="Private evidence awaiting moderation"/>`:''}<form class="cf-form" data-review-id="${esc(i.id)}" data-review-kind="${esc(i.table)}">${i.table==='cases'?`<label>Evidence status<select name="credibility">${evidenceStatuses.map(s=>`<option>${esc(s)}</option>`).join('')}</select></label>`:''}<label>Decision<select name="decision"><option value="published">Publish</option><option value="rejected">Reject</option></select></label><label>Moderator rationale<textarea name="note" minlength="5" maxlength="2000" required rows="2"></textarea></label><button class="cf-button" type="submit">Save review decision</button><p data-form-status role="status"></p></form></article>`).join(''):'<p class="cf-empty">The review queue is clear.</p>';
   $$<HTMLFormElement>('[data-review-id]',moderation!).forEach(f=>f.addEventListener('submit',async e=>{e.preventDefault();const b=$<HTMLButtonElement>('[type=submit]',f)!;b.disabled=true;try{await request('review',{...Object.fromEntries(new FormData(f)),id:f.dataset.reviewId,kind:f.dataset.reviewKind});await queue();}catch(err){$('[data-form-status]',f)!.textContent=(err as Error).message;b.disabled=false;}}));
  }catch(e){moderation!.textContent=(e as Error).message;}}await queue();
 }
}
