import {mkdir,readFile,writeFile} from 'node:fs/promises';import {resolve} from 'node:path';import {spawnSync} from 'node:child_process';
const root=resolve(import.meta.dirname,'..'),art=resolve(root,'art/cinematics'),out=resolve(root,'public/exports/polish');await mkdir(out,{recursive:true});
const run=args=>{const p=spawnSync('ffmpeg',['-y','-hide_banner','-loglevel','error',...args],{stdio:'inherit'});if(p.status!==0)throw Error('Cinematic encoding failed');};
const sources=[['companion','10c0f4ec-0a53-48b9-a51c-91164aa801ee','https://d8j0ntlcm91z4.cloudfront.net/user_2vm1zUlZVo7Zg51Fx2ETKBgAmnM/hf_20261003_165715_10c0f4ec-0a53-48b9-a51c-91164aa801ee.mp4'],['rivals','2d51f750-413a-4790-8fe5-776e8d906c4b',process.argv[2]]];
for(const [name,id,url]of sources){if(!url)continue;const path=resolve(art,name+'-higgsfield.mp4');let exists=false;try{exists=(await readFile(path)).length>0;}catch{}if(!exists){const r=await fetch(url);if(!r.ok)throw Error('Higgsfield source unavailable: '+r.status);await writeFile(path,Buffer.from(await r.arrayBuffer()));}run(['-i',path,'-vf','scale=1280:720:force_original_aspect_ratio=increase,crop=1280:720,setsar=1,fps=24','-t','5','-an','-c:v','libx264','-preset','fast','-crf','21','-pix_fmt','yuv420p','-movflags','+faststart',resolve(art,name+'.mp4')]);}
for(const name of ['ride','studio','lotto','arcade'])run(['-framerate','24','-i',resolve(art,name,'frame-%04d.png'),'-frames:v','120','-an','-c:v','libx264','-preset','fast','-crf','20','-pix_fmt','yuv420p','-vf','scale=1280:720,setsar=1','-movflags','+faststart',resolve(art,name+'.mp4')]);
const edits=[{name:'swoop-intro-15',duration:15,shots:['companion','ride','studio']},...(process.argv[2]?[{name:'swoop-trailer-15',duration:15,shots:['rivals','arcade','ride']},{name:'swoop-trailer-30',duration:30,shots:['companion','ride','studio','lotto','arcade','rivals']}]:[])];
for(const edit of edits){
 const args=edit.shots.flatMap(name=>['-i',resolve(art,name+'.mp4')]);const filters=[];let previous='0:v';
 for(let i=1;i<edit.shots.length;i++){const next='blend'+i;filters.push(`[${previous}][${i}:v]xfade=transition=fade:duration=0.3:offset=${(i*4.7).toFixed(1)}[${next}]`);previous=next;}
 filters.push(`[${previous}]tpad=stop_mode=clone:stop_duration=${((edit.shots.length-1)*.3).toFixed(1)},fade=t=in:st=0:d=0.3,fade=t=out:st=${edit.duration-.35}:d=0.35[film]`);
 run([...args,'-filter_complex',filters.join(';'),'-map','[film]','-t',String(edit.duration),'-an','-c:v','libx264','-preset','fast','-crf','21','-pix_fmt','yuv420p','-movflags','+faststart',resolve(out,edit.name+'.mp4')]);
}
await writeFile(resolve(art,'edit-manifest.json'),JSON.stringify({fps:24,resolution:[1280,720],silent:true,blender:'5.2.1 LTS',blenderMaster:'Swoop_Detroit_Cinematics.blend',approvedCreditCap:6.25,freeGenjutsuRuns:1,sources:sources.filter(x=>x[2]).map(([name,job,url])=>({name,job,url})),edits,transition:'0.3-second dissolves; final frame pads preserve exact 15/30-second duration; no camera motion synthesized from static images.'},null,2));console.log('SWOOP_CINEMATIC_ASSEMBLY_OK / '+edits.map(e=>e.name).join(', '));
