import {RealtimeClient} from '../../../../../output/swoop-polish-20261003/asset-tools/node_modules/@supabase/realtime-js/dist/main/index.js';
import {randomUUID} from 'node:crypto';import {readFile,writeFile} from 'node:fs/promises';
const config=await readFile(new URL('../src/detroit/onlineConfig.ts',import.meta.url),'utf8'),url=/url:'([^']+)'/.exec(config)[1],key=/key:'([^']+)'/.exec(config)[1],room='swoop:qa:'+randomUUID(),clients=[],channels=[];const seen=new Set(),states=[];
try{
 for(let i=0;i<4;i++){const client=new RealtimeClient(url+'/realtime/v1',{params:{apikey:key}});clients.push(client);const channel=client.channel(room,{config:{presence:{key:'qa-'+i},broadcast:{ack:true,self:false},private:false}});channels.push(channel);channel.on('presence',{event:'sync'},()=>{});channel.on('broadcast',{event:'qa'},message=>{if(message.payload.marker==='four-real-clients')seen.add(i);});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Realtime subscribe timeout / client '+i)),15000);channel.subscribe(status=>{if(status==='SUBSCRIBED'){clearTimeout(timer);resolve();}if(['CHANNEL_ERROR','TIMED_OUT'].includes(status)){clearTimeout(timer);reject(Error(status));}});});await channel.track({id:'qa-'+i,kind:'Swoop room transport check'});}
 await new Promise(resolve=>setTimeout(resolve,2500));await channels[0].send({type:'broadcast',event:'qa',payload:{marker:'four-real-clients'}});await new Promise(resolve=>setTimeout(resolve,700));for(const channel of channels)states.push(Object.keys(channel.presenceState()).length);
 console.log(JSON.stringify({presence:states,recipients:[...seen]}));if(seen.size!==3||states.some(count=>count!==4))throw Error('Expected all four real clients and three remote recipients');
 const proof={project:'lottomind',projectRef:'sqdasdbvlkgpbbiyeune',checked:new Date().toISOString(),presenceCounts:states,broadcastRecipients:[...seen].sort(),room:'ephemeral QA room',tablesChanged:false};await writeFile(new URL('../art/live-room-proof.json',import.meta.url),JSON.stringify(proof,null,2));console.log(JSON.stringify(proof));
}finally{await Promise.all(channels.map((channel,i)=>clients[i].removeChannel(channel)));for(const client of clients)client.disconnect();}
