"""Sample the existing 2017 Wayne County one-metre DEM into the game plan frame.
The map registration remains an approximate two-landmark fit, not a site survey.
"""
from pathlib import Path
import json,re,shutil
import numpy as np
from PIL import Image
from pyproj import Transformer
ROOT=Path(__file__).resolve().parents[1]
library=ROOT.parents[2]/'euc-detroit-riverwalk/art/elmwood/terrain'
meta=json.loads((library/'georeference.json').read_text())
a=np.asarray(Image.open(library/'Elmwood_DEM_1m.tif'),dtype=float)
transform=Transformer.from_crs(4326,26917,always_xy=True)
coords=np.array([(x,z) for z in range(100,721,2) for x in range(0,1231,2)])
dx,dz=coords[:,0]-948,coords[:,1]-229
lon=-83.016495+(.5534*dx-.7947*dz)*.00001073
lat=42.347071-(.7947*dx+.5534*dz)*.00000793
east,north=transform.transform(lon,lat)
x0,y0,x1,y1=meta['dem']['boundsUTM']
x=np.clip(east-x0-.5,0,a.shape[1]-1.001);z=np.clip(y1-north-.5,0,a.shape[0]-1.001)
i,j=x.astype(int),z.astype(int);u,v=x-i,z-j
def sample(array):return (array[j,i]*(1-u)+array[j,i+1]*u)*(1-v)+(array[j+1,i]*(1-u)+array[j+1,i+1]*u)*v
def blur(array,n):
    for _ in range(n):
        p=np.pad(array,1,mode='edge');array=(p[1:-1,1:-1]*4+p[:-2,1:-1]+p[2:,1:-1]+p[1:-1,:-2]+p[1:-1,2:])/8
    return array
raw=sample(blur(a,3));graded=sample(blur(a,1200))
code=(ROOT/'src/detroit/elmwood.ts').read_text()
roads=json.loads(re.search(r'export const ELM_ROADS=(\[.*?\n\]);',code,re.S)[1]);distance=np.full(len(coords),np.inf)
for road in roads:
    for start,end in zip(road,road[1:]):
        start=np.array(start);delta=np.array(end)-start
        t=np.clip(((coords-start)*delta).sum(axis=1)/max(1,(delta*delta).sum()),0,1)
        distance=np.minimum(distance,np.linalg.norm(coords-start-t[:,None]*delta,axis=1)*.686486)
blend=np.clip((distance-4)/8,0,1);blend=blend*blend*(3-2*blend)
values=np.round(graded*(1-blend)+raw*blend,3).tolist()
target=ROOT/'src/detroit/elmwood-dem.ts'
backup=ROOT/'backups/elmwood-before-realism';backup.mkdir(parents=True,exist_ok=True)
if not (backup/target.name).exists():shutil.copy2(target,backup/target.name)
out=dict(source='USGS MI_WayneCo_2017 one-metre bare-earth DEM',publication='2020-03-30',sourceResolutionMetres=1,
 alignment='Existing approximate two-landmark plan fit; local lane smoothing over 4-12 metres; not surveyed',
 planX=0,planZ=100,step=2,width=616,height=311,datum=183.204,minMetres=min(values),maxMetres=max(values))
target.write_text('// Generated by scripts/refine_elmwood_dem.py from archived USGS data.\nexport const ELM_DEM='+json.dumps(out)+' as const;\nexport const ELM_ELEVATIONS='+json.dumps(values,separators=(',',':'))+';\n')
print(json.dumps(out))
