"""Resample the archived USGS 3DEP F32 export into the cemetery plan frame.

Google satellite reference inspected 2026-09-15. Manual tie points, not survey:
roundabout plan (948,229) -> (42.347071,-83.016495);
pond centre plan (850,386) -> (42.346999,-83.018416).
The similarity fit uses north-up screen pixel axes; retain the original plan
scale for gameplay. This cannot eliminate distortions in the published plan.
"""
from pathlib import Path
import json
import re
import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
a = np.array(Image.open(ROOT / 'elmwood-dem.tiff'), dtype=float)
# Modest 8 m-ish low pass removes fine DEM noise, preserving valley relief.
for _ in range(3):
    p = np.pad(a, 1, mode='edge')
    a = (p[1:-1,1:-1]*4+p[:-2,1:-1]+p[2:,1:-1]+p[1:-1,:-2]+p[1:-1,2:])/8

def gps(px,pz):
    dx,dz=px-948,pz-229
    # Orthogonal fit from the two visible satellite landmarks.
    sx=.5534*dx-.7947*dz
    sy=.7947*dx+.5534*dz
    return 42.347071-sy*.00000793,-83.016495+sx*.00001073

def sample(px,pz):
    lat,lon=gps(px,pz)
    x=np.clip((lon+83.025)/.013*256-.5,0,254.999)
    z=np.clip((42.356-lat)/.013*256-.5,0,254.999)
    i,j=int(x),int(z);u,v=x-i,z-j
    return float((a[j,i]*(1-u)+a[j,i+1]*u)*(1-v)+(a[j+1,i]*(1-u)+a[j+1,i+1]*u)*v)

coords=[(x,z) for z in range(100,721,10) for x in range(0,1231,10)]
raw=np.array([sample(x,z) for x,z in coords])
# Grade only lane corridors from a wider low-pass field; retain the measured
# hills away from lanes. This bridges plan/DEM registration error at banks.
for _ in range(55):
    p=np.pad(a,1,mode='edge')
    a=(p[1:-1,1:-1]*4+p[:-2,1:-1]+p[2:,1:-1]+p[1:-1,:-2]+p[1:-1,2:])/8
graded=np.array([sample(x,z) for x,z in coords])
code=(ROOT/'src/detroit/elmwood.ts').read_text()
roads=json.loads(re.search(r'export const ELM_ROADS=(\[.*?\n\]);',code,re.S)[1])
q=np.array(coords);distance=np.full(len(q),np.inf)
for road in roads:
    for start,end in zip(road,road[1:]):
        start=np.array(start);delta=np.array(end)-start
        t=np.clip(((q-start)*delta).sum(axis=1)/(delta*delta).sum(),0,1)
        distance=np.minimum(distance,np.linalg.norm(q-start-t[:,None]*delta,axis=1))
blend=np.clip((distance-10)/20,0,1);blend=blend*blend*(3-2*blend)
values=np.round(graded*(1-blend)+raw*blend,3).tolist()
meta=dict(source='https://elevation.nationalmap.gov/arcgis/rest/services/3DEPElevation/ImageServer',
    fetched='2026-09-15',bbox=[-83.025,42.343,-83.012,42.356],rasterSize=[256,256],
    alignment='Manual two-landmark Google satellite similarity fit; approximate; lane corridors graded',
    planX=0,planZ=100,step=10,width=124,height=63,datum=round(sample(1075,485),3),
    minMetres=min(values),maxMetres=max(values))
(ROOT/'src/detroit/elmwood-dem.ts').write_text('// USGS public-domain 3DEP elevation; generated by scripts/sample_elmwood_dem.py\nexport const ELM_DEM='+json.dumps(meta)+' as const;\nexport const ELM_ELEVATIONS='+json.dumps(values)+';\n')
print(json.dumps(meta,indent=2))
