import type {CommunityRide} from './communityRide.ts';
/** Small shared accessible event panel; game adapters own travel and pause semantics. */
export function communityPanel(title:string,ride:CommunityRide,player:()=>{x:number;z:number},travel:()=>void,focus:()=>void){
  const panel=document.createElement('details');panel.className='community-panel';panel.setAttribute('aria-label',title);panel.innerHTML='<summary></summary><p class="community-status" role="status"></p><div></div><small>Local NPC ride · solo mode · no online rewards</small>';
  panel.querySelector('summary')!.textContent=title;const status=panel.querySelector('p')!,buttons=panel.querySelector('div')!;
  const button=(label:string,action:()=>void)=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{action();focus();update(true);};buttons.append(b);return b;};
  const join=button('Join ride',()=>ride.joined?ride.leave():ride.join(player()));const skip=button('Roll out now',()=>ride.continue());button('Meet the riders',()=>{travel();ride.continue();});button('Cancel ride',()=>ride.cancel());button('Restart gathering',()=>{ride.restart();travel();ride.continue();});
  const style=document.createElement('style');style.textContent='.community-panel{position:fixed;z-index:25;left:50%;transform:translateX(-50%);bottom:72px;width:min(420px,calc(100vw - 32px));background:#122d2bef;color:#f2ead1;border:1px solid #bdab70;border-radius:12px;max-height:45vh;overflow:auto;padding:10px 14px;font:13px system-ui;box-sizing:border-box}.community-panel[hidden]{display:none}.community-panel summary{cursor:pointer;font-weight:700;min-height:34px}.community-panel p{margin:8px 0}.community-panel div{display:flex;flex-wrap:wrap;gap:6px}.community-panel div>button{width:auto;flex:1 1 auto;min-height:44px;padding:6px 12px;background:#264a44;color:#fff;border:1px solid #8ca79c;border-radius:7px}.community-panel button:focus-visible{outline:3px solid #ffdc72}.community-panel small{display:block;margin-top:8px;font-size:11px}@media(max-width:650px){.community-panel{bottom:auto;top:190px;width:calc(100vw - 40px)}.community-panel:not([open]){width:auto;max-width:calc(100vw - 40px)}}';document.head.append(style);document.body.append(panel);
  function update(visible:boolean){panel.hidden=!visible;const p=player(),near=ride.route.nearest(p);status.textContent=ride.message+' '+(ride.continuous?`Lap ${ride.laps+1} · ${ride.joined?'Riding with the group':'Catch the pack to join'}`:ride.joined?`${ride.stage.toUpperCase()} · ${Math.round(near.s)} / ${Math.round(ride.route.length)} m · ${ride.nextGate}/${ride.gates.length} markers${ride.eligible?'':' · social ride'}`:`Gathering ${Math.round(Math.hypot(p.x-ride.route.points[0].x,p.z-ride.route.points[0].z))} m away`);join.textContent=ride.joined?'Leave ride':'Join ride';join.disabled=ride.stage==='complete'||ride.stage==='cleanup'||ride.stage==='hangout';skip.hidden=ride.stage!=='rollout'&&ride.stage!=='regroup';skip.textContent=ride.stage==='regroup'?'Continue ride':'Roll out now';}
  return {panel,update,dispose(){panel.remove();style.remove();}};
}

