import Phaser from "phaser";
import "./styles.css";
import "./polish.css";
import { BoardScene } from "./scene/BoardScene";
import { createInitialState, type GameMode, type GameState } from "./engine/state";
import { reducer } from "./engine/reducer";
import type { GameAction } from "./engine/actions";
import { chooseCpuAction, chooseRoute } from "./engine/ai";
import { boardNodes } from "./content/board";
import { cityPulseCards, oracleCards } from "./content/cards";
import { districts } from "./content/districts";
import { developmentNames, ventures } from "./content/ventures";
import { scorePlayer } from "./engine/scoring";
import { dailySeed } from "./engine/rng";
import { clearSave, loadGame, saveGame } from "./services/storage";
import { sendToSavedWallet } from "./services/wallet";

const app=document.querySelector<HTMLDivElement>("#app")!;
if(location.pathname.includes("/games/lottomind-313-fortune-grid/")){
  ["../../../assets/js/lottomind-account-service.js","../../../assets/js/lm-game-rewards-sdk.js"].forEach((source)=>{const script=document.createElement("script");script.src=new URL(source,location.href).href;script.defer=true;document.head.append(script)});
}
app.innerHTML=`<div class="shell"><header class="topbar"><a class="brand" href="../../features-app.html"><img src="./assets/icons/icon.svg" alt=""><span><strong>LottoMind 313: Fortune Grid</strong><small>Build the city. Read the signals. Make your move. · Beta</small></span></a><p class="notice">Simulated game sequence for entertainment only. LottoMind does not predict lottery outcomes.</p><div class="topbar-actions"><button data-action="help">Help</button><button data-action="settings">Settings</button></div></header><main class="game-layout"><section class="playfield" aria-label="Interactive Fortune Grid board"><div class="round-chip" data-round>Setup</div><div class="camera-controls"><button data-camera="follow" aria-label="Return camera to current player">Player</button><button data-camera="overview" aria-label="Show board overview">Overview</button></div><div id="game" class="game-canvas"></div></section><aside class="hud" id="game-actions" aria-label="Game actions" data-hud></aside></main></div><div aria-live="polite" aria-atomic="true" class="sr-live" data-live></div><div data-modal></div><div data-toast></div>`;

const modal=app.querySelector<HTMLElement>("[data-modal]")!;const hud=app.querySelector<HTMLElement>("[data-hud]")!;const live=app.querySelector<HTMLElement>("[data-live]")!;const roundChip=app.querySelector<HTMLElement>("[data-round]")!;const toastHost=app.querySelector<HTMLElement>("[data-toast]")!;
let state:any=null;let busy=false;let selectedRoute:number[]|null=null;
const game=new Phaser.Game({type:Phaser.AUTO,parent:"game",backgroundColor:"#05040a",scene:[BoardScene],scale:{mode:Phaser.Scale.RESIZE,width:"100%",height:"100%"},render:{antialias:true,powerPreference:"high-performance"}});
const scene=()=>game.scene.getScene("board") as BoardScene;

function announce(message:string){live.textContent="";requestAnimationFrame(()=>live.textContent=message)}
function toast(message:string){toastHost.innerHTML=`<p class="toast" role="status">${escapeHtml(message)}</p>`;setTimeout(()=>toastHost.replaceChildren(),3500)}
function escapeHtml(value:unknown){return String(value).replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!))}
function dispatch(action:GameAction){if(!state)return;const previous=state;state=reducer(state,action);if(state===previous)return;saveGame(state);scene().setState(state);render();const message=state.eventLog.at(-1)?.message;if(message)announce(message);queueCpu();}

function showSetup(){modal.innerHTML=`<div class="modal-backdrop"><form class="modal" data-setup><p class="disclaimer">Original LottoMind Arcade strategy experience · Beta</p><h1>LottoMind 313: Fortune Grid</h1><p>Establish fictional ventures across eight Detroit-inspired district networks. A full Standard match lasts thirteen rounds.</p><div class="setup-grid"><label>Mode<select name="mode"><option value="quick313">Quick 313 · 3 rounds</option><option value="standard">Standard · 13 rounds</option><option value="daily">Daily seeded · 3 rounds</option></select></label><label>Total players<select name="players"><option>2</option><option>3</option><option>4</option></select></label><label>Local players<select name="locals"><option>1</option><option>2</option><option>3</option><option>4</option></select></label></div><p class="disclaimer">Players establish original ventures and partnerships in represented districts; they do not buy neighborhoods. Detroit Dollars exist only within this match. LottoMind Credits are never granted by the browser.</p><div class="dialog-actions"><button class="primary" type="submit">Launch Fortune Grid</button>${loadGame()?'<button type="button" data-resume>Resume saved match</button>':""}<a class="button" href="../../features-app.html">Return to LottoMind Arcade</a></div></form></div>`;const form=modal.querySelector<HTMLFormElement>("[data-setup]")!;form.addEventListener("submit",(event)=>{event.preventDefault();const data=new FormData(form);const mode=data.get("mode") as GameMode;const players=Number(data.get("players"));const locals=Math.min(players,Number(data.get("locals")));const seed=mode==="daily"?dailySeed():Number(`${Date.now()}`.slice(-9));start(createInitialState({mode,playerCount:players,localPlayers:locals,seed}));});modal.querySelector("[data-resume]")?.addEventListener("click",()=>{const saved=loadGame();if(saved)start(saved)});}
function start(next:GameState){state=next;modal.replaceChildren();document.documentElement.style.setProperty("--text-scale",String(state.settings.textScale));document.body.classList.toggle("high-contrast",state.settings.highContrast);const hydrate=()=>{const board=scene();if(!board.sys.isActive()){setTimeout(hydrate,50);return;}board.setState(state);board.fitOverview();render();queueCpu()};hydrate()}

async function roll(){if(!state||busy||state.phase!=="roll")return;busy=true;dispatch({type:"ROLL"});await new Promise(r=>setTimeout(r,state?.settings.reducedMotion?0:650));busy=false;const rolledState=state as GameState|null;if(!rolledState)return;if(rolledState.phase==="moving"){selectedRoute=rolledState.players[rolledState.currentPlayer].cpu?chooseRoute(rolledState):rolledState.pendingRoll!.routes[0];await moveSelected();}else render();}
async function moveSelected(){if(!state||busy||!selectedRoute)return;busy=true;const player=state.players[state.currentPlayer];await scene().animateRoute(player.id,selectedRoute,state.settings.reducedMotion);const route=selectedRoute;selectedRoute=null;busy=false;dispatch({type:"COMPLETE_MOVEMENT",route});scene().followPlayer();}
function choosePlayerRoute(index:number){if(!state||state.phase!=="route")return;selectedRoute=state.pendingRoll?.routes[index]||null;if(selectedRoute){dispatch({type:"CHOOSE_ROUTE",route:selectedRoute});moveSelected();}}

function render(){if(!state)return;const player=state.players[state.currentPlayer];const node=boardNodes[player.nodeId];const owner=node.kind==="venture"?state.players.find(p=>p.ventures[node.ventureId!]):undefined;const venture=node.kind==="venture"?ventures[node.ventureId!]:null;roundChip.textContent=`Round ${Math.min(state.round,state.maxRounds)} / ${state.maxRounds} · ${state.mode}`;document.body.classList.toggle("high-contrast",state.settings.highContrast);document.documentElement.style.setProperty("--text-scale",String(state.settings.textScale));if(state.phase==="ended"){renderResults();return;}const routeMarkup=state.phase==="route"?`<section class="panel"><strong>Choose a route</strong><div class="route-list">${state.pendingRoll!.routes.slice(0,6).map((route,index)=>`<button data-route="${index}">Route ${index+1}: ${route.slice(1).map(id=>boardNodes[id].kind==="venture"?ventures[boardNodes[id].ventureId!].name:boardNodes[id].label).join(" → ")}</button>`).join("")}</div></section>`:"";const ventureAction=venture?(!owner&&!player.rebuild?`<button class="primary" data-game-action="launch" ${player.dollars<venture.launchCost?"disabled":""}>Launch ${escapeHtml(venture.name)} · ${venture.launchCost} DD</button>`:owner?.id===player.id&&player.ventures[venture.id]<4?`<button data-game-action="upgrade">Upgrade ${escapeHtml(venture.name)} · Level ${player.ventures[venture.id]+1}</button>`:owner&&owner.id!==player.id?`<p>${escapeHtml(owner.name)} operates this venture at ${developmentNames[owner.ventures[venture.id]]} level.</p>`:""):"";
  hud.innerHTML=`<section class="turn-card"><small>CURRENT SIGNAL PILOT</small><h1>${escapeHtml(player.name)}${player.cpu?` · CPU ${player.personality}`:""}</h1><div class="resources"><div class="resource"><small>Detroit Dollars</small><strong>${player.dollars}</strong></div><div class="resource"><small>Legacy</small><strong>${player.legacy}</strong></div><div class="resource"><small>Focus</small><strong>${player.focus}</strong></div></div>${player.rebuild?'<p><strong>Rebuild Mode:</strong> launch paused. Use Community Grant, partnership, or sell-back recovery.</p>':""}</section><section class="panel"><strong>Signal Strip · Pick 3 / Pick 4-style</strong><div class="signal-strip" aria-label="Current simulated sequence">${player.signals.length?player.signals.map((digit,i)=>`<button class="digit" data-digit="${i}" aria-label="Signal digit ${i+1}: ${digit}">${digit}</button>`).join(""):'<span>Roll to collect digits.</span>'}</div><div class="utility-actions"><button data-signal="sort">Sort</button><button data-signal="save">Save idea</button><button data-signal="copy">Copy</button><button data-signal="wallet">Send to Wallet</button></div><p class="disclaimer">Simulated game sequence for entertainment only. LottoMind does not predict lottery outcomes.</p></section>${state.pendingRoll?`<section class="panel roll-result"><span>Movement Cube <strong>${state.pendingRoll.movement}</strong></span><span>Signal Orb <strong>${state.pendingRoll.signal}</strong></span></section>`:""}${routeMarkup}<section class="panel actions"><strong>${node.kind==="venture"?escapeHtml(venture!.name):escapeHtml(node.label)}</strong>${venture?`<small>${escapeHtml(venture.description)} · ${districts.find(d=>d.id===venture.district)?.name}</small>`:""}<button class="primary" data-game-action="roll" ${state.phase!=="roll"||busy?"disabled":""}>Roll Movement Cube + Signal Orb</button>${state.phase==="action"?ventureAction+portfolioActions(player):""}${node.kind==="studio"&&state.phase==="action"?'<button data-game-action="beat">Open Beat Studio</button>':""}${state.phase==="action"?'<button data-game-action="end">End turn</button>':""}</section><section class="panel"><strong>Players</strong><div class="players">${state.players.map((p,i)=>`<div class="player-row"><i class="swatch" style="background:${p.color}"></i><span>${escapeHtml(p.name)}${i===state.currentPlayer?" · ACTIVE":""}</span><b>${scorePlayer(p).total}</b></div>`).join("")}</div></section><details class="panel"><summary>Portfolio and network bonuses</summary>${portfolioMarkup(player)}</details><details class="panel"><summary>Match log</summary><ol class="log">${state.eventLog.slice(-12).reverse().map(e=>`<li>${escapeHtml(e.message)}</li>`).join("")}</ol></details>`;bindHud();if(state.activeCard)showCard();}
function portfolioActions(player:GameState["players"][number]){const entries=Object.keys(player.ventures).map(Number);if(!entries.length)return"";const id=entries[0];return`<div class="utility-actions"><button data-portfolio="sponsor" data-id="${id}">Sponsor</button><button data-portfolio="partner" data-id="${id}">Partner</button><button data-portfolio="sell" data-id="${id}">Sell back</button></div>`}
function portfolioMarkup(player:GameState["players"][number]){const entries=Object.entries(player.ventures);return entries.length?`<ul>${entries.map(([id,level])=>`<li>${escapeHtml(ventures[Number(id)].name)} · ${developmentNames[level]}</li>`).join("")}</ul><h3>District network bonuses</h3><ul>${districts.map(d=>`<li><strong>${d.symbol} ${d.name}:</strong> ${d.bonus}</li>`).join("")}</ul>`:"<p>No ventures launched yet.</p>"}
function bindHud(){hud.querySelector("[data-game-action=roll]")?.addEventListener("click",roll);hud.querySelector("[data-game-action=launch]")?.addEventListener("click",()=>dispatch({type:"LAUNCH_VENTURE"}));hud.querySelector("[data-game-action=upgrade]")?.addEventListener("click",()=>{if(!state)return;const id=boardNodes[state.players[state.currentPlayer].nodeId].ventureId!;dispatch({type:"UPGRADE_VENTURE",ventureId:id})});hud.querySelector("[data-game-action=end]")?.addEventListener("click",()=>dispatch({type:"END_TURN"}));hud.querySelector("[data-game-action=beat]")?.addEventListener("click",showBeatStudio);hud.querySelectorAll<HTMLElement>("[data-route]").forEach(el=>el.addEventListener("click",()=>choosePlayerRoute(Number(el.dataset.route))));hud.querySelector("[data-signal=sort]")?.addEventListener("click",()=>dispatch({type:"SIGNAL_SORT"}));hud.querySelector("[data-signal=save]")?.addEventListener("click",()=>dispatch({type:"SAVE_SEQUENCE"}));hud.querySelector("[data-signal=copy]")?.addEventListener("click",()=>state&&navigator.clipboard.writeText(state.players[state.currentPlayer].signals.join("")).then(()=>toast("Sequence copied as an entertainment-only number idea.")));hud.querySelector("[data-signal=wallet]")?.addEventListener("click",async()=>{if(!state)return;const p=state.players[state.currentPlayer];try{await sendToSavedWallet(p.signals,state.matchId);toast("Sequence sent to the shared LottoMind Saved Numbers Wallet.")}catch(error){toast((error as Error).message)}});hud.querySelectorAll<HTMLElement>("[data-portfolio]").forEach(el=>el.addEventListener("click",()=>{const ventureId=Number(el.dataset.id);if(el.dataset.portfolio==="sell")dispatch({type:"SELL_VENTURE",ventureId});if(el.dataset.portfolio==="sponsor")dispatch({type:"SPONSOR_VENTURE",ventureId});if(el.dataset.portfolio==="partner")dispatch({type:"PARTNER_VENTURE",ventureId})}));}

function showCard(){if(!state?.activeCard)return;const list=state.activeCard.type==="pulse"?cityPulseCards:oracleCards;const card=list.find(c=>c.id===state!.activeCard!.id)!;modal.innerHTML=`<div class="modal-backdrop"><article class="modal" role="dialog" aria-modal="true" aria-labelledby="card-title"><p>${state.activeCard.type==="pulse"?"City Pulse":"Dream Oracle"}</p><h2 id="card-title">${escapeHtml(card.title)}</h2><div role="img" aria-label="${escapeHtml(card.artAlt)}" style="min-height:180px;border-radius:16px;background:radial-gradient(circle at 30% 25%,#ffdc75,#5b2f94 48%,#071d35);display:grid;place-items:center;font-size:4rem">${state.activeCard.type==="pulse"?"✦":"◐"}</div><p>${escapeHtml(card.text)}</p><p><strong>Effect:</strong> ${card.effect} +${card.amount}</p><button class="primary" data-close-card>Continue</button></article></div>`;modal.querySelector("[data-close-card]")?.addEventListener("click",()=>{modal.replaceChildren();dispatch({type:"DISMISS_CARD"})});}
function showBeatStudio(){let hits=0;let step=0;modal.innerHTML=`<div class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true"><h2>Beat Studio · Four Beat Signal</h2><p>Press Space, click, or tap the active pad. This visual mode works without audio.</p><div class="beat-grid">${[0,1,2,3].map(i=>`<button class="beat-pad" data-pad="${i}">Beat ${i+1}</button>`).join("")}</div><p data-beat-status>Ready. No time pressure; use Finish anytime.</p><div class="dialog-actions"><button class="primary" data-start-beat>Start visual beat</button><button data-finish-beat>Finish</button></div></section></div>`;let timer:number|undefined;const activate=()=>{modal.querySelectorAll(".beat-pad").forEach((el,i)=>el.classList.toggle("active",i===step%4));step++;if(step>8&&timer)clearInterval(timer)};modal.querySelector("[data-start-beat]")?.addEventListener("click",()=>{activate();timer=window.setInterval(activate,state?.settings.reducedMotion?800:520)});modal.querySelectorAll(".beat-pad").forEach(el=>el.addEventListener("click",()=>{if(el.classList.contains("active")){hits++;(modal.querySelector("[data-beat-status]") as HTMLElement).textContent=`${hits} signal hits.`}}));modal.querySelector("[data-finish-beat]")?.addEventListener("click",()=>{if(timer)clearInterval(timer);modal.replaceChildren();dispatch({type:"BEAT_RESULT",hits})});}
function renderResults(){if(!state)return;const scores=state.players.map(p=>({player:p,score:scorePlayer(p)})).sort((a,b)=>b.score.total-a.score.total);hud.innerHTML=`<section class="turn-card"><h1>${escapeHtml(scores[0].player.name)} is the Fortune Visionary</h1><p>Standard score breakdown</p></section><table class="score-table"><thead><tr><th>Player</th><th>Legacy</th><th>Networks</th><th>Development</th><th>Signals</th><th>Focus</th><th>Total</th></tr></thead><tbody>${scores.map(({player,score})=>`<tr><td>${escapeHtml(player.name)}</td><td>${score.legacy}</td><td>${score.networks}</td><td>${score.development}</td><td>${score.signals}</td><td>${score.focus}</td><td><strong>${score.total}</strong></td></tr>`).join("")}</tbody></table><p class="disclaimer">All rewards shown are in-game only. LottoMind Credits require separate authenticated server verification and are disabled in this static Beta.</p><div class="dialog-actions"><button class="primary" data-new-game>New match</button><a class="button" href="../../features-app.html">Return to LottoMind Arcade</a></div>`;hud.querySelector("[data-new-game]")?.addEventListener("click",()=>{clearSave();state=null;showSetup()});}
function showSettings(){if(!state){toast("Start or resume a match to change game settings.");return;}modal.innerHTML=`<div class="modal-backdrop"><form class="modal settings-grid" data-settings><h2>Accessibility and game settings</h2><label><input type="checkbox" name="reduced" ${state.settings.reducedMotion?"checked":""}> Reduced motion camera and token travel</label><label><input type="checkbox" name="particles" ${state.settings.particles?"checked":""}> Environmental particles</label><label><input type="checkbox" name="contrast" ${state.settings.highContrast?"checked":""}> High contrast</label><label><input type="checkbox" name="muted" ${state.settings.muted?"checked":""}> Mute audio (audio never autoplays)</label><label>Text size <select name="text"><option value="1">Standard</option><option value="1.15">Large</option><option value="1.3">Extra large</option></select></label><div class="dialog-actions"><button class="primary" type="submit">Apply</button><button type="button" data-close>Cancel</button></div></form></div>`;const form=modal.querySelector<HTMLFormElement>("[data-settings]")!;(form.elements.namedItem("text") as HTMLSelectElement).value=String(state.settings.textScale);form.addEventListener("submit",e=>{e.preventDefault();const data=new FormData(form);dispatch({type:"SETTINGS",patch:{reducedMotion:data.has("reduced"),particles:data.has("particles"),highContrast:data.has("contrast"),muted:data.has("muted"),textScale:Number(data.get("text"))}});modal.replaceChildren()});modal.querySelector("[data-close]")?.addEventListener("click",()=>modal.replaceChildren());}
function showHelp(){modal.innerHTML=`<div class="modal-backdrop"><article class="modal"><h2>How to Play</h2><ol><li>Roll a Movement Cube (1–6) and Signal Orb (0–9).</li><li>Choose a route at intersections, then watch the token reach its destination.</li><li>Launch fictional ventures, upgrade them, and complete three-venture district networks.</li><li>Use Focus to explore digits and collect Legacy Points. A Standard game ends after 13 rounds.</li><li>Players without Detroit Dollars enter Rebuild Mode instead of being eliminated.</li></ol><h3>Controls</h3><p>Tab and Enter operate every action. Arrow keys or WASD pan the camera. Mouse/touch drag pans; wheel/pinch-compatible trackpads zoom. Press 0 for overview. No audio begins without player interaction.</p><button class="primary" data-close>Close</button></article></div>`;modal.querySelector("[data-close]")?.addEventListener("click",()=>modal.replaceChildren());}
async function queueCpu(){if(!state||busy||!state.players[state.currentPlayer].cpu||state.phase==="ended")return;busy=true;await new Promise(r=>setTimeout(r,state?.settings.reducedMotion?20:500));busy=false;if(!state)return;if(state.phase==="roll")return roll();if(state.phase==="moving"){selectedRoute=chooseRoute(state);return moveSelected()}if(state.phase==="action"){const action=chooseCpuAction(state);dispatch(action);if(action.type!=="END_TURN")setTimeout(()=>state&&dispatch({type:"END_TURN"}),state.settings.reducedMotion?20:400)}}

app.querySelector("[data-action=help]")?.addEventListener("click",showHelp);app.querySelector("[data-action=settings]")?.addEventListener("click",showSettings);app.querySelector("[data-camera=follow]")?.addEventListener("click",()=>scene().followPlayer());app.querySelector("[data-camera=overview]")?.addEventListener("click",()=>scene().fitOverview());window.addEventListener("keydown",e=>{if(e.key===" "&&state?.phase==="roll"&&!e.repeat){e.preventDefault();roll()}});window.addEventListener("beforeunload",()=>state&&saveGame(state));
if("serviceWorker" in navigator&&location.protocol.startsWith("http"))window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js",{scope:"./"}).catch(()=>toast("Offline support will activate after a successful hosted load.")));
showSetup();

function decorateHudControls(){
  if(!state||!hud.isConnected)return;
  if(!hud.querySelector("[data-game-utilities]")){
    const utilities=document.createElement("section");
    utilities.className="panel utility-actions";
    utilities.dataset.gameUtilities="true";
    utilities.innerHTML='<button data-utility="save">Save match</button><button data-utility="lab">Number Lab</button><button data-utility="restart">New match</button>';
    hud.prepend(utilities);
  }
  const player=state.players[state.currentPlayer];
  hud.querySelectorAll<HTMLButtonElement>("[data-digit]").forEach((button)=>{
    const index=Number(button.dataset.digit);const locked=player.lockedSignals?.includes(index);const digit=player.signals[index];
    button.classList.toggle("locked",Boolean(locked));button.setAttribute("aria-pressed",String(Boolean(locked)));button.setAttribute("aria-label",`Signal digit ${index+1}: ${digit}. ${locked?"Locked":"Unlocked"}`);const nextText=`${locked?"🔒 ":""}${digit}`;if(button.textContent!==nextText)button.textContent=nextText;
  });
  const portfolioRow=hud.querySelector<HTMLElement>("[data-portfolio=sponsor]")?.parentElement;
  if(portfolioRow&&!portfolioRow.querySelector("[data-portfolio=trade]")){const trade=document.createElement("button");trade.dataset.portfolio="trade";trade.textContent="Trade";portfolioRow.append(trade)}
}

function showNumberLab(){
  if(!state)return;const player=state.players[state.currentPlayer];if(!player.signals.length){toast("Collect a Signal digit before opening Number Lab.");return;}
  modal.innerHTML=`<div class="modal-backdrop"><form class="modal" data-number-lab><h2>Number Lab</h2><p>Lock digits to protect them from new rolls. Reorder unlocked positions or replace one unlocked digit using a Focus Token. Sorting is pattern visualization only, never a prediction.</p><div class="signal-strip">${player.signals.map((digit:number,index:number)=>`<span class="digit">${player.lockedSignals.includes(index)?"🔒 ":""}${digit}</span>`).join("")}</div><div class="setup-grid"><label>Position<select name="index">${player.signals.map((_digit:number,index:number)=>`<option value="${index}">${index+1}${player.lockedSignals.includes(index)?" · locked":""}</option>`).join("")}</select></label><label>Replacement digit<select name="digit">${Array.from({length:10},(_,digit)=>`<option>${digit}</option>`).join("")}</select></label><label>Move position to<select name="to">${player.signals.map((_digit:number,index:number)=>`<option value="${index}">${index+1}</option>`).join("")}</select></label></div><div class="dialog-actions"><button type="button" data-lab="lock">Lock / unlock</button><button type="button" data-lab="replace">Replace · 1 Focus</button><button type="button" data-lab="reorder">Reorder</button><button class="primary" type="button" data-lab="close">Done</button></div></form></div>`;
  const form=modal.querySelector<HTMLFormElement>("[data-number-lab]")!;const value=(name:string)=>Number((form.elements.namedItem(name) as HTMLSelectElement).value);
  form.querySelector("[data-lab=lock]")?.addEventListener("click",()=>{dispatch({type:"SIGNAL_LOCK",index:value("index")});showNumberLab()});
  form.querySelector("[data-lab=replace]")?.addEventListener("click",()=>{dispatch({type:"SIGNAL_REPLACE",index:value("index"),digit:value("digit")});showNumberLab()});
  form.querySelector("[data-lab=reorder]")?.addEventListener("click",()=>{dispatch({type:"SIGNAL_REORDER",from:value("index"),to:value("to")});showNumberLab()});
  form.querySelector("[data-lab=close]")?.addEventListener("click",()=>modal.replaceChildren());
}

new MutationObserver(decorateHudControls).observe(hud,{childList:true,subtree:true});
hud.addEventListener("click",(event)=>{const target=(event.target as HTMLElement).closest<HTMLElement>("button");if(!target||!state)return;if(target.dataset.digit!==undefined)dispatch({type:"SIGNAL_LOCK",index:Number(target.dataset.digit)});if(target.dataset.utility==="save"){dispatch({type:"MANUAL_SAVE"});toast("Match saved on this device.")}if(target.dataset.utility==="lab")showNumberLab();if(target.dataset.utility==="restart"){clearSave();state=null;hud.replaceChildren();showSetup()}if(target.dataset.portfolio==="trade"){const player=state.players[state.currentPlayer];const ventureId=Number(Object.keys(player.ventures)[0]);const targetPlayer=(state.currentPlayer+1)%state.players.length;if(Number.isFinite(ventureId))dispatch({type:"TRADE_VENTURE",ventureId,targetPlayer})}});
