"""Generate a north-up inspection map and a review queue without bundling basemap imagery."""
import json,math,html
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'public/geospatial'
geo=json.loads((ROOT/'src/detroit/cut-geospatial.json').read_text());city=json.loads((ROOT/'src/detroit/city-data.json').read_text())
ox,oz=geo['origin']['map']
def en(p):
    x,z=p[0]-ox,p[1]-oz;return [-.5*x-.8660254*z,-(.8660254*x-.5*z)]
def points(pts):return ' '.join(f'{x:.2f},{y:.2f}' for x,y in map(en,pts))
line=city['cut'];lengths=[0]
for a,b in zip(line,line[1:]):lengths.append(lengths[-1]+math.dist(a,b))
def point(d,u=0):
    i=next((i for i in range(1,len(line)) if lengths[i]>=d),len(line)-1);a,b=line[i-1:i+1];l=lengths[i]-lengths[i-1];t=max(0,min(1,(d-lengths[i-1])/l));return[a[0]+(b[0]-a[0])*t-(b[1]-a[1])/l*u,a[1]+(b[1]-a[1])*t+(b[0]-a[0])/l*u]
def near(p):
    result=1e9
    for a,b in zip(line,line[1:]):
        dx,dz=b[0]-a[0],b[1]-a[1];t=max(0,min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dz)/(dx*dx+dz*dz)));result=min(result,math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dz))
    return result
def gps(p):
    x,z=p;return [42.3283+(.8660254*x-.5*z)/111320,-83.0399+(-.5*x-.8660254*z)/(111320*math.cos(math.radians(42.3283)))]
def shape(name,pts,kind,source,polygon=False):
    center=[sum(p[i] for p in pts)/len(pts) for i in range(2)];lat,lon=gps(center)
    meta=html.escape(json.dumps(dict(name=name,source=source,lat=lat,lon=lon)),quote=True)
    return f'<{"polygon" if polygon else "polyline"} tabindex="0" class="feature {kind}" points="{points(pts)}" data-meta="{meta}"><title>{html.escape(name+" — "+source)}</title></{"polygon" if polygon else "polyline"}>'
layers=[]
roads=[r for r in city['roads'] if any(near(p)<230 for p in [r['points'][0],r['points'][-1]])]
layers.append('<g id="roads">'+''.join(shape(r['name'] or r['kind'],r['points'],'road','OSM road/path vertices') for r in roads)+'</g>')
buildings=json.loads((OUT/'runtime-buildings.json').read_text())
layers.append('<g id="buildings">'+''.join(shape(b['name'] or 'OSM building '+b['id'],b['points'],'building','OSM footprint; facade and height are approximations',True) for b in buildings)+'</g>')
layers.append('<g id="trail">'+shape('Dequindre Cut',line,'trail','87 mapped vertices; 2,629.24 m connected route')+'</g>')
layers.append('<g id="bridges">'+''.join(shape(b['name'],b['points'],'bridge',b['source']+'; deck elevation estimated',True) for b in geo['bridges'])+'</g>')
layers.append('<g id="ramps">'+''.join(shape(r['name'],r['points'],'ramp',r['source']+'; endpoint elevation interpolation') for r in geo['ramps'])+'</g>')
layers.append('<g id="walls">'+''.join(shape('Wall station '+str(w['at']),[point(w['at'],w['offset']),point(w['at']+7.8,w['offset'])],'wall',w['source']) for w in geo['walls'])+'</g>')
labels=[]
for b in geo['bridges']:
    x,y=en(point(b['at']));labels.append(f'<text x="{x+38}" y="{y-8}">{html.escape(b["name"])}</text>')
layers.append('<g id="labels">'+''.join(labels)+'</g><g id="origin"><circle cx="0" cy="0" r="13"/><path d="M-23 0H23M0-23V23"/></g>')
xy=list(map(en,line));bounds=[min(p[0] for p in xy)-180,min(p[1] for p in xy)-90,max(p[0] for p in xy)-min(p[0] for p in xy)+500,max(p[1] for p in xy)-min(p[1] for p in xy)+180]
svg='<svg xmlns="http://www.w3.org/2000/svg" id="map" role="img" aria-label="North-up map of the Dequindre Cut with mapped buildings, bridges, ramps and wall estimates" viewBox="'+ ' '.join(map(str,bounds))+'">'+''.join(layers)+'</svg>'
styles='''.feature{vector-effect:non-scaling-stroke;stroke-linejoin:round;fill:none;cursor:pointer}.feature:hover,.feature:focus{stroke:white;stroke-width:5;outline:none}.road{stroke:#526066;stroke-width:1}.building{stroke:#76c9a3;fill:#284338;stroke-width:1}.trail{stroke:#ffe287;stroke-width:4}.bridge{stroke:#ff9e63;fill:#74492f99;stroke-width:2}.ramp{stroke:#69e5ed;stroke-width:4}.wall{stroke:#df86f1;stroke-width:2;stroke-dasharray:4 2}#labels{fill:#b8c9c8;font:14px system-ui;pointer-events:none}#origin{fill:#fff;stroke:#fff;stroke-width:2;vector-effect:non-scaling-stroke;pointer-events:none}'''
(OUT/'dequindre-map-audit.svg').write_text(svg.replace('><g','><style>'+styles+'</style><g',1),encoding='utf-8')
sectors={b['name']:en(point(b['at'])) for b in geo['bridges']};sectors['Whole Cut']=None
html_doc='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dequindre Cut · Map audit</title><style>
:root{color-scheme:dark;font-family:system-ui;background:#0b1417;color:#dce8e4}*{box-sizing:border-box}body{margin:0}header{padding:22px 28px;border-bottom:1px solid #304347;display:flex;align-items:center;justify-content:space-between;gap:24px}h1{font-size:27px;letter-spacing:-1px;margin:3px 0}h2{font-size:15px;margin:22px 0 10px}p{font-size:13px;line-height:1.6;color:#acbfbc}.eyebrow{color:#cfdbaa;font-size:11px;letter-spacing:2px}a{color:#9ee2ce}main{display:grid;grid-template-columns:minmax(0,1fr) 310px;height:calc(100vh - 111px)}.viewport{position:relative;background:radial-gradient(ellipse at center,#18292e,#0f1b1e);overflow:hidden}svg{width:100%;height:100%;touch-action:none}aside{padding:0 22px 24px;overflow:auto;border-left:1px solid #304347}select,button,a.button{background:#223a3c;color:#e6f4ee;border:1px solid #49605d;border-radius:5px;padding:9px 11px;font:inherit;font-size:12px;cursor:pointer;text-decoration:none}nav{display:flex;gap:7px;align-items:center;flex-wrap:wrap}label{display:flex;align-items:center;gap:8px;margin:9px 0;font-size:13px}label span{width:18px;height:3px;background:var(--color)}.pill{border:1px solid #5c744b;color:#cee39e;border-radius:20px;padding:5px 9px;font-size:11px}.note{border-left:2px solid #dfaa60;padding-left:12px}.north{position:absolute;right:24px;top:18px;text-align:center;font-size:12px;line-height:1.8;color:#eef9ef}.scale{position:absolute;bottom:18px;left:24px;color:#dce8e4;font-size:11px}.scale b{display:block;border:1px solid #bacdca;border-top:0;height:7px;margin-bottom:5px}.zoom{position:absolute;top:18px;left:18px;display:flex;gap:6px}.small{font-size:11px}#detail{min-height:88px}#featureName{font-size:16px;margin:0 0 5px}#featureSource{margin:0}#status{font-size:11px;color:#9ab8b0}li{font-size:12px;line-height:1.6;margin:7px 0}@media(max-width:750px){header{padding:16px;display:block}nav{margin-top:10px}main{height:auto;display:block}.viewport{height:65vh}aside{border-left:0;padding:1px 18px 24px}}
STYLE
</style></head><body><header><div><div class="eyebrow">DIGITAL STATIC / GEOSPATIAL REVIEW</div><h1>Dequindre Cut.</h1></div><nav><a class="button" href="../detroit.html">Ride the level ↗</a><a class="button" href="dequindre-map-audit.kml" download>Satellite overlay · KML ↓</a><a class="button" href="dequindre-map-audit.svg" download>Map · SVG ↓</a></nav></header><main><div class="viewport">{{MAP_SVG}}<div class="zoom"><button id="plus" aria-label="Zoom in">+</button><button id="minus" aria-label="Zoom out">−</button><button id="reset">Whole Cut</button></div><div class="north">↑<br>NORTH</div><div class="scale"><b id="bar"></b><span id="scaleText">100 m</span><p class="small">Drag to pan · Scroll to zoom · Select a feature</p></div></div><aside><h2>Inspect a crossing</h2><select id="sector" aria-label="Map sector">OPTIONS</select><h2>Map layers</h2><div id="toggles"></div><h2>Selected feature</h2><div id="detail"><h3 id="featureName">Gratiot origin</h3><p id="featureSource">Game (0, 0, 0) is the trail center beneath Gratiot. One unit = one metre.</p><p id="gps">42.3472034, −83.0358912</p></div><nav><a id="satellite" class="button" target="_blank" rel="noopener">Google satellite ↗</a><a id="streetview" class="button" target="_blank" rel="noopener">Street View ↗</a></nav><h2>Validation</h2><span class="pill">11 overpasses + 3 ramps clear</span><p>Collision checks scan the entire Cut corridor and simulate an EUC passing beneath every mapped overpass.</p><p class="note">The KML overlay was opened over Google Earth satellite imagery on 14 September 2026. Gratiot ramp and crossing alignment were visually inspected. Numeric satellite residuals, roof-edge parallax and survey accuracy still need manual review. Import this KML through Google Earth → Local KML editor → Open from device.</p><h2>Corrections made</h2><ul><li>Added missing Jefferson, Larned, Chestnut and pedestrian crossings.</li><li>Removed false bridge structures at the at-grade Franklin and Woodbridge crossings.</li><li>Replaced generic bridge orientations with mapped footprints or road bearings.</li><li>Placed Lafayette, Gratiot and Wilkins ramps on their connected mapped paths.</li><li>Raised the northern trail toward Mack using 2013 design spot levels.</li><li>Moved Freight Yard containers toward the Alfred / Division area.</li></ul><p><a href="comparison.html">Open satellite review evidence and correction queue ↗</a></p><h2>Manual correction queue</h2>FLAGS<h2>Reference material</h2><p>Map data © OpenStreetMap contributors, ODbL 1.0, retrieved 14 Sep 2026. City of Detroit 2013 Phase II engineering plans. Historical Google Street View at Chestnut, August 2021.</p><p><a href="references.html">Open reference notes & source links ↗</a></p><p id="status"></p></aside></main><script>
const initial=BOUNDS,sectors=SECTORS,map=document.getElementById('map');let view=[...initial];
function render(){map.setAttribute('viewBox',view.join(' '));const factor=Math.min(map.clientWidth/view[2],map.clientHeight/view[3]);let metres=100;if(factor>2)metres=20;document.getElementById('bar').style.width=(metres*factor)+'px';document.getElementById('scaleText').textContent=metres+' m';}
function zoom(f){view=[view[0]+view[2]*(1-f)/2,view[1]+view[3]*(1-f)/2,view[2]*f,view[3]*f];render();}
document.getElementById('plus').onclick=()=>zoom(.7);document.getElementById('minus').onclick=()=>zoom(1/.7);document.getElementById('reset').onclick=()=>{view=[...initial];document.getElementById('sector').value='Whole Cut';render();};document.getElementById('sector').onchange=e=>{const p=sectors[e.target.value];view=p?[p[0]-220,p[1]-180,440,360]:[...initial];render();};
for(const [id,label,color] of [['roads','Street network','#78888c'],['buildings','Building footprints','#76c9a3'],['trail','Cut centerline','#ffe287'],['bridges','Overpass decks','#ff9e63'],['ramps','Entry ramps','#69e5ed'],['walls','Estimated walls','#df86f1'],['labels','Crossing names','#b8c9c8']]){const row=document.createElement('label');row.innerHTML='<input type="checkbox" checked data-layer="'+id+'"><span style="--color:'+color+'"></span>'+label;row.querySelector('input').onchange=e=>document.getElementById(id).style.display=e.target.checked?'':'none';document.getElementById('toggles').append(row);}
function links(lat,lon){document.getElementById('satellite').href='https://www.google.com/maps?q='+lat+','+lon+'&t=k&z=19';document.getElementById('streetview').href='https://www.google.com/maps/@?api=1&map_action=pano&viewpoint='+lat+','+lon;}
function select(el){const d=JSON.parse(el.dataset.meta);document.getElementById('featureName').textContent=d.name;document.getElementById('featureSource').textContent=d.source;document.getElementById('gps').textContent=d.lat.toFixed(7)+', '+d.lon.toFixed(7);links(d.lat,d.lon);}
let drag;map.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,view:[...view],target:e.target};map.setPointerCapture(e.pointerId);};map.onpointermove=e=>{if(!drag)return;const rect=map.getBoundingClientRect(),s=Math.max(view[2]/rect.width,view[3]/rect.height);view[0]=drag.view[0]-(e.clientX-drag.x)*s;view[1]=drag.view[1]-(e.clientY-drag.y)*s;render();};map.onpointerup=e=>{if(drag&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<4&&drag.target.dataset.meta)select(drag.target);drag=null;};map.onkeydown=e=>{if(e.key==='Enter'&&e.target.dataset.meta)select(e.target);};map.onwheel=e=>{e.preventDefault();zoom(e.deltaY>0?1.15:1/1.15);};window.onresize=render;links(42.347203364,-83.035891246);render();document.getElementById('status').textContent=document.querySelectorAll('.feature').length+' inspectable features · metre scale · north up';
</script></body></html>'''
flags=''.join('<p class="note"><strong>'+f['id']+'</strong> '+html.escape(f['detail'])+'</p>' for f in geo['reviewFlags'])
options='<option>Whole Cut</option>'+''.join('<option>'+html.escape(b['name'])+'</option>' for b in geo['bridges'])
for key,val in [('STYLE',styles),('{{MAP_SVG}}',svg),('OPTIONS',options),('FLAGS',flags),('BOUNDS',json.dumps(bounds)),('SECTORS',json.dumps(sectors))]:html_doc=html_doc.replace(key,val)
(OUT/'index.html').write_text(html_doc,encoding='utf-8')
print('Audit generated:',len(roads),'roads,',len(buildings),'buildings')

