import test from 'node:test';
import assert from 'node:assert/strict';
import {ArenaTerrain,SPAWNS,ZONE_CANDIDATES,route,clearGround,HANDSHAKE,compatible,ground} from '../src/royale/arena.ts';
import {RoyaleMatch,neutral,PROTECTION,DEADLINE,move} from '../src/royale/rules.ts';
import {RideController} from '../src/controller.ts';
const terrain=await ArenaTerrain.create();
function full(){const m=new RoyaleMatch(terrain);for(let i=0;i<6;i++)m.add('r'+i,'Rider '+i);m.start('test',1);return m;}
function place(m:RoyaleMatch,i:number,x:number,z:number,yaw=0){const a=m.actors[i];a.controller.reset({position:{x,y:ground(x,z).height,z},headingY:yaw});a.pose={...a.controller.poseValue};}
function advance(m:RoyaleMatch,n:number){for(let i=0;i<n;i++)m.step();}
test('six slots are mandatory and a seventh never becomes a combatant',()=>{const m=new RoyaleMatch(terrain);m.add('one','One');assert.throws(()=>m.start('a'));for(let i=0;i<5;i++)m.add('b'+i,'AI',true);assert.throws(()=>m.add('seven','Seven'));m.start('six');assert.equal(m.actors.length,6);});
test('handshake rejects any mismatched arena, rules, controller, protocol or collision version',()=>{assert(compatible(HANDSHAKE));for(const k of Object.keys(HANDSHAKE))assert(!compatible({...HANDSHAKE,[k]:'wrong'}));});
test('all six bays connect to every safe center with collision-clear wheel routes',()=>{for(const s of SPAWNS){assert(clearGround(s.position.x,s.position.z));for(const p of ZONE_CANDIDATES){const nodes=route(s.position,{...p,y:0},terrain);assert(nodes.length>3);for(let i=1;i<nodes.length;i++)assert(terrain.line({...nodes[i-1],y:nodes[i-1].y+.7},{...nodes[i],y:nodes[i].y+.7},.6));}}});
test('replay restores the entire controller motor and suspension state',()=>{const m=full(),a=m.actors[0],c={...neutral(m.round),throttle:1,steer:.12};for(let i=0;i<100;i++)move(a,c,i);const state=a.controller.captureState(),other=new RideController(terrain);other.restoreState(state);const b={controller:other,energy:a.energy,burstUntil:a.burstUntil,burstLatch:a.burstLatch};for(let i=100;i<180;i++){const input={...c,hop:i===110,hopHeld:i<110};move(a,input,i);move(b,input,i);}assert.deepEqual(other.captureState(),a.controller.captureState());});
test('reject nonfinite movement, extra claimed health, replay and sequence floods',()=>{const m=full(),c=neutral(m.round,1,m.tick);assert.equal(m.command('r0',{...c,throttle:NaN}),false);assert.equal(m.command('r0',{...c,integrity:999}),false);assert.equal(m.command('r0',{...c,seq:999}),false);assert(m.command('r0',c));assert(!m.command('r0',c));for(let i=2;i<=24;i++)assert(m.command('r0',{...c,seq:i}));assert(!m.command('r0',{...c,seq:25}));});
test('deployment cannot fire; active shots consume ammo and damage shield first',()=>{const m=full();place(m,0,0,0);place(m,1,0,7,Math.PI);m.command('r0',{...neutral(m.round,1,m.tick),fire:true,shot:1});m.step();assert.equal(m.projectiles.length,0);assert.equal(m.actors[0].ammo.static,80);advance(m,PROTECTION);m.command('r0',{...neutral(m.round,2,m.tick),fire:true,shot:2});advance(m,15);assert.equal(m.actors[0].ammo.static,79);assert.equal(m.actors[1].shield,30);assert.equal(m.actors[1].integrity,100);});
test('solid cover intercepts the complete projectile sweep',()=>{const m=full();advance(m,PROTECTION);place(m,0,28,5);place(m,1,28,39);m.command('r0',{...neutral(m.round,1,m.tick),fire:true,shot:1});advance(m,45);assert.equal(m.actors[1].shield,50);});
test('simultaneous lethal hits resolve as a draw and terminal state freezes',()=>{const m=full();advance(m,PROTECTION);for(let i=2;i<6;i++){m.actors[i].alive=false;m.actors[i].integrity=0;}place(m,0,0,0);place(m,1,0,8,Math.PI);for(let i=0;i<2;i++){m.actors[i].shield=0;m.actors[i].lastDamage=m.tick;m.actors[i].integrity=20;m.command('r'+i,{...neutral(m.round,1,m.tick),fire:true,shot:1});}advance(m,20);assert.equal(m.phase,'results');assert.equal(m.winner,null);assert.equal(m.projectiles.length,0);const frozen=JSON.stringify(m.snapshot('r0'));advance(m,100);assert.equal(JSON.stringify(m.snapshot('r0')),frozen);});
test('front shield prevents firing and repair is limited/cancelled by damage',()=>{const m=full();advance(m,PROTECTION);place(m,0,0,40);m.command('r0',{...neutral(m.round,1,m.tick),utility:true,fire:true,shot:1,repair:true});m.step();assert.equal(m.actors[0].ammo.static,80);assert.equal(m.actors[0].utility,0);assert.equal(m.actors[0].repairUntil,0);assert.equal(m.actors[0].repairs,0);});
test('reconnect keeps health, ammo, elimination and inventory; disconnect has no immunity',()=>{const m=full();advance(m,PROTECTION);const a=m.actors[0];a.integrity=32;a.ammo.static=11;m.disconnect(a.id);advance(m,15);m.reconnect(a.id);assert.equal(a.integrity,32);assert.equal(a.ammo.static,11);m.disconnect(a.id);advance(m,1202);assert(!a.alive);m.reconnect(a.id);assert(!a.alive);});
test('spectators get no live opponent coordinates or private controller states',()=>{const m=full();advance(m,PROTECTION);const s=m.snapshot();assert.equal(s.actors.length,0);assert.equal(s.projectiles.length,0);assert.equal(s.loot.length,0);assert.equal(s.self,undefined);assert.equal(s.roster.length,6);});
test('hard deadline terminates even riders together at the final center',()=>{const m=full();for(let i=0;i<6;i++)place(m,i,-12,0);m.tick=PROTECTION+DEADLINE-1;m.step();assert.equal(m.phase,'results');assert.equal(m.winner,null);});
test('released controls brake without reversing and recovery stays nearby without healing',()=>{
 const m=full();advance(m,PROTECTION);place(m,0,0,0);const a=m.actors[0];m.release(a.id);advance(m,180);assert(Math.abs(a.pose.speed)<.1);assert(Math.hypot(a.pose.x,a.pose.z)<.15);
 a.integrity=42;a.ammo.static=7;a.controller.crashed=true;
 m.command(a.id,{...neutral(m.round,1,m.tick),recover:true});m.step();assert(!a.controller.crashed);assert.equal(a.integrity,42);assert.equal(a.ammo.static,7);assert(Math.hypot(a.pose.x,a.pose.z)<1.21);
});
test('two full AI rounds terminate, move all six wheels and reset cleanly',()=>{
 const m=new RoyaleMatch(terrain);for(let i=0;i<6;i++)m.add('ai'+i,'AI',true);
 for(const seed of [0,3]){m.start('bots'+seed,seed);let frames=0;while(m.phase!=='results'&&frames++<PROTECTION+DEADLINE+1)m.step();assert.equal(m.phase,'results');assert(m.actors.every(a=>a.distance>30));assert(m.actors.filter(a=>a.alive).length<=1);assert(m.actors.every(a=>Number.isFinite(a.pose.x)&&Number.isFinite(a.pose.y)));assert.equal(m.projectiles.length,0);}
});
test.after(()=>terrain.dispose());
