import assert from 'node:assert/strict';import {readFile,writeFile} from 'node:fs/promises';import {Client} from '@colyseus/sdk';import {currentHandshake,initializeEngine} from '@digital-static/ridecore/royale';import {loadDowntown} from './downtown-fixture.mjs';
await initializeEngine(await readFile(new URL('../../ride-core/dist/engine/breadflower.wasm',import.meta.url)));const terrain=await loadDowntown(),options={handshake:currentHandshake(terrain.arenaIdentity),name:'Voice test',botFill:true};terrain.terrain.dispose();
const mode=process.env.VOICE_PRODUCT;let roomType='static-royale',roomOptions=options;if(mode){const {loadHostFixture}=await import('../dist/hostFixture.js');const {fileURLToPath}=await import('node:url');const {fixture}=await loadHostFixture(fileURLToPath(new URL('../fixtures/',import.meta.url)),mode);roomType='love-tag';roomOptions={product:mode,version:'heart-rush-1',hash:fixture.hash,ruleset:'classic',target:4,botFill:false,name:'Voice test'};}
const endpoint=process.env.ROYALE_TEST_URL??'http://127.0.0.1:8227',rooms=[];const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn){for(let i=0;i<100;i++){if(fn())return;await sleep(50);}throw Error('Voice test timeout');}
function watch(r){rooms.push(r);const s={r,roster:[],signals:[]};for(const type of ['welcome','lobby','snapshot','notice','host'])r.onMessage(type,()=>{});r.onMessage('voice-roster',v=>s.roster=v);r.onMessage('voice-signal',v=>s.signals.push(v));return s;}
try{
 const a=watch(await new Client(endpoint).create(roomType,roomOptions)),b=watch(await new Client(endpoint).joinById(a.r.roomId,roomOptions)),c=watch(await new Client(endpoint).joinById(a.r.roomId,roomOptions)),outside=watch(await new Client(endpoint).create(roomType,roomOptions));
 for(const s of [a,b,outside])s.r.send('voice-state',{enabled:true,channel:'all'});c.r.send('voice-state',{enabled:true,channel:'squad-a'});await until(()=>a.roster.length===3&&b.roster.length===3);
 const description={type:'offer',sdp:'v=0\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111\r\n'};a.r.send('voice-signal',{from:'spoof',to:b.r.sessionId,description});await until(()=>b.signals.length===1);assert.equal(b.signals[0].from,a.r.sessionId);assert.equal(b.signals[0].signal.to,b.r.sessionId);
 a.r.send('voice-signal',{to:c.r.sessionId,description});a.r.send('voice-signal',{to:outside.r.sessionId,description});a.r.send('voice-signal',{to:b.r.sessionId,description:{type:'offer',sdp:'m=video 9'}});await sleep(250);assert.equal(c.signals.length,0);assert.equal(outside.signals.length,0);assert.equal(b.signals.length,1);
 b.r.send('voice-state',{enabled:false,channel:'all'});await until(()=>a.roster.length===2);a.r.send('voice-signal',{to:b.r.sessionId,description});await sleep(150);assert.equal(b.signals.length,1);
 await writeFile('../docs/combat/evidence/voice-signaling-'+(mode??'royale')+'.json',JSON.stringify({at:new Date().toISOString(),server:endpoint,product:mode??'royale',automatedClients:4,rooms:2,canonicalSender:true,crossRoomBlocked:true,crossChannelBlocked:true,videoBlocked:true,leaveBlocked:true,humanAudioTest:false},null,2));console.log('PASS authenticated local voice routing, room/channel isolation, video rejection and leave cleanup');
}finally{for(const room of rooms)await room.leave();}
