import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHmac} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {AuctionEngine} from './engine.mjs';
import {auctionServer,validWebhook} from './server.mjs';
function fixture(){let now=1000000;const e=new AuctionEngine(':memory:',{clock:()=>now});return {e,set:n=>now=n};}
test('catalog includes every existing merch item, preserves prices, and claims no inventory',()=>{const {e}=fixture();try{const c=e.catalog();assert.equal(c.products.length,19);assert.ok(c.products.every(p=>p.stock===0&&p.availability==='awaiting_inventory'));assert.equal(c.state,'prelaunch');assert.equal(c.products.find(p=>p.id==='night-protocol-hoodie').reference_price_cents,10680);assert.equal(c.products.find(p=>p.id==='boogeyman-graphic-hoodie').reference_price_cents,null);}finally{e.close();}});
test('one bid deducts one credit; repeat network request cannot deduct a second credit',()=>{const {e}=fixture();try{const a=e.startTest('test:one'),id=randomUUID();e.bid('test:one',a.id,id);const retry=e.bid('test:one',a.id,id);assert.equal(retry.replayed,true);assert.equal(e.account('test:one','test').credits,19);assert.equal(e.catalog().auctions[0].price_cents,1);assert.equal(e.db.prepare('SELECT count(*) n FROM bids').get().n,1);assert.throws(()=>e.bid('test:one',a.id,randomUUID()),/ALREADY_HIGHEST_BIDDER/);assert.equal(e.account('test:one','test').credits,19);}finally{e.close();}});
test('late bid extends deadline; bid receipt never shortens original auction window',()=>{const {e,set}=fixture();try{const a=e.startTest('test:one');e.startTest('test:two');e.bid('test:one',a.id,randomUUID());assert.equal(e.catalog().auctions[0].ends_at,1030000);set(1029500);e.bid('test:two',a.id,randomUUID());assert.equal(e.catalog().auctions[0].ends_at,1039500);set(1039500);assert.throws(()=>e.bid('test:one',a.id,randomUUID()),/AUCTION_ENDED/);const c=e.catalog();assert.equal(c.auctions[0].state,'closed');assert.equal(e.account('test:two','test').orders[0].state,'test_result');assert.equal(e.account('test:one','test').orders.length,0);e.closeDue();assert.equal(e.account('test:two','test').orders.length,1);}finally{e.close();}});
test('insufficient credit rolls back bid, price, history and ledger',()=>{const {e}=fixture();try{const a=e.startTest('test:one');e.db.prepare("UPDATE wallets SET credits=0 WHERE user_id='test:one'").run();assert.throws(()=>e.bid('test:one',a.id,randomUUID()),/NO_BID_CREDITS/);assert.equal(e.catalog().auctions[0].price_cents,0);assert.equal(e.db.prepare('SELECT count(*) n FROM bids').get().n,0);assert.equal(e.db.prepare("SELECT count(*) n FROM ledger WHERE reason='bid'").get().n,0);}finally{e.close();}});
test('real auctions require explicit launch gates and verified, reserved stock',()=>{const e=new AuctionEngine(':memory:',{allowLive:true});try{assert.throws(()=>e.publish('night-protocol-hoodie'),/LAUNCH_REQUIREMENTS_PENDING/);e.db.exec('UPDATE settings SET processor_approved=1,fulfillment_ready=1,policy_ready=1');assert.throws(()=>e.publish('night-protocol-hoodie'),/VERIFIED_STOCK_REQUIRED/);e.verifyProduct('night-protocol-hoodie',{stock:1,retailCents:10680});e.publish('night-protocol-hoodie');assert.equal(e.db.prepare("SELECT stock FROM products WHERE id='night-protocol-hoodie'").get().stock,0);assert.throws(()=>e.publish('night-protocol-hoodie'),/VERIFIED_STOCK_REQUIRED/);}finally{e.close();}});
test('signed successful payments match a server quote and credit a wallet only once',()=>{const e=new AuctionEngine(':memory:',{allowLive:true});try{e.db.exec('UPDATE settings SET processor_approved=1,fulfillment_ready=1,policy_ready=1');const p=e.quotePurchase('verified-user',{kind:'bid_pack'}),event={eventId:'payment-1',purchaseId:p.id,amountCents:600,currency:'USD'};assert.throws(()=>e.paymentEvent({...event,amountCents:1}),/PAYMENT_MISMATCH/);assert.equal(e.account('verified-user','live').credits,0);e.paymentEvent(event);e.paymentEvent(event);e.paymentEvent({...event,eventId:'retry-other-id'});assert.equal(e.account('verified-user','live').credits,10);assert.equal(e.db.prepare("SELECT count(*) n FROM ledger WHERE reason='purchase'").get().n,1);const raw=JSON.stringify({...event,type:'payment.succeeded'}),now=Date.now(),stamp=String(now),sig='sha256='+createHmac('sha256','fixture-only-secret').update(stamp+'.'+raw).digest('hex');assert.equal(validWebhook(raw,stamp,sig,'fixture-only-secret',now),true);assert.equal(validWebhook(raw+' ',stamp,sig,'fixture-only-secret',now),false);assert.equal(validWebhook(raw,stamp,sig,'fixture-only-secret',now+300001),false);}finally{e.close();}});
test('auction state and account receipts survive backend restart',()=>{const directory=mkdtempSync(join(tmpdir(),'penny-test-')),path=join(directory,'test.sqlite');let e=new AuctionEngine(path);try{const a=e.startTest('test:persistence');e.bid('test:persistence',a.id,randomUUID());e.close();e=new AuctionEngine(path);assert.equal(e.account('test:persistence','test').credits,19);assert.equal(e.catalog().auctions[0].price_cents,1);}finally{e.close();rmSync(directory,{recursive:true,force:true});}});
test('tax-inclusive quotes reject unverified totals and match payment receipts',()=>{const e=new AuctionEngine(':memory:',{allowLive:true});try{e.db.exec('UPDATE settings SET processor_approved=1,fulfillment_ready=1,policy_ready=1');const p=e.quotePurchase('buyer',{kind:'bid_pack'});assert.throws(()=>e.acceptTaxQuote(p.id,{totalAmountCents:600,currency:'USD',taxCalculated:false}),/VALID_TAX_QUOTE_REQUIRED/);assert.throws(()=>e.acceptTaxQuote(p.id,{totalAmountCents:599,currency:'USD',taxCalculated:true}),/VALID_TAX_QUOTE_REQUIRED/);e.acceptTaxQuote(p.id,{totalAmountCents:636,currency:'USD',taxCalculated:true});assert.throws(()=>e.paymentEvent({eventId:'tax-1',purchaseId:p.id,amountCents:600,currency:'USD'}),/PAYMENT_MISMATCH/);e.paymentEvent({eventId:'tax-1',purchaseId:p.id,amountCents:636,currency:'USD'});assert.equal(e.account('buyer','live').credits,10);}finally{e.close();}});
test('fulfillment requires a paid winning order and tracking',()=>{let now=1000000;const e=new AuctionEngine(':memory:',{allowLive:true,clock:()=>now});try{e.db.exec('UPDATE settings SET processor_approved=1,fulfillment_ready=1,policy_ready=1');e.verifyProduct('night-protocol-hoodie',{stock:1,retailCents:10680,shippingCents:500});const auction=e.publish('night-protocol-hoodie',{model:'free',feeCents:0,durationMs:30000});e.bid('buyer',auction,randomUUID());now+=30001;const order=e.account('buyer','live').orders[0];assert.equal(order.state,'awaiting_payment');assert.throws(()=>e.shipOrder(order.id,'tracking-1'),/PAID_ORDER_REQUIRED/);const p=e.quotePurchase('buyer',{kind:'order',orderId:order.id});e.paymentEvent({eventId:'order-payment-1',purchaseId:p.id,amountCents:501,currency:'USD'});assert.throws(()=>e.shipOrder(order.id,''),/TRACKING_REQUIRED/);e.shipOrder(order.id,'tracking-1');assert.equal(e.account('buyer','live').orders[0].state,'shipped');}finally{e.close();}});
test('HTTP rejects unauthenticated bidding and foreign origins; local test uses the real engine',async()=>{const e=new AuctionEngine(':memory:'),server=auctionServer(e,{testEnabled:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,origin='http://127.0.0.1:4181';try{const catalog=await (await fetch(base+'/api/auctions',{headers:{Origin:origin}})).json();assert.equal(catalog.state,'prelaunch');assert.equal((await fetch(base+'/api/bids',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:'{}'})).status,401);assert.equal((await fetch(base+'/api/test-session',{method:'POST',headers:{Origin:'https://untrusted.example'}})).status,403);const s=await (await fetch(base+'/api/test-session',{method:'POST',headers:{Origin:origin}})).json();const b=await fetch(base+'/api/bids',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',Authorization:'Bearer '+s.token},body:JSON.stringify({auctionId:s.auction.id,requestId:randomUUID(),priceCents:9999,userId:'forged'})});assert.equal(b.status,200);const receipt=await b.json();assert.equal(receipt.credits,19);assert.equal(receipt.auctions[0].price_cents,1);assert.equal(receipt.auctions[0].leader.startsWith('Bidder '),true);}finally{await new Promise(r=>server.close(r));e.close();}});
