import {test} from 'node:test';
import assert from 'node:assert/strict';
import {actorTravelFraction} from './actorAvoidance.ts';
import {advanceCrowd,crowdObstacle,type CrowdAgent,type CrowdPath} from './crowdFlow.ts';
import {RideController,createPose,NEUTRAL_ACTIONS} from './controller.ts';
import {createGroundSample,type NavigationObstacle,type TerrainSampler} from './terrain.ts';
import {SplitRaceSimulation} from './splitRaceSimulation.ts';
import {routePosition} from './districtView.ts';
import {RACE_ROUTE} from './raceRules.ts';
const obstacle=(x=0,z=0):NavigationObstacle=>({id:'person',x,y:0,z,radius:.45,height:1.8,kind:'pedestrian',vx:0,vz:0});
const path:CrowdPath={length:1000,runout:180,point:(d,u)=>({x:u,y:0,z:d,heading:0}),width:()=>7};
const agent=(id:string,d:number,pace:number,dir=1,lane=1.65):CrowdAgent=>({id,distance:d,lane,direction:dir,pace,speed:pace,radius:.42,height:1.8,x:lane,y:0,z:d,heading:dir>0?0:Math.PI});
const flat:TerrainSampler={sampleGround(_x,_z,out){return Object.assign(out,createGroundSample());},raycast:()=>null,raycastObstacle:()=>null};
test('swept character envelopes cannot tunnel through a person at high speed',()=>{assert.ok(actorTravelFraction({x:0,y:0,z:-5},0,12,.48,2.1,[obstacle()])<.4);assert.equal(actorTravelFraction({x:2,y:0,z:-5},0,12,.48,2.1,[obstacle()]),1);assert.equal(actorTravelFraction({x:0,y:3,z:-5},0,12,.48,2.1,[obstacle()]),1);});
test('initial overlap permits escape but never movement deeper into another actor',()=>{assert.equal(actorTravelFraction({x:.5,y:0,z:0},.1,0,.48,2.1,[obstacle()]),1);assert.equal(actorTravelFraction({x:.5,y:0,z:0},-.1,0,.48,2.1,[obstacle()]),0);});
test('walkers pass a stationary rider with a smooth detour and keep their direction',()=>{const people=[agent('walker',0,1.1)],hero=obstacle(1.65,8);let maxStep=0,minGap=Infinity,heading=0;for(let i=0;i<900;i++){const before={...people[0]};advanceCrowd(people,1/30,path,[hero]);const a=people[0];maxStep=Math.max(maxStep,Math.hypot(a.x-before.x,a.z-before.z));minGap=Math.min(minGap,Math.hypot(a.x-hero.x,a.z-hero.z));assert.ok(a.distance>=before.distance);assert.ok(Math.abs(a.heading-heading)<=.051);heading=a.heading;}assert.ok(people[0].distance>22,JSON.stringify(people));assert.ok(minGap>.9);assert.ok(maxStep<.06);});
test('a faster jogger overtakes a walker without intersecting or reversing',()=>{const people=[agent('walker',7,1.1),agent('runner',0,3.2)];let min=Infinity;for(let i=0;i<1200;i++){const previous=people.map(a=>a.distance);advanceCrowd(people,1/30,path,[]);min=Math.min(min,Math.hypot(people[0].x-people[1].x,people[0].z-people[1].z));assert.ok(people.every((a,j)=>a.distance>=previous[j]));}assert.ok(people[1].distance>people[0].distance+10,JSON.stringify(people));assert.ok(min>.89);});
test('opposing pedestrians choose passing space and do not pass through one another',()=>{const people=[agent('a',0,1.1,1,0),agent('b',15,1.1,-1,0)];let min=Infinity;for(let i=0;i<750;i++){advanceCrowd(people,1/30,path,[]);min=Math.min(min,Math.hypot(people[0].x-people[1].x,people[0].z-people[1].z));}assert.ok(people[0].z>people[1].z);assert.ok(min>.89);});
test('crowd yields to a full blocked path rather than intersecting it',()=>{const people=[agent('a',-2,1.1)],wall={...obstacle(0,5),radius:5};for(let i=0;i<600;i++)advanceCrowd(people,1/30,path,[wall]);assert.ok(Math.hypot(people[0].x-wall.x,people[0].z-wall.z)>=5.48);});
test('player impact stops the root at the walker and enters a fall',()=>{const blocker=obstacle(0,5),terrain={...flat,navigationObstacles:()=>[blocker]},sim=new RideController(terrain,{spawn:{position:{x:0,y:0,z:0},headingY:0}}),pose=createPose();for(let i=0;i<600;i++){sim.step(1/120,{...NEUTRAL_ACTIONS,throttle:1});sim.writePose(pose);assert.ok(Math.hypot(pose.x-blocker.x,pose.z-blocker.z)>.98);}assert.ok(pose.z>3);assert.equal(sim.crashed,true);assert.ok(Math.abs(pose.speed)<.01);});
test('two controlled local riders have solid envelopes, not ghost overlap',()=>{const room=new SplitRaceSimulation(flat,['DS_Man_01','DS_Hoodie_Woman_01']);room.rules.advance(3);const p=routePosition(RACE_ROUTE.start);room.riders[0].sim.reset({position:{...p,y:0},headingY:p.heading});room.riders[1].sim.reset({position:{x:p.x+Math.sin(p.heading)*5,y:0,z:p.z+Math.cos(p.heading)*5},headingY:p.heading});room.riders.forEach(r=>r.sim.writePose(r.pose));let min=Infinity;for(let i=0;i<800;i++){room.step(1/120,[{...NEUTRAL_ACTIONS,throttle:1},NEUTRAL_ACTIONS]);const[a,b]=room.riders;min=Math.min(min,Math.hypot(a.pose.x-b.pose.x,a.pose.z-b.pose.z));}assert.ok(min>1,`gap ${min}`);assert.equal(room.riders[0].sim.crashed,true);assert.equal(room.riders[1].sim.crashed,true);});
test('zero time freezes crowd poses and passing reservations',()=>{const people=[agent('a',0,1.1)],before=JSON.stringify(people);advanceCrowd(people,0,path,[crowdObstacle(agent('b',2,0))]);assert.equal(JSON.stringify(people),before);});

test('mapped left-positive offsets choose the same physical passing side as right-positive paths',()=>{const mirrored={...path,offsetSign:-1,point:(d:number,u:number)=>({x:-u,y:0,z:d,heading:0})},walker=agent('mapped',0,1.1),hero=obstacle(-1.65,8);walker.x=-walker.lane;let min=Infinity;for(let i=0;i<900;i++){advanceCrowd([walker],1/30,mirrored,[hero]);min=Math.min(min,Math.hypot(walker.x-hero.x,walker.z-hero.z));}assert.ok(walker.distance>22);assert.ok(min>.9);});

test('passing candidates reject steep or missing shoulders',()=>{const people=[agent('a',0,1.1)],hero=obstacle(1.65,8),restricted={...path,walkable:(x:number)=>x<2};for(let i=0;i<900;i++){advanceCrowd(people,1/30,restricted,[hero]);assert.ok(people[0].x<2);}assert.ok(people[0].distance>22);});
