import * as T from 'three';
import {toMap} from './geo-profile.ts';
import './arcadeCabinets.css';
type GameId='wave'|'rahbe'|'underground';
type Cabinet={id:GameId;name:string;url:string;root:T.Group;sticks:T.Group[];buttons:T.Mesh[];screen:T.Mesh;normal:T.Vector3;centre:T.Vector3};
const paths={wave:'../../../opengw-levels/index.html',rahbe:'../robot-rahbe-vault-rush/index.html',underground:'../robot-rahbe-underground/index.html'};
const mapping={KeyA:'a',KeyD:'d',KeyW:'w',KeyS:'s',ArrowLeft:'ArrowLeft',ArrowRight:'ArrowRight',ArrowUp:'ArrowUp',ArrowDown:'ArrowDown',KeyJ:'j',KeyL:'l',KeyI:'i',ShiftLeft:'Shift',Space:' ',KeyE:'e',KeyK:'k',Enter:'Enter',Escape:'Escape'} as Record<string,string>;
export class ArcadeCabinets{
 readonly panel=document.createElement('details');private frame=document.createElement('iframe');private active?:Cabinet;private cabinets:Cabinet[]=[];private previousFov=55;private lastControl="ready";private held=new Set<string>();private drag?:{pointer:number;stick:number;x:number;y:number};private ray=new T.Raycaster();private camera?:T.PerspectiveCamera;private banner=document.createElement('p');private controls=document.createElement('div');
 constructor(private canvas:HTMLCanvasElement,private enter:()=>void,private leave:()=>void){
  this.panel.className='cabinet-console';this.panel.hidden=true;this.panel.setAttribute('aria-label','Playable arcade cabinets');const heading=document.createElement('summary');heading.textContent='Arcade · free play';this.banner.textContent='Choose a cabinet';this.controls.className='cabinet-controls';this.panel.append(heading,this.banner,this.controls);document.body.append(this.panel);
  this.frame.className='cabinet-game';this.frame.hidden=true;this.frame.allow="autoplay 'none'";this.frame.title='Arcade cabinet game';document.body.append(this.frame);
  this.frame.onload=()=>{if(!this.active)return;this.banner.textContent=this.active.name+' · Start / Resume, then drag the ball tops. Left moves, right aims in 2084.';};
  const start=document.createElement('button');start.textContent='Start / Resume';start.onclick=()=>{const d=this.frame.contentDocument,b=d?.querySelector<HTMLButtonElement>('#primaryAction, #start');if(b&&!b.disabled)b.click();else{this.send('Enter',true);this.send('Enter',false);}this.canvas.focus();};const exit=document.createElement('button');exit.textContent='Leave cabinet';exit.onclick=()=>this.close();this.controls.append(start,exit);
  const directions=document.createElement('div');directions.className='cabinet-directions';for(const [label,code]of [['Move left','KeyA'],['Move up','KeyW'],['Move down','KeyS'],['Move right','KeyD'],['Action / fire','KeyJ'],['Jump / bomb','Space'],['Use','KeyE'],['Dash','KeyK']]as const){const b=document.createElement('button');b.textContent=label;b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);this.send(code,true);this.animateHeld();};const release=()=>{this.send(code,false);this.animateHeld();};b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release;b.onkeydown=e=>{if(e.code==='Enter'||e.code==='Space'){e.preventDefault();this.send(code,true);this.animateHeld();}};b.onkeyup=e=>{if(e.code==='Enter'||e.code==='Space'){e.preventDefault();release();}};b.onblur=release;directions.append(b);}this.controls.append(directions);
  this.panel.addEventListener('keydown',e=>e.stopPropagation());
  for(const type of ['keydown','keyup']as const)window.addEventListener(type,e=>{if(!this.active||e.code==='Tab')return;if(e.code!=='Escape'&&(e.target as HTMLElement)?.closest?.('.cabinet-console'))return;if(!mapping[e.code]&&e.code!=='Escape')return;e.stopImmediatePropagation();e.preventDefault();if(e.code==='Escape'&&type==='keydown'){this.close();return;}if(mapping[e.code]){this.send(e.code,type==='keydown');this.animateHeld();}},true);
  this.canvas.addEventListener('pointerdown',e=>{if(!this.active||!this.camera)return;e.preventDefault();e.stopImmediatePropagation();const r=this.canvas.getBoundingClientRect();this.ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),this.camera);const hits=this.ray.intersectObjects([...this.active.sticks.flatMap(s=>s.children),...this.active.buttons],true);const hit=hits[0];if(!hit)return;const index=this.active.sticks.findIndex(s=>hit.object===s||hit.object.parent===s);this.canvas.setPointerCapture(e.pointerId);if(index>=0){this.lastControl='3D joystick '+(index===1?'aim':'move');this.drag={pointer:e.pointerId,stick:index,x:e.clientX,y:e.clientY};}else{this.lastControl='3D pushbutton';const n=this.active.buttons.indexOf(hit.object as T.Mesh);this.send(n===0?'KeyJ':'Space',true);this.active.buttons[n].position.y=.997;}},true);
  this.canvas.addEventListener('pointermove',e=>{if(!this.active||!this.drag||this.drag.pointer!==e.pointerId)return;e.stopImmediatePropagation();const x=T.MathUtils.clamp((e.clientX-this.drag.x)/36,-1,1),y=T.MathUtils.clamp((e.clientY-this.drag.y)/36,-1,1),codes=this.drag.stick===1?['KeyJ','KeyL','KeyI','KeyK']:['KeyA','KeyD','KeyW','KeyS'];[x<-.25,x>.25,y<-.25,y>.25].forEach((down,i)=>this.send(codes[i],down));this.active.sticks[this.drag.stick].rotation.set(y*.30,0,-x*.30);},true);
  for(const event of ['pointerup','pointercancel','lostpointercapture'])this.canvas.addEventListener(event,()=>{if(this.active){this.release();this.drag=undefined;this.animateHeld();}},true);
  window.addEventListener('blur',()=>this.release());document.addEventListener('visibilitychange',()=>{if(document.hidden&&this.active)this.close();});
 }
 add(building:T.Object3D,u:number,v:number,angle:number,id:GameId,name:string){
  const root=new T.Group();root.position.set(u,0,v);root.rotation.y=angle;building.add(root);root.updateWorldMatrix(true,false);
  const poster=document.createElement('canvas');poster.width=512;poster.height=288;const ink=poster.getContext('2d')!;ink.fillStyle='#081a18';ink.fillRect(0,0,512,288);ink.fillStyle='#d6efbf';ink.font='bold 28px sans-serif';ink.textAlign='center';ink.fillText(name.includes('Underground')?'RAHBE: Underground':name,256,105);ink.font='22px sans-serif';ink.fillText('PRESS PLAY / FREE PLAY',256,182);const idle=new T.CanvasTexture(poster);idle.colorSpace=T.SRGBColorSpace;const screen=new T.Mesh(new T.PlaneGeometry(.64,.36),new T.MeshBasicMaterial({map:idle,toneMapped:false}));screen.position.set(0,1.345,.306);root.add(screen);
  const sticks:T.Group[]=[];for(const x of id==='wave'?[-.20,.20]:[-.20]){const s=new T.Group();s.position.set(x,1.028,.37);const shaft=new T.Mesh(new T.CylinderGeometry(.014,.014,.13,12),new T.MeshStandardMaterial({color:'#abbaba',metalness:.8,roughness:.3}));shaft.position.y=.055;const knob=new T.Mesh(new T.SphereGeometry(.049,16,12),new T.MeshStandardMaterial({color:x>0?'#c5da5a':'#d12e49',roughness:.4}));knob.position.y=.135;s.add(shaft,knob);root.add(s);sticks.push(s);}
  const buttons:T.Mesh[]=[];for(const [index,x] of (id==='wave'?[-.045,.065]:[.12,.27]).entries()){const button=new T.Mesh(new T.CylinderGeometry(.038,.04,.025,16),new T.MeshStandardMaterial({color:index===0?'#e9ca66':'#436cff',roughness:.4}));button.position.set(x,1.038,.37);root.add(button);buttons.push(button);}
  const gameUrl=new URL(paths[id],location.href);gameUrl.searchParams.set('cabinet','1');const c:Cabinet={id,name,url:gameUrl.href,root,sticks,buttons,screen,normal:new T.Vector3(),centre:new T.Vector3()};this.cabinets.push(c);const play=document.createElement('button');play.textContent='Play '+name;play.className='cabinet-choice';play.onclick=()=>this.open(c);this.panel.insertBefore(play,this.controls);
 }
 private open(c:Cabinet){if(!this.active)this.previousFov=this.camera?.fov??55;this.release();this.active=c;this.lastControl="ready";this.enter();this.frame.hidden=false;this.frame.title=c.name+' cabinet screen';this.frame.src=c.url;this.panel.classList.add('active');this.panel.open=true;this.canvas.focus();}
 private close(){this.release();this.drag=undefined;this.animateHeld();if(this.active?.sticks[1])this.active.sticks[1].rotation.set(0,0,0);this.active=undefined;this.frame.hidden=true;this.frame.src='about:blank';this.panel.classList.remove('active');if(this.camera){this.camera.fov=this.previousFov;this.camera.updateProjectionMatrix();}this.leave();}
 private send(code:string,down:boolean){if(!this.active)return;if(down===this.held.has(code))return;down?this.held.add(code):this.held.delete(code);if(down)this.lastControl=this.lastControl.split(' · ')[0]+' · '+code;const win=this.frame.contentWindow;try{if(win&&this.frame.contentDocument){const EventType=(win as unknown as {KeyboardEvent:typeof KeyboardEvent}).KeyboardEvent;this.frame.contentDocument.body.dispatchEvent(new EventType(down?'keydown':'keyup',{code,key:mapping[code]??code,bubbles:true,cancelable:true,repeat:false}));}}catch{this.banner.textContent='Use the game screen controls for this cabinet.';}}
 private release(){for(const code of [...this.held])this.send(code,false);}
 private animateHeld(){if(!this.active)return;const x=Number(this.held.has('KeyD'))-Number(this.held.has('KeyA')),y=Number(this.held.has('KeyS'))-Number(this.held.has('KeyW'));this.active.sticks[0].rotation.set(y*.3,0,-x*.3);this.active.buttons.forEach((b,i)=>b.position.y=this.held.has(i===0?'KeyJ':'Space')?.997:1.038);}
 stop(){if(this.active)this.close();}
 get playing(){return Boolean(this.active);}
 update(x:number,z:number,visible:boolean,camera:T.PerspectiveCamera){
  this.camera=camera;const near=this.cabinets.filter(c=>{c.root.getWorldPosition(c.centre);return Math.hypot(x-c.centre.x,z-c.centre.z)<4.8;});this.panel.hidden=!this.active&&(!visible||near.length===0);this.panel.querySelectorAll<HTMLButtonElement>('.cabinet-choice').forEach((b,i)=>b.hidden=Boolean(this.active)||!near.includes(this.cabinets[i]));this.controls.hidden=!this.active;
  if(!this.active){this.banner.textContent='Pick a cabinet · original games · free play';return;}const c=this.active;c.root.updateWorldMatrix(true,true);c.screen.getWorldPosition(c.centre);c.normal.set(0,0,1).transformDirection(c.root.matrixWorld);camera.position.copy(c.centre).addScaledVector(c.normal,1.35);camera.lookAt(c.centre);camera.fov=T.MathUtils.clamp(T.MathUtils.radToDeg(2*Math.atan(Math.tan(T.MathUtils.degToRad(52/2))/camera.aspect)),50,105);camera.updateProjectionMatrix();camera.updateMatrixWorld();
  const points=[new T.Vector3(-.32,.18,.308),new T.Vector3(.32,-.18,.308)].map(p=>p.add(new T.Vector3(0,1.345,0)).applyMatrix4(c.root.matrixWorld).project(camera));const rect=this.canvas.getBoundingClientRect(),xs=points.map(p=>(p.x*.5+.5)*rect.width+rect.left),ys=points.map(p=>(-p.y*.5+.5)*rect.height+rect.top);Object.assign(this.frame.style,{left:Math.min(...xs)+'px',top:Math.min(...ys)+'px',width:Math.abs(xs[1]-xs[0])+'px',height:Math.abs(ys[1]-ys[0])+'px'});this.canvas.dataset.cabinet=JSON.stringify({game:c.id,name:c.name,held:[...this.held],lastControl:this.lastControl});
  // DOM iframe is the live screen. Parent canvas exports include the cabinet,
  // while each original game retains its own rendering and keyboard/touch input.
  const map=toMap(c.centre.x,0,c.centre.z);this.panel.dataset.location=JSON.stringify(map);
 }
}
