export type BlockingShot={start:number;end:number;aspect:'16:9'|'9:16'|'1:1';guides:boolean;notes:string;camera:string;subject:string};
export type BlockingSample={time:number;sourceTime:number;camera:{position:number[];quaternion:number[];fov:number;aspect:number};actors:{name:string;position:number[];quaternion:number[];scale:number[]}[]};
export const BLOCKING_LIMIT=30;
export function validateShot(shot:BlockingShot,duration:number){
 if(!Number.isFinite(shot.start)||!Number.isFinite(shot.end)||shot.start<0||shot.end>duration+.001)throw Error('Choose a range inside the recorded clip.');
 const length=shot.end-shot.start;if(length<3-.001||length>BLOCKING_LIMIT+.001)throw Error('Choose a shot between 3 and 30 seconds.');
 return length;
}
export function blockingSize(aspect:BlockingShot['aspect']){return aspect==='9:16'?{width:720,height:1280}:aspect==='1:1'?{width:960,height:960}:{width:1280,height:720};}
export function blockingMime(supports:(mime:string)=>boolean){return ['video/mp4;codecs=avc1.42001E','video/mp4','video/webm;codecs=vp8','video/webm'].find(supports);}
export function blockingFiles(game:string,shot:BlockingShot,videoName:string,samples:BlockingSample[],stills:{file:string;time:number}[]){
 const size=blockingSize(shot.aspect),duration=shot.end-shot.start;
 const prompt=`Use the supplied game footage as a staging and movement reference for ${game}. Preserve the subject's route, speed, screen direction, camera movement, framing and scene layout. Keep the rider and their vehicle consistent between frames. ${samples.some(s=>s.actors.some(a=>a.name.startsWith('Companion')))?'Keep the companion a muscular short-coated Boerboel with a short docked tail. ':''}Replace game rendering with polished cinematic detail. Do not reproduce interface text, guide labels or timestamps.\n\nCreative direction: ${shot.notes.trim()||'Natural lighting, grounded proportions, believable materials and smooth physical movement.'}\n\nShot: ${duration.toFixed(2)} seconds, ${shot.aspect}, ${shot.camera} camera, subject ${shot.subject}.\n`;
 const manifest={format:'digital-static-blocking',version:1,game,units:'metres',coordinates:'Three.js scene coordinates, right-handed, Y up; quaternion order x,y,z,w. Local game origin, not GPS.',sourceRange:{start:shot.start,end:shot.end},duration,video:{file:videoName,...size,audio:false,guides:shot.guides,timing:'Real-time browser capture; sample times record rendered frames, not a guaranteed constant simulation rate.'},cameraMode:shot.camera,subject:shot.subject,notes:shot.notes,referenceImages:stills,sampleRateTarget:10,samples,limitations:['Scenery and bystanders are not rewound.','JSON is a portable shot description, not a Higgsfield project or direct import format.','Generated AI motion and camera matching are not guaranteed.']};
 const csv=['time_seconds,source_seconds,camera_x,camera_y,camera_z,camera_qx,camera_qy,camera_qz,camera_qw,fov,aspect',...samples.map(s=>[s.time,s.sourceTime,...s.camera.position,...s.camera.quaternion,s.camera.fov,s.camera.aspect].join(','))].join('\n');
 const readme=`# ${game} — Higgsfield reference pack\n\n1. Extract this ZIP. Preview ${videoName} and the three JPG reference images.\n2. In Higgsfield choose a workflow that accepts a motion/reference video, such as Motion Control. Upload the video and a character or scene reference image in the appropriate slots. A generated or real character image may produce a better result than the game still.\n3. Paste and adjust prompt.txt. Review the selected model's current input limits, settings and credit cost before generating. No upload or paid job is started by this game.\n\nThe clean JPGs show the start, middle and end of this shot. blocking.json and camera.csv document the camera and actor placements for planning, Blender scripts or other tools. They are not native Higgsfield import files. The JSON has actor root transforms, not a skinned animation or full 3D scene.\n\n${videoName.endsWith('.webm')?'This browser exported WebM. If the chosen Higgsfield model requires MP4, convert locally with an installed FFmpeg:\n\n    ffmpeg -i '+videoName+' -c:v libx264 -pix_fmt yuv420p -movflags +faststart -an blocking.mp4\n\nDo not just rename the extension.\n':'This browser exported MP4. Verify the selected Higgsfield model accepts its codec and duration.\n'}\nVideo has no sound or game HUD. ${shot.guides?'Guide labels and timecode were requested; choose Clean reference for AI inputs without annotations.':'Clean reference was selected.'} Framing uses a dedicated camera aspect ratio, so the rider stays in view without stretching the image.\n\nRecording range: ${shot.start.toFixed(2)}–${shot.end.toFixed(2)} seconds. Scenery and bystanders are not rewound. Each export is limited to 30 seconds and 40 MiB of video for mobile memory use. Keep this tab visible until export finishes.\n\nHiggsfield reference documentation (checked 2026-09-29):\nhttps://open.higgsfield.ai/models/kling-video/v3/motion-control/pro/api-reference\n`;
 return {'blocking.json':JSON.stringify(manifest,null,2),'camera.csv':csv,'prompt.txt':prompt,'README.md':readme};
}
