import {test} from 'node:test';
import assert from 'node:assert/strict';
import {SurfaceParticles,effectSurface,containsPatch,landingResponse,ConfirmationState,type EffectPatch} from './effectRules.ts';
import {RideController,createPose,NEUTRAL_ACTIONS} from './controller.ts';
import {createGroundSample,type TerrainSampler} from './terrain.ts';
const flat:TerrainSampler={sampleGround(_x,_z,o){o.height=0;o.normal={x:0,y:1,z:0};o.surface='pavement';o.offCourse=false;return o;},raycast:()=>null,raycastObstacle:()=>null};
function drive(kind='pavement',options:{wet?:boolean;leaves?:boolean;grounded?:boolean;crash?:boolean;reduced?:boolean}={}){const fx=new SurfaceParticles(),p=createPose(),g=createGroundSample();g.surface=kind as typeof g.surface;p.speed=6;p.velocityZ=6;p.crashBlend=options.crash?1:0;for(let i=0;i<240;i++){p.z+=.05;fx.step(1/120,p,g,options.grounded!==false,!!options.wet,!!options.leaves,!!options.reduced);}return {fx,p,g};}
test('dry asphalt and grass never produce a continuous smoke trail',()=>{for(const s of ['pavement','brick','grass','wood'])assert.deepEqual(drive(s).fx.emitted,{dust:0,spray:0,leaf:0,landings:0});});
test('dirt and gravel have short sparse tire bursts, not permanent clouds',()=>{for(const s of ['dirt','gravel']){const {fx,p,g}=drive(s);assert.ok(fx.emitted.dust>=20&&fx.emitted.dust<44);assert.ok(fx.state.live<=12);p.speed=0;for(let i=0;i<120;i++)fx.step(1/120,p,g,true,false,false);assert.equal(fx.state.live,0);}});
test('wet patch crossing sprays and ripples while dry asphalt stays dry',()=>{const {fx,p,g}=drive('pavement',{wet:true});assert.ok(fx.emitted.spray>0);assert.ok(fx.state.ripples>0);const count=fx.emitted.spray;for(let i=0;i<120;i++){p.z+=.05;fx.step(1/120,p,g,true,false,false);}assert.equal(fx.emitted.spray,count);assert.equal(fx.state.live,0);assert.equal(fx.state.ripples,0);});
test('only selected leaf areas disturb leaves',()=>{assert.ok(drive('grass',{leaves:true}).fx.emitted.leaf>0);assert.equal(drive('grass').fx.emitted.leaf,0);});
test('airborne, crashed, stationary, teleporting and reduced-motion riders emit nothing',()=>{for(const options of [{grounded:false},{crash:true},{reduced:true}])assert.equal(drive('gravel',options).fx.emitted.dust,0);const fx=new SurfaceParticles(),p=createPose(),g=createGroundSample();g.surface='dirt';p.speed=10;fx.step(.1,p,g,true,false,false);fx.step(.1,p,g,true,false,false);p.x=100;fx.step(.1,p,g,true,false,false);assert.equal(fx.state.live,0);});
test('particle state freezes on pause, remains bounded and resets on recovery',()=>{const {fx,p,g}=drive('gravel');const before=JSON.stringify(fx.particles);fx.step(0,p,g,true,false,false);assert.equal(JSON.stringify(fx.particles),before);for(let i=0;i<150;i++)fx.land(p,g,true,8);assert.ok(fx.state.live<=96);assert.ok(fx.state.ripples<=6);fx.reset();assert.equal(fx.state.live+fx.state.ripples,0);});
test('landing response scales with impact and surface, rejecting false contact',()=>{assert.ok(landingResponse(5,'dirt',false).count>landingResponse(2,'dirt',false).count);assert.ok(landingResponse(5,'dirt',false).count>landingResponse(5,'pavement',false).count);assert.equal(landingResponse(.4,'dirt',false).count,0);assert.equal(landingResponse(5,'pavement',true).kind,'spray');const fx=new SurfaceParticles(),p=createPose(),g=createGroundSample();p.y=1;fx.land(p,g,false,5);p.y=0;p.crashBlend=1;fx.land(p,g,false,5);p.crashBlend=0;g.offCourse=true;fx.land(p,g,false,5);assert.equal(fx.emitted.landings,0);});
test('actual RideController hop emits one touchdown event and preserves suspension',()=>{const sim=new RideController(flat),p=createPose(),fx=new SurfaceParticles(),g=createGroundSample();let contacts=0,compression=0;for(let i=0;i<360;i++){sim.step(1/120,{...NEUTRAL_ACTIONS,hop:i===30});sim.writePose(p);fx.step(1/120,p,g,sim.snapshot().grounded,false,false);if(sim.touchedDown){contacts++;fx.land(p,g,false,sim.lastLandingImpact);}compression=Math.max(compression,p.landingCompression);}assert.equal(contacts,1);assert.equal(fx.emitted.landings,1);assert.ok(compression>.05);assert.equal(fx.state.live,0);});
test('rotated authored footprint is the only wet region and does not alter terrain type',()=>{const patch:EffectPatch={id:'wet',kind:'wet',x:10,z:20,rx:1,rz:3,heading:Math.PI/2};assert.ok(containsPatch(patch,12,20));assert.ok(!containsPatch(patch,10,22));assert.deepEqual(effectSurface([patch],12,20,'pavement'),{wet:true,leaves:false,surface:'pavement'});assert.equal(effectSurface([patch],10,22,'pavement').wet,false);});
test('confirmation appears once per earned event, expires in simulation time and resets',()=>{const c=new ConfirmationState();assert.ok(c.show('checkpoint','Gate 1','gate:1'));c.step(.5);assert.equal(c.show('checkpoint','Gate 1','gate:1'),false);assert.equal(c.remaining,1.3);c.step(0);assert.equal(c.remaining,1.3);c.step(2);assert.equal(c.remaining,0);assert.ok(c.show('trick','Clean hop','hop:2'));c.reset();assert.equal(c.remaining,0);assert.ok(c.show('checkpoint','Gate 1','gate:1'));});
