import * as T from 'three';
import {GLTFLoader} from './compressedGLTFLoader.ts';
import {toLocal,toMap} from './geo-profile.ts';
import {LOTTO_SHOP,lottoMap,lottoCoordinates,LOTTO_OFFICIAL_URL,LOTTO_FIXTURES,LOTTO_WALLS,lottoToolsAvailable,practiceNumbers,validPracticePick} from './lottoShopSite.ts';
import type {DetroitWorld} from './world.ts';
import {storefrontDetails} from './storefrontDetails.ts';
import {LottoAppDesk} from './lottoAppDesk.ts';
import './lottoShop.css';
export async function buildLottoShop(scene:T.Scene,world:DetroitWorld,focus:()=>void,appOpened:()=>void=focus,appClosed:()=>void=focus){
 const building=(await new GLTFLoader().loadAsync('/exports/atwater/lottomind-store.glb?v=street-entry-20261003')).scene;building.name='LottoMind Mack Avenue virtual store';const at=toLocal(LOTTO_SHOP.x,LOTTO_SHOP.floor,LOTTO_SHOP.z);building.position.set(at.x,at.y,at.z);building.rotation.y=LOTTO_SHOP.heading;scene.add(building);building.traverse(o=>{const mesh=o as T.Mesh;if(mesh.isMesh){mesh.receiveShadow=true;const materials=Array.isArray(mesh.material)?mesh.material:[mesh.material];mesh.castShadow=!materials.some(m=>m.transparent);}});
 function solid(u:number,v:number,w:number,h:number,d:number,y=h/2){const p=lottoMap(u,v);world.addBox({x:p.x,y:LOTTO_SHOP.floor+y,z:p.z,hx:w/2,hy:h/2,hz:d/2,yaw:-LOTTO_SHOP.heading,kind:'LottoMind shop'});}
 for(const p of LOTTO_WALLS)solid(p.u,p.v,p.width,p.height,p.depth,p.y);for(const p of LOTTO_FIXTURES)solid(p.u,p.v,p.width,p.height,p.depth);
 const corners=[[-6.7,-9.4],[-6.7,9.4],[6.7,9.4],[6.7,-9.4]].map(([u,v])=>lottoMap(u,v));world.addRideSurface(new Float32Array([0,2,1,0,3,2].flatMap(i=>[corners[i].x,LOTTO_SHOP.floor+.068,corners[i].z])),true);
 const glass=new T.MeshPhysicalMaterial({color:0xe5eee4,transparent:true,opacity:.10,roughness:.17,metalness:.10,depthWrite:false,side:T.DoubleSide});for(const u of [-4.05,4.05]){const pane=new T.Mesh(new T.PlaneGeometry(5.15,2.85),glass);pane.position.set(u,1.58,9.48);building.add(pane);}
 for(const u of [-3.5,3.5]){const light=new T.PointLight(0xffecd0,55,15,2);light.position.set(u,3.75,0);building.add(light);}
 await storefrontDetails(building,world,true);
 const panel=document.createElement('details');panel.className='lotto-shop';panel.hidden=true;panel.setAttribute('aria-label','LottoMind store');const summary=document.createElement('summary');summary.setAttribute('aria-label','Open LottoMind store tools');const icon=document.createElement('span');icon.className='lotto-shop-icon';icon.textContent='LM';icon.setAttribute('aria-hidden','true');const title=document.createElement('span');title.className='lotto-shop-title';title.textContent='LottoMind';const subtitle=document.createElement('small');subtitle.textContent='Store tools · tap to open';title.append(subtitle);summary.append(icon,title);const name=document.createElement('strong');name.textContent='LOTTOMIND / MACK AVENUE';
 const desk=new LottoAppDesk(panel,appOpened,appClosed),home=document.createElement('div');home.className='lotto-shop-home';const official=document.createElement('a');official.href=LOTTO_OFFICIAL_URL;official.target='_blank';official.rel='noopener noreferrer';official.textContent='Real tickets · official Michigan Lottery';const note=document.createElement('p');note.textContent='Virtual LottoMind store. Local tools have no wagers, real tickets or prizes. LottoMind numbers do not predict lottery results.';home.append(desk.toolsLaunch,desk.launch,official,note);
 const selected=document.createElement('p');selected.setAttribute('role','status');selected.textContent='Pick six numbers · 1–47';const grid=document.createElement('div');grid.className='lotto-picks';grid.setAttribute('role','group');grid.setAttribute('aria-label','Practice lottery numbers');const picks=new Set<number>(),buttons:HTMLButtonElement[]=[];
 const refresh=()=>{buttons.forEach((b,i)=>{const on=picks.has(i+1);b.setAttribute('aria-pressed',String(on));b.disabled=!on&&picks.size===6;});selected.textContent=picks.size===6?'Practice ticket · '+[...picks].sort((a,b)=>a-b).join(' · '):`Choose ${6-picks.size} more numbers`;draw.disabled=picks.size!==6;};
 for(let n=1;n<=47;n++){const b=document.createElement('button');b.textContent=String(n);b.setAttribute('aria-label','Practice number '+n);b.setAttribute('aria-pressed','false');b.onclick=()=>{focus();if(picks.has(n))picks.delete(n);else if(picks.size<6)picks.add(n);refresh();};buttons.push(b);grid.append(b);}
 const easy=document.createElement('button');easy.textContent='Quick practice pick';easy.onclick=()=>{focus();picks.clear();practiceNumbers(()=>crypto.getRandomValues(new Uint32Array(1))[0]/4294967296).forEach(n=>picks.add(n));refresh();};const draw=document.createElement('button');draw.textContent='Run practice draw';draw.disabled=true;const result=document.createElement('p');result.setAttribute('role','status');draw.onclick=()=>{focus();if(!validPracticePick([...picks]))return;const numbers=practiceNumbers(()=>crypto.getRandomValues(new Uint32Array(1))[0]/4294967296),matches=numbers.filter(n=>picks.has(n));result.textContent=`Practice draw: ${numbers.join(' · ')}. ${matches.length} matched${matches.length?' ('+matches.join(', ')+')':''}. No real ticket or prize.`;};
 const clear=document.createElement('button');clear.textContent='Clear ticket';clear.onclick=()=>{picks.clear();refresh();result.textContent='';};const practice=document.createElement('details');practice.className='lotto-practice';const practiceSummary=document.createElement('summary');practiceSummary.textContent='Practice number desk';practice.append(practiceSummary,selected,easy,grid,draw,clear,result);panel.append(summary,name,home,desk.view,practice);panel.addEventListener('keydown',e=>e.stopPropagation());document.body.append(panel);
 return{building,panel,get appActive(){return desk.active;},closeApp(){desk.close();},open(){panel.open=true;},update(x:number,z:number,visible:boolean){const m=toMap(x,0,z),p=lottoCoordinates(m.x,m.z);building.visible=Math.hypot(m.x-LOTTO_SHOP.x,m.z-LOTTO_SHOP.z)<250;panel.hidden=!visible||!lottoToolsAvailable(p.u,p.v);if(panel.hidden){desk.close(false);panel.open=false;}}};
}
