import {ONLINE_CONFIG} from './onlineConfig.ts';
import './pennyAuction.css';
import {photographyCollection} from './photographyExhibition.ts';
type Product={id:string;name:string;brand:string;source_url:string;kind:string;availability:string;image:string;reference_price_cents:number|null;concept:number};
type Auction={id:string;product_id:string;mode:'test'|'live';model:'paid'|'free';state:string;price_cents:number;ends_at:number;reset_ms:number;leader:string|null;bid_fee_cents:number;history:{bidder:string;price_cents:number;at:number}[]};
type Catalog={serverTime:number;state:string;products:Product[];auctions:Auction[];testEnabled:boolean};
type Account={credits:number;orders:{id:string;state:string;price_cents:number;shipping_cents:number;auction_id:string}[]};
const money=(c:number)=>(c/100).toLocaleString('en-US',{style:'currency',currency:'USD'});
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const apiBase=()=>['127.0.0.1','localhost'].includes(location.hostname)?location.origin+'/__penny':new URL('./exports/polish/penny-service.json',location.href).href;

export class PennyAuction {
 readonly panel=document.createElement('dialog');private status=document.createElement('p');private products=document.createElement('div');private activeAuctions=document.createElement('div');private credits=document.createElement('div');private test=document.createElement('button');private signOut=document.createElement('button');private account?:Account;private catalog?:Catalog;private token='';private base='';private timer?:number;private busy=false;private offset=0;private renderKey='';private pending=new Map<string,string>();private returnTo?:HTMLElement;
 private productQuery='';private matches=document.createElement('p');
 constructor(private entered:()=>void,private left:()=>void){
  this.panel.className='penny-desk';this.panel.setAttribute('aria-label','Penny Exchange auction desk');
  const header=document.createElement('header');header.innerHTML='<div><p class="penny-eyebrow">MACK AVENUE / NEXT TO LOTTOMIND</p><h1>Penny Exchange</h1></div>';const close=document.createElement('button');close.textContent='Back to ride';close.onclick=()=>this.close();header.append(close);
  const content=document.createElement('div');content.className='penny-content';content.innerHTML='<div class="penny-intro"><div><h2>Find your Detroit favorite.</h2><p>Hoodies, hats, shirts, key charms and the full GothTech collection.</p></div></div><div class="penny-service">Practice mode · no money charged, no products awarded.</div><ol class="penny-steps"><li><span>1</span><div><strong>Browse</strong><p>Look at the merch below.</p></div></li><li><span>2</span><div><strong>Try a bid</strong><p>Tap the big bid button.</p></div></li><li><span>3</span><div><strong>Watch the clock</strong><p>The last bid leads when time ends.</p></div></li></ol>';
  this.credits.className='penny-credits';this.credits.textContent='No active session';content.querySelector('.penny-intro')!.append(this.credits);this.products.className='penny-products';
  const training=document.createElement('section');training.className='penny-test';training.innerHTML='<h2>Learn with a free practice auction</h2><p>Each tap uses one practice credit and adds 1¢ to the price. Start with 20 free credits. This is a test: no payment and no product prize.</p>';
  this.test.textContent='▶ Start free practice · 20 test credits';this.test.hidden=true;this.test.onclick=()=>void this.testSession();training.append(this.test);this.activeAuctions.className='penny-auctions';
  this.status.className='penny-status';this.status.setAttribute('role','status');this.signOut.textContent='Sign out of auction desk';this.signOut.hidden=true;this.signOut.onclick=()=>{this.token='';this.account=undefined;sessionStorage.removeItem('penny-auction.auth.v1');this.render();this.status.textContent='Signed out.';};
  const login=document.createElement('form');login.className='penny-login';login.innerHTML='<label>Auction account email<input name="email" type="email" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button type="submit">Sign in to auction account</button>';login.onsubmit=e=>{e.preventDefault();void this.signIn(login);};
  const note=document.createElement('p');note.className='penny-notice';note.textContent='Existing GothTechnology merchandise images and reference prices are preserved. Concept artwork and catalog drafts do not establish sale inventory. Confirm garment sizes, quantities and fulfillment before opening real lots. Auction credits are separate from your LottoMind lottery wallet. Test auctions charge nothing and award no products.';
  const accountDetails=document.createElement('details');accountDetails.className='penny-account';const accountSummary=document.createElement('summary');accountSummary.textContent='Already have an auction account? Sign in';accountDetails.append(accountSummary,login,this.signOut);
  const browse=document.createElement('section');browse.className='penny-browse';const title=document.createElement('h2');title.textContent='Browse all GothTech merch';const label=document.createElement('label');label.textContent='Find a hoodie, hat, shirt or charm';const search=document.createElement('input');search.type='search';search.placeholder='Search the collection';search.oninput=()=>{this.productQuery=search.value.trim().toLowerCase();this.render();};label.append(search);this.matches.className='penny-matches';this.matches.setAttribute('role','status');browse.append(title,label,this.matches,this.products);
  content.append(photographyCollection(),training,this.activeAuctions,this.status,browse,accountDetails,note);this.panel.append(header,content);this.panel.addEventListener('cancel',e=>{e.preventDefault();this.close();});this.panel.addEventListener('keydown',e=>e.stopPropagation());document.body.append(this.panel);
 }
 get active(){return this.panel.open;}
 async open(){if(this.active)return;this.returnTo=document.activeElement as HTMLElement;this.entered();this.panel.showModal();this.status.textContent='Connecting to auction desk…';
  try{const candidate=apiBase();if(candidate.endsWith('.json')){const response=await fetch(candidate,{cache:'no-store'});if(!response.ok)throw Error('Auction service is not published yet. The showroom is available locally.');const c=await response.json();if(typeof c.apiBase!=='string'||!c.apiBase)throw Error('Auction service is not published yet. The showroom is available locally.');const url=new URL(c.apiBase);if(url.protocol!=='https:')throw Error('Auction service requires HTTPS.');this.base=url.href.replace(/\/$/,'');}else this.base=candidate;
   this.token=sessionStorage.getItem('penny-auction.auth.v1')??'';await this.refresh();this.status.textContent='Ready. Start free practice, or browse the merch below.';this.timer=window.setInterval(()=>{void this.refresh(true);},1000);
  }catch(e){this.status.textContent=e instanceof Error?e.message:'Auction service is unavailable.';}
 }
 close(){if(!this.active)return;if(this.timer)clearInterval(this.timer);this.renderKey='';this.timer=undefined;this.panel.close();this.left();this.returnTo?.focus();}
 private async request(path:string,data?:unknown){const r=await fetch(this.base+path,{method:data?'POST':'GET',headers:{...(data?{'Content-Type':'application/json'}:{}),...(this.token?{Authorization:'Bearer '+this.token}:{})},body:data?JSON.stringify(data):undefined,signal:AbortSignal.timeout(6000),cache:'no-store'});const reply=await r.json();if(!r.ok)throw Error(({SIGN_IN_REQUIRED:'Sign in before bidding.',AUCTION_ENDED:'This auction has closed.',ALREADY_HIGHEST_BIDDER:'You are already the highest bidder.',NO_BID_CREDITS:'No bid credits remain.',REAL_BIDDING_NOT_OPEN:'Real-money bidding is not open.',SLOW_DOWN:'Please wait a moment before trying again.'} as Record<string,string>)[reply.error]??'Auction desk: '+reply.error);return reply;}
 private async refresh(quiet=false){if(this.busy||!this.active)return;try{const c:Catalog=await this.request('/api/auctions');if(!this.active)return;this.catalog=c;this.offset=c.serverTime-Date.now();if(this.token){try{this.account=await this.request('/api/account');}catch(e){this.token='';this.account=undefined;sessionStorage.removeItem('penny-auction.auth.v1');throw e;}}this.render();}catch(e){if(this.active)this.status.textContent=(quiet?'Connection interrupted. Bidding waits for the server. ':'')+(e instanceof Error?e.message:'Service unavailable.');this.activeAuctions.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=true);}}
 private async signIn(form:HTMLFormElement){this.busy=true;try{const fields=new FormData(form);const r=await fetch(ONLINE_CONFIG.url+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:ONLINE_CONFIG.key,'Content-Type':'application/json'},body:JSON.stringify({email:fields.get('email'),password:fields.get('password')})});const reply=await r.json();if(!r.ok||!reply.access_token)throw Error('Sign-in failed. Check your auction account details.');this.token=reply.access_token;sessionStorage.setItem('penny-auction.auth.v1',this.token);form.reset();this.status.textContent='Signed in. Real bidding and checkout remain closed during prelaunch.';}catch(e){this.status.textContent=e instanceof Error?e.message:'Unable to sign in.';}finally{this.busy=false;await this.refresh();}}
 private async testSession(){this.busy=true;this.test.disabled=true;try{const reply=await this.request('/api/test-session',{});if(!this.active)return;this.token=reply.token;this.account=reply;sessionStorage.setItem('penny-auction.auth.v1',this.token);this.status.textContent='TEST AUCTION · no payment, no product award. Your bids use free test credits.';}catch(e){this.status.textContent=e instanceof Error?e.message:'Test session unavailable.';}finally{this.busy=false;this.test.disabled=false;await this.refresh();}}
 private async bid(auction:Auction,button:HTMLButtonElement){if(this.busy)return;this.busy=true;button.disabled=true;const requestId=this.pending.get(auction.id)??crypto.randomUUID();this.pending.set(auction.id,requestId);try{const reply=await this.request('/api/bids',{auctionId:auction.id,requestId});this.pending.delete(auction.id);if(!this.active)return;this.account=reply;this.catalog=reply;this.offset=reply.serverTime-Date.now();this.render();this.status.textContent=auction.mode==='test'?'Test bid accepted and saved by the server.':'Bid accepted and recorded.';}catch(e){this.status.textContent=e instanceof Error?e.message:'Bid was not confirmed. Check the history before retrying.';}finally{this.busy=false;await this.refresh();}}
 private async checkout(kind:'bid_pack'|'order',orderId?:string){if(this.busy)return;this.busy=true;try{const reply=await this.request('/api/checkout',{kind,orderId});const url=new URL(reply.checkoutUrl);if(url.protocol!=='https:')throw Error('Checkout is unavailable.');const link=document.createElement('a');link.href=url.href;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Continue to secure checkout ↗';this.status.replaceChildren(link);}catch(e){this.status.textContent=e instanceof Error?e.message:'Checkout is unavailable.';}finally{this.busy=false;}}
 private render(){const c=this.catalog;if(!c)return;this.panel.querySelector('.penny-service')!.textContent=c.state==='ready'?'Auctions are open · read the fees and terms before bidding.':'Prelaunch showroom · real-money bidding and checkout are closed.';this.test.hidden=!c.testEnabled;this.signOut.hidden=!this.token;this.credits.textContent=this.account?this.account.credits+(this.token.length===64?' test credits':' bid credits'):'Try a free practice auction';
  const key=JSON.stringify({products:c.products,auctions:c.auctions,account:this.account,token:!!this.token,busy:this.busy,query:this.productQuery});if(key===this.renderKey){for(const clock of this.activeAuctions.querySelectorAll<HTMLElement>('[data-auction-clock]'))clock.textContent=Math.max(0,Math.ceil((Number(clock.dataset.auctionClock)-Date.now()-this.offset)/1000))+'s remaining';return;}this.renderKey=key;
  const found=c.products.filter(p=>(p.name+' '+p.kind).toLowerCase().includes(this.productQuery));this.matches.textContent=found.length+' of '+c.products.length+' items'+(found.length?'':' � Try another search');this.products.innerHTML=found.map(p=>`<article class="penny-product"><div class="penny-product-visual"><img src="${escape(new URL('./exports/boutique/'+p.image,location.href).href)}" alt="${escape(p.name)} · existing store reference artwork" loading="lazy"></div><div class="penny-product-copy"><small>${escape(p.brand)} / ${escape(p.kind)}</small><h3>${escape(p.name)}</h3><p>${p.reference_price_cents===null?'Price pending':money(p.reference_price_cents)+' · store reference price'}</p><div class="penny-tag">${p.availability==='verified_inventory'?'INVENTORY VERIFIED':'CATALOG DRAFT / STOCK UNCONFIRMED'}${p.concept?' · CONCEPT ARTWORK':''}</div><a href="${escape(p.source_url)}" target="_blank" rel="noopener noreferrer">View GothTechnology product ↗</a></div></article>`).join('');
  this.activeAuctions.replaceChildren();if(this.token&&c.state==='ready'){const pack=document.createElement('button');pack.textContent='Purchase 10 bids · $6 before tax';pack.onclick=()=>void this.checkout('bid_pack');this.activeAuctions.append(pack);}
for(const a of c.auctions.filter(a=>a.state==='live'||a.mode==='test').slice(0,4)){const p=c.products.find(p=>p.id===a.product_id),card=document.createElement('section');card.className='penny-auction';const remaining=Math.max(0,Math.ceil((a.ends_at-Date.now()-this.offset)/1000));card.innerHTML=`<div>${p?`<img class="penny-auction-image" src="${escape(new URL('./exports/boutique/'+p.image,location.href).href)}" alt="${escape(p.name)}">`:''}<p class="penny-eyebrow">${a.mode==='test'?'TEST AUCTION / NO PRODUCT AWARD':'PRODUCT AUCTION'}</p><h3>${escape(p?.name??'Product')}</h3><p class="penny-price">${money(a.price_cents)}</p><p class="penny-clock" ${a.state==='live'?'data-auction-clock="'+a.ends_at+'"':''}>${a.state==='live'?remaining+'s remaining':'Closed'}</p><p>${escape(a.leader??'No bids recorded')}</p><p class="penny-notice">Each bid adds 1¢. ${a.mode==='test'?'Uses one free test credit.':a.model==='paid'?'One paid bid is spent whether you win or lose.':'Bids are free; the winner pays the final price.'} A late bid extends the clock to at least ${a.reset_ms/1000}s.</p></div><div><strong>Recorded bids</strong><ol class="penny-history">${a.history.length?a.history.map(b=>`<li>${escape(b.bidder)} · ${money(b.price_cents)}</li>`).join(''):'<li>No bids yet.</li>'}</ol></div>`;const button=document.createElement('button');button.textContent=a.mode==='test'?'Place test bid · +1¢':'Bid +1¢';button.disabled=!this.token||a.state!=='live'||this.busy||a.mode==='live'&&c.state!=='ready';button.onclick=()=>void this.bid(a,button);card.firstElementChild!.append(button);this.activeAuctions.append(card);}
  if(this.account?.orders.length){const orders=document.createElement('div');orders.className='penny-orders';orders.innerHTML='<h3>Your results</h3>'+this.account.orders.map(o=>`<p>${o.state==='test_result'?'Test result saved · no product awarded':escape(o.state)} · ${money(o.price_cents)}</p>`).join('');for(const order of this.account.orders.filter(o=>o.state==='awaiting_payment')){const pay=document.createElement('button');pay.textContent='Checkout winning lot · '+money(order.price_cents+order.shipping_cents)+' before tax';pay.disabled=c.state!=='ready';pay.onclick=()=>void this.checkout('order',order.id);orders.append(pay);}this.activeAuctions.append(orders);}
 }
}
