import * as T from 'three';
import {studioCoordinates} from './mackStudioSite.ts';
import {toMap} from './geo-profile.ts';
import {STUDIO_SCREEN_WALLS,MOVIE_PROGRAMS,PUBLIC_LIVE_STREAM,streamUrl,mediaBadge} from './mediaSources.ts';
import './studioScreens.css';
type HlsPlayer={autoLevelCapping:number;loadSource(url:string):void;attachMedia(video:HTMLVideoElement):void;startLoad(position?:number):void;stopLoad():void;destroy():void;on(event:string,callback:(_event:string,data:{fatal?:boolean;details?:{live?:boolean}})=>void):void};
type HlsConstructor={new(config:Record<string,unknown>):HlsPlayer;isSupported():boolean;Events:{MANIFEST_PARSED:string;LEVEL_LOADED:string;ERROR:string}};
type WallPlayer={video:HTMLVideoElement;mesh:T.Mesh;texture:T.VideoTexture;idle:T.CanvasTexture;status:HTMLParagraphElement;play:HTMLButtonElement;sound:HTMLButtonElement;hls?:HlsPlayer;live:boolean;ready:boolean;generation:number;request:boolean;url:string;name:string;objectUrl?:string};
/** Two true WebGL video surfaces. Network/decoding starts only on a Play gesture. */
export class StudioScreens{
 readonly panel=document.createElement('details');private players:WallPlayer[]=[];private available=false;private playlist=document.createElement('select');private cycle=document.createElement('input');
 constructor(building:T.Object3D,private focus:()=>void){
  this.panel.className='studio-screens';this.panel.hidden=true;this.panel.setAttribute('aria-label','Studio wall screens');const summary=document.createElement('summary');summary.textContent='Wall screens · movies + live';this.panel.append(summary);
  const title=['CINEMA / COMMERCIALS','PUBLIC LIVE STREAM'];
  for(const [i,wall]of STUDIO_SCREEN_WALLS.entries()){
   const section=document.createElement('section'),heading=document.createElement('strong');heading.textContent=title[i];const status=document.createElement('p');status.setAttribute('role','status');status.textContent=i?'Public live demo · Mux timer + movie loop':'City in Motion · Detroit mini movie · press Play';
   const video=document.createElement('video');video.playsInline=true;video.muted=true;video.crossOrigin='anonymous';video.preload='none';video.hidden=true;video.setAttribute('aria-label',i?'Live wall video':'Cinema wall video');
   const idleCanvas=document.createElement('canvas');idleCanvas.width=1280;idleCanvas.height=720;const c=idleCanvas.getContext('2d')!;c.fillStyle='#091c1a';c.fillRect(0,0,1280,720);c.strokeStyle='#b79d56';c.lineWidth=5;c.strokeRect(28,28,1224,664);c.fillStyle='#dece93';c.font='28px sans-serif';c.fillText('GOTHTECH  /  2000 MACK',80,125);c.fillStyle='#f0efe2';c.font='bold 64px sans-serif';c.fillText(i?'STREAM WALL':'CINEMA WALL',80,310);c.font='30px sans-serif';c.fillStyle='#b9ccbd';c.fillText(i?'Public live demo · or connect your HLS stream':'City in Motion / Detroit mini movie',80,385);c.fillText('Press Play in Wall screens',80,565);
   const idle=new T.CanvasTexture(idleCanvas);idle.colorSpace=T.SRGBColorSpace;const texture=new T.VideoTexture(video);texture.colorSpace=T.SRGBColorSpace;const mesh=new T.Mesh(new T.PlaneGeometry(wall.width,wall.height),new T.MeshBasicMaterial({map:idle,toneMapped:false}));mesh.name=wall.id+' wall playback';mesh.position.set(wall.u,wall.y,wall.v);mesh.rotation.y=wall.angle;building.add(mesh);
   const play=document.createElement('button'),sound=document.createElement('button');play.textContent=i?'Play live stream':'Play cinema';sound.textContent='Sound off';sound.setAttribute('aria-label',i?'Live screen sound':'Cinema screen sound');sound.setAttribute('aria-pressed','false');
   const p:WallPlayer={video,mesh,texture,idle,status,play,sound,live:false,ready:false,generation:0,request:false,url:i?PUBLIC_LIVE_STREAM:MOVIE_PROGRAMS[0].url,name:i?'Public live demo · Mux':MOVIE_PROGRAMS[0].name};this.players.push(p);
   play.onclick=()=>{this.focus();if(!video.paused){p.request=false;video.pause();p.hls?.stopLoad();}else{p.request=true;if(p.ready){p.hls?.startLoad(-1);void video.play().catch(()=>this.fail(p,'Playback needs another tap.'));}else void this.load(p);}};
   sound.onclick=()=>{video.muted=!video.muted;if(!video.muted)for(const other of this.players)if(other!==p){other.video.muted=true;this.refresh(other);}this.refresh(p);};
   video.onplaying=()=>{p.mesh.material=(p.mesh.material as T.MeshBasicMaterial);(p.mesh.material as T.MeshBasicMaterial).map=texture;(p.mesh.material as T.MeshBasicMaterial).needsUpdate=true;this.refresh(p);};video.onpause=()=>this.refresh(p);video.onwaiting=()=>{status.textContent='Buffering · '+p.name;};video.onerror=()=>this.fail(p,'Media unavailable. Choose another source or Retry.');
   video.onended=()=>{if(i===0&&this.cycle.checked&&!p.objectUrl){this.playlist.selectedIndex=(this.playlist.selectedIndex+1)%MOVIE_PROGRAMS.length;this.chooseMovie();p.request=true;void this.load(p);}else if(i===0){video.currentTime=0;if(p.request)void video.play().catch(()=>this.fail(p,'Press Play to restart.'));}};
   const actions=document.createElement('div');actions.className='screen-actions';actions.append(play,sound);section.append(heading,status,actions,video);this.panel.append(section);
   if(i===0){this.playlist.setAttribute('aria-label','Cinema program');for(const [n,item]of MOVIE_PROGRAMS.entries())this.playlist.add(new Option(item.name,String(n)));this.playlist.onchange=()=>this.chooseMovie();const cycleLabel=document.createElement('label');this.cycle.type='checkbox';this.cycle.checked=false;cycleLabel.append(this.cycle,' Rotate commercials + movie');const file=document.createElement('input');file.type='file';file.accept='video/mp4,video/webm';file.setAttribute('aria-label','Play your local movie');file.onchange=()=>{const selected=file.files?.[0];if(!selected)return;this.reset(p);p.objectUrl=URL.createObjectURL(selected);p.url=p.objectUrl;p.name=selected.name;p.status.textContent='Local movie ready · press Play';};const credit=document.createElement('small');credit.className='screen-credit';credit.textContent=MOVIE_PROGRAMS[0].credit;section.append(this.playlist,cycleLabel,file,credit);}
   else{const input=document.createElement('input');input.type='url';input.placeholder='https://…/live.m3u8';input.setAttribute('aria-label','Direct live stream URL');const connect=document.createElement('button');connect.textContent='Use stream URL';connect.onclick=()=>{const url=streamUrl(input.value);if(!url){status.textContent='Use a direct HTTPS .m3u8, .mp4 or .webm URL. The host must allow cross-origin video.';return;}this.reset(p);p.url=url;p.name='Your stream';status.textContent='Stream ready · press Play';};const restore=document.createElement('button');restore.textContent='Public live demo';restore.onclick=()=>{this.reset(p);p.url=PUBLIC_LIVE_STREAM;p.name='Public live demo · Mux';status.textContent='Public live demo ready · press Play';};const note=document.createElement('small');note.textContent='Public live demo broadcasts a movie loop and clock. Live status comes from the stream playlist.';section.append(input,connect,restore,note);}
  }
  this.panel.addEventListener('keydown',e=>e.stopPropagation());this.panel.addEventListener('pointerdown',()=>this.focus());document.body.append(this.panel);document.addEventListener('visibilitychange',()=>{if(document.hidden)this.suspend();});window.addEventListener('pagehide',()=>this.players.forEach(p=>this.reset(p)));
 }
 private chooseMovie(){const p=this.players[0],item=MOVIE_PROGRAMS[this.playlist.selectedIndex];this.reset(p);p.url=item.url;p.name=item.name;p.status.textContent='Ready · '+item.name;this.panel.querySelector('.screen-credit')!.textContent=item.credit;}
 private reset(p:WallPlayer){p.generation++;p.request=false;p.video.pause();p.hls?.destroy();p.hls=undefined;p.video.removeAttribute('src');p.video.load();if(p.objectUrl)URL.revokeObjectURL(p.objectUrl);p.objectUrl=undefined;p.live=false;p.ready=false;(p.mesh.material as T.MeshBasicMaterial).map=p.idle;(p.mesh.material as T.MeshBasicMaterial).needsUpdate=true;this.refresh(p);}
 private fail(p:WallPlayer,message:string){p.request=false;p.video.pause();p.hls?.stopLoad();p.ready=false;p.play.textContent=p===this.players[0]?'Retry cinema':'Retry stream';p.status.textContent=message;}
 private async load(p:WallPlayer){
  const generation=++p.generation;p.hls?.destroy();p.hls=undefined;p.status.textContent='Connecting · '+p.name;p.live=false;
  try{if(/\.m3u8(?:\?|$)/i.test(p.url)&&!p.video.canPlayType('application/vnd.apple.mpegurl')){
   const Hls=(await import('../vendor/hls.light.mjs')).default as HlsConstructor;if(generation!==p.generation||!p.request||!this.available)return;if(!Hls.isSupported())throw Error('HLS unsupported');const hls=new Hls({enableWorker:true,maxBufferLength:15,maxMaxBufferLength:30,maxBufferSize:20*1024*1024,autoStartLoad:true});hls.autoLevelCapping=2;p.hls=hls;
   hls.on(Hls.Events.LEVEL_LOADED,(_e,data)=>{if(generation!==p.generation)return;p.live=Boolean(data.details?.live);this.refresh(p);});hls.on(Hls.Events.ERROR,(_e,data)=>{if(data.fatal&&generation===p.generation)this.fail(p,'Stream unavailable · Retry or use another URL.');});hls.on(Hls.Events.MANIFEST_PARSED,()=>{if(generation!==p.generation)return;p.ready=true;if(p.request&&this.available)void p.video.play().catch(()=>this.fail(p,'Press Play again to start.'));});hls.loadSource(p.url);hls.attachMedia(p.video);
  }else{p.video.src=p.url;p.ready=true;if(/\.m3u8(?:\?|$)/i.test(p.url))p.video.onloadedmetadata=()=>{p.live=!Number.isFinite(p.video.duration);this.refresh(p);};else p.video.onloadedmetadata=null;await p.video.play();}}catch{if(generation===p.generation)this.fail(p,'Playback unavailable · Retry or choose another source.');}
 }
 private refresh(p:WallPlayer){p.play.textContent=p.video.paused?(p===this.players[0]?'Play cinema':'Play live stream'):(p===this.players[0]?'Pause cinema':'Pause stream');p.sound.textContent=p.video.muted?'Sound off':'Sound on';p.sound.setAttribute('aria-pressed',String(!p.video.muted));p.status.textContent=mediaBadge(!p.video.paused,p.live)+' · '+p.name;p.video.dataset.live=String(p.live);}
 private suspend(){for(const p of this.players){p.request=false;p.video.pause();p.hls?.stopLoad();}}
 update(x:number,z:number,visible:boolean){const map=toMap(x,0,z),p=studioCoordinates(map.x,map.z);const available=visible&&Math.abs(p.u)<24.1&&p.v>-21.7&&p.v<21.7;this.panel.hidden=!available;if(this.available&&!available)this.suspend();this.available=available;}
}
