import type { Product } from '../commerce/types';
import { initDialogs } from './dom';
import { initCart } from './cart';
import { initCatalog } from './catalog';
import { initExperience } from './experience';
import { initInlineFilms } from './inline-film';
import { initSubscriptions } from './subscriptions';
import { initAnalytics } from './analytics';
const data=JSON.parse(document.getElementById('store-data')?.textContent??'{"products":[]}') as {products:Product[]};
initDialogs();initSubscriptions(data.products);initAnalytics();initCart(data.products);initCatalog(data.products);initExperience();initInlineFilms();
if(document.querySelector('.cathedral-hero')) import('./story').then(m=>m.initStory());
if(document.querySelector('.signal-card')) import('./cinematic').then(m=>m.initCinematic());
if(document.querySelector('[data-game-host]')) import('../game/play').then(m=>m.initPlay());
if(document.querySelector('[data-load-viewer]')) import('../three/viewer-entry').then(m=>m.initViewers(data.products));
