export type RoomChatMessage={id:string;player:string;name:string;text:string;at:number};
export function cleanChatText(value:unknown){if(typeof value!=='string'||value.length>160||/[\u0000-\u001f\u007f\u202a-\u202e\u2066-\u2069]/.test(value))return;const text=value.trim();return text||undefined;}
export function validChatMessage(value:unknown):RoomChatMessage|undefined{if(!value||typeof value!=='object')return;const m=value as RoomChatMessage,text=cleanChatText(m.text);if(!text||typeof m.id!=='string'||m.id.length>80||typeof m.player!=='string'||m.player.length>80||typeof m.name!=='string'||m.name.length>40||!Number.isFinite(m.at))return;return {...m,text};}
export class ChatRateGate{private last=new Map<string,number>();allow(player:string,now:number){if(now-(this.last.get(player)??-Infinity)<1200)return false;this.last.set(player,now);return true;}forget(player:string){this.last.delete(player);}clear(){this.last.clear();}}
/** Plain text only; no HTML, links, persisted history or automated messages. */
export class RoomChatPanel {
 readonly root=document.createElement('details');private summary=document.createElement('summary');private list=document.createElement('ol');private field=document.createElement('input');private send=document.createElement('button');private status=document.createElement('output');private seen=new Set<string>();private muted=false;private unread=0;private lastSent=-Infinity;
 constructor(private transmit:(text:string)=>void,private release:()=>void,private connected:()=>boolean){
  if(!document.getElementById('ride-room-chat-style')){const style=document.createElement('style');style.id='ride-room-chat-style';style.textContent='.rideRoomChat{position:fixed;z-index:9100;left:50%;bottom:12px;transform:translateX(-50%);width:170px;max-width:calc(100vw - 24px);font:13px/1.4 system-ui;background:#091f2bea;color:#efffff;border:1px solid #72b9b0;border-radius:9px;pointer-events:auto}.rideRoomChat[hidden]{display:none!important}.rideRoomChat[open]{width:300px}.rideRoomChat summary{min-height:44px;display:flex;align-items:center;justify-content:center;cursor:pointer;list-style:none}.rideRoomChat ol{max-height:160px;overflow:auto;list-style:none;margin:0;padding:0 12px}.rideRoomChat li{overflow-wrap:anywhere;margin:8px 0}.rideRoomChat form{display:flex;gap:6px;padding:10px}.rideRoomChat input{width:0;min-width:0;flex:1}.rideRoomChat button,.rideRoomChat input{font:inherit;min-height:44px;border:1px solid #6d9d9b;border-radius:6px;background:#19394a;color:#fff;padding:5px 8px}.rideRoomChat output{display:block;padding:0 12px 8px;font-size:11px;color:#ffdd8d}.rideRoomChat .chatTools{padding:0 10px 8px;display:flex;gap:6px}.rideRoomChat button:focus-visible,.rideRoomChat input:focus-visible,.rideRoomChat summary:focus-visible{outline:3px solid #ffdd8d;outline-offset:2px}@media(max-width:650px),(max-height:500px){body.love-tag .rideRoomChat{bottom:max(150px,calc(env(safe-area-inset-bottom) + 140px))}}@media(max-height:500px){.rideRoomChat ol{max-height:76px}.rideRoomChat[open]{max-height:calc(100dvh - 80px);overflow:auto}}';document.head.append(style);}
  this.root.className='rideRoomChat lt-ui';this.root.hidden=true;this.root.setAttribute('aria-label','Multiplayer chat');this.list.setAttribute('aria-live','polite');this.summary.textContent='Chat';const form=document.createElement('form');this.field.maxLength=160;this.field.placeholder='Message your room';this.field.setAttribute('aria-label','Room message');this.field.autocomplete='off';this.send.type='submit';this.send.textContent='Send';form.append(this.field,this.send);form.onsubmit=e=>{e.preventDefault();const text=cleanChatText(this.field.value);if(!this.connected()){this.status.textContent='Connect to a room to chat.';return;}if(!text){this.status.textContent='Write a message (up to 160 characters).';return;}if(performance.now()-this.lastSent<1200){this.status.textContent='Wait a moment before sending again.';return;}this.lastSent=performance.now();this.transmit(text);this.field.value='';this.status.textContent='';};
  const tools=document.createElement('div');tools.className='chatTools';const mute=document.createElement('button');mute.type='button';mute.textContent='Mute chat';mute.setAttribute('aria-pressed','false');mute.onclick=()=>{this.muted=!this.muted;mute.setAttribute('aria-pressed',String(this.muted));mute.textContent=this.muted?'Unmute chat':'Mute chat';};const close=document.createElement('button');close.type='button';close.textContent='Close';close.onclick=()=>{this.root.open=false;};tools.append(mute,close);this.root.append(this.summary,this.list,form,tools,this.status);document.body.append(this.root);
  this.root.ontoggle=()=>{this.release();if(this.root.open){this.unread=0;this.summary.textContent='Chat';}};this.field.onfocus=()=>this.release();this.root.addEventListener('keydown',e=>e.stopPropagation());
 }
 receive(raw:unknown){const m=validChatMessage(raw);if(!m||this.muted||this.seen.has(m.id))return;this.seen.add(m.id);if(this.seen.size>128)this.seen.delete(this.seen.values().next().value!);const li=document.createElement('li'),name=document.createElement('strong');name.textContent=m.name+': ';li.append(name,document.createTextNode(m.text));this.list.append(li);while(this.list.children.length>50)this.list.firstElementChild?.remove();this.list.scrollTop=this.list.scrollHeight;if(!this.root.open)this.summary.textContent='Chat ('+(++this.unread)+')';}
 show(value:boolean){this.root.hidden=!value;if(!value)this.root.open=false;}
 clear(){this.seen.clear();this.list.replaceChildren();this.unread=0;this.summary.textContent='Chat';this.field.value='';this.status.textContent='';this.lastSent=-Infinity;}
}
