import * as T from 'three';
import {onlineService} from './tag/onlineService.ts';
import {resumeTagInput} from './tag/inputCursor.ts';
import {loadFixture} from './fixtureLoader.ts';
import {Client,type Room} from '@colyseus/sdk';
import {RideController,NEUTRAL_ACTIONS,lerpPose,createPose,type RidePose} from './controller.ts';
import {TagMatch,TagTerrain,TAG_VERSION,neutralCommand,type TagFixture,type TagProduct,type TagRuleset,type TagSnapshot,type TagCommand} from './tag.ts';
import {TagMapView} from './tag/mapView.ts';
import {RoomChatPanel} from './roomChat.ts';

type RiderView={root:T.Group;apply(p:RidePose):void;dispose():void};
type Host={product:TagProduct;scene:T.Scene;camera:T.PerspectiveCamera;canvas:HTMLCanvasElement;menu:HTMLElement;fixtureUrl:string;configUrl:string;prepare?():Promise<void>;mountDisplay?(parent:HTMLElement):void;createView(terrain:TagTerrain):Promise<RiderView>;suspend():()=>void};
const css=`
.lt-ui{font:15px/1.4 system-ui;color:#f4fbff;z-index:9000;box-sizing:border-box}.lt-ui *{box-sizing:border-box}.lt-ui[hidden],.lt-ui [hidden]{display:none!important}.lt-ui button,.lt-ui select,.lt-ui input{font:inherit;margin:0;width:auto;min-height:46px;border:1px solid #536d82;border-radius:8px;padding:9px 12px;background:#172b40;color:#fff}.lt-ui button{cursor:pointer}.lt-ui button:disabled{opacity:.45}.lt-ui button:focus-visible,.lt-ui select:focus-visible,.lt-ui input:focus-visible{outline:3px solid #ffdc77;outline-offset:3px}.lt-ui .primary{background:#55ecdb;color:#062829;font-weight:750}.lt-ui label{display:grid;gap:5px;margin:10px 0}.lt-dialog{position:fixed;inset:0;margin:auto;max-height:90dvh;overflow:auto;width:min(92vw,520px);padding:24px;border:1px solid #55ecdb;border-radius:14px;background:#071623}.lt-dialog::backdrop{background:#00101de6}.lt-dialog h2{margin:0 0 6px;font-size:28px}.lt-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:16px}.lt-message{min-height:2em;color:#ffdd88}.lt-hud{position:fixed;top:max(12px,env(safe-area-inset-top));left:12px;right:12px;display:flex;justify-content:space-between;align-items:start;pointer-events:none;gap:8px}.lt-hud>div{pointer-events:auto;padding:12px;border:1px solid #3d647a;border-radius:10px;background:#061321dc}.lt-hud output{display:block}.lt-hud strong{font-size:20px}.lt-crosshair{position:fixed;left:50%;top:50%;transform:translate(-50%,-50%);font-size:25px;pointer-events:none}.lt-touch{position:fixed;bottom:max(18px,env(safe-area-inset-bottom));left:18px;right:18px;display:flex;justify-content:space-between;pointer-events:none}.lt-touch>div{display:grid;grid-template-columns:repeat(3,56px);gap:6px;pointer-events:auto}.lt-touch button{touch-action:none;background:#0b283be8}.lt-touch [data-k=fire]{background:#c2497e}.lt-controls{position:fixed;bottom:62px;left:50%;transform:translateX(-50%);padding:6px 10px;background:#061321cb;text-align:center;font-size:12px;max-width:46vw;pointer-events:none}.lt-hidden{display:none!important}body.love-tag> :not(canvas):not(.lt-ui):not(script):not(style){visibility:hidden!important}body.love-tag canvas{visibility:visible}body.love-tag canvas.lt-game-canvas{position:fixed!important;inset:0!important;width:100vw!important;height:100dvh!important;border:0!important;display:block!important}body.love-tag .lt-ui{visibility:visible!important}.lt-room-code{font-size:26px;letter-spacing:4px;color:#55ecdb}.lt-ui table{width:100%;border-collapse:collapse}.lt-ui td,.lt-ui th{padding:8px;text-align:left;border-bottom:1px solid #36536a}@media(max-width:650px){.lt-touch{left:10px;right:10px}.lt-touch>div{grid-template-columns:repeat(3,clamp(44px,calc((100vw - 60px)/6),56px))}.lt-touch button{padding:7px 3px}.lt-hud{font-size:12px}.lt-hud>div{padding:8px}.lt-hud strong{font-size:16px}.lt-hud button{min-height:44px;padding:6px}.lt-controls{display:none}.lt-dialog{padding:18px}}@media(prefers-reduced-motion:reduce){.lt-ui *{transition:none;animation:none}}`;
const errors:Record<string,string>={ROOM_FULL:'The active seats are full. Join as a spectator or use another room.',ROOM_EXPIRED:'That room has expired. Ask the host for a new code.',INVALID_ROOM_CODE:'Enter the eight-letter or number code.',INCOMPATIBLE_MAP_OR_BUILD:'This room uses a different game or build. Open its invitation link.',INCOMPATIBLE_BUILD:'Update both game builds before joining.',WAITING_FOR_READY_PLAYERS:'Waiting for every player to finish loading.',MORE_PLAYERS_NEEDED:'Invite more riders or enable bot fill.',ONLY_HOST_CAN_START:'Only the room host can start or rematch.',SPECTATORS_FULL:'All four spectator seats are full.'};
export class LoveTagClient{
  private readonly map=new TagMapView();private display=document.createElement('dialog');private chat:RoomChatPanel;
  active=false;private fixture?:TagFixture;private terrain?:TagTerrain;private match?:TagMatch;private room?:Room;private sdk?:Client;private endpoint='';private restoring?:()=>void;private viewPending=new Set<string>();private views=new Map<string,{view:RiderView;weapon:T.Group;label:T.Sprite;role?:string}>();private heartMeshes:T.Mesh[]=[];private snapshot?:TagSnapshot;private previous?:TagSnapshot;private received=0;private accumulator=0;private seq=0;private shot=0;private aimYaw=0;private aimPitch=0;private keys=new Set<string>();private taps=new Map<string,number>();private cruise=false;private fire=false;private hop=false;private burst=false;private local?:RideController;private pending:TagCommand[]=[];private hostId='';private code='';private me='offline-human';private paused=false;private disposed=false;private resultRound='';private lastEvent='';private cameraSaved?:{position:T.Vector3;rotation:T.Quaternion;fov:number};private hiddenActors:{o:T.Object3D;visible:boolean}[]=[];private generation=0;private predictionErrors:number[]=[];
  private resetRequested=false;private arenaReady=false;private onlineEndpoint='';
  readonly dialog=document.createElement('dialog');private ui=document.createElement('div');private hud=document.createElement('div');private pads=document.createElement('div');private info:HTMLOutputElement;private role:HTMLElement;private message:HTMLElement;private status:HTMLOutputElement;private startButton:HTMLButtonElement;private invite:HTMLInputElement;
  constructor(readonly host:Host){
    this.chat=new RoomChatPanel(text=>this.room?.send('chat',{text}),()=>this.clear(),()=>!!this.room&&!this.disposed);
    const style=document.createElement('style');style.textContent=css+`.lt-map{position:fixed;right:12px;top:192px;width:144px;padding:0!important;border:1px solid #70b4a6!important;overflow:hidden;background:#071b28;z-index:9000}.lt-map canvas{display:block;width:100%;height:auto}.lt-map-dialog canvas{display:block;margin:12px 0}.lt-hud>div:first-child{max-width:calc(100% - 156px)}.lt-hud>div:last-child{display:flex;flex-direction:column;gap:4px}@media(max-width:650px){.lt-map{width:128px}.lt-hud>div:first-child{max-width:calc(100% - 142px)}}@media(max-height:500px){.lt-map{top:172px;width:104px}.lt-hud{font-size:12px}.lt-hud strong{font-size:16px}.lt-hud>div{padding:6px}}`;document.head.append(style);
    this.map.button.addEventListener('click',()=>{this.clear();document.exitPointerLock();});this.map.dialog.addEventListener('close',()=>this.clear());
    this.dialog.className='lt-ui lt-dialog';this.dialog.setAttribute('aria-labelledby','lt-title');
    this.dialog.innerHTML='<h2 id="lt-title">LOVE TAG: Heart Rush</h2><p>Ride, dodge and pass the tag. Hearts and contact both count.</p><label>Your name<input id="lt-name" maxlength="20" value="Rider" autocomplete="nickname"></label><label>Rules<select id="lt-rules"><option value="classic">Classic · pass It · lowest It time wins</option><option value="spread">Spread · taggers catch every runner</option></select></label><label>Players<select id="lt-count"><option value="4">4 riders</option><option value="2">2 riders · Classic only</option><option value="6">6 riders</option><option value="8">8 riders</option></select></label><label>Bot difficulty<select id="lt-difficulty"><option value="easy">Easy</option><option value="normal" selected>Normal</option><option value="hard">Hard</option><option value="expert">Expert · quickest reactions</option></select></label><label><span><input id="lt-fill" type="checkbox" checked> Fill empty seats with labeled bots</span></label><p id="lt-online-status" role="status" aria-live="polite">Checking online availability…</p><button id="lt-refresh-online" type="button">Check online availability</button><div class="lt-actions"><button id="lt-offline" class="primary">Play offline</button><button id="lt-create">Create online room</button><button id="lt-rejoin" hidden>Rejoin last room</button></div><label>Room code<input id="lt-code" maxlength="8" autocomplete="off" placeholder="8-character code"></label><label><span><input id="lt-spectate" type="checkbox"> Join as a spectator</span></label><div class="lt-actions"><button id="lt-join">Join online room</button><button id="lt-start" hidden class="primary">Start round</button><button id="lt-copy" hidden>Copy invitation</button><button id="lt-resume" hidden>Resume round</button><button id="lt-exit">Back to game</button></div><label id="lt-invite-label" hidden>Invitation link<input id="lt-invite" readonly></label><label>Aim sensitivity<input id="lt-sensitivity" type="range" min="1" max="6" value="3"></label><p class="lt-message" id="lt-message" role="status" aria-live="polite"></p><div id="lt-roster"></div><div id="lt-results"></div>';
    document.body.append(this.dialog);this.get<HTMLSelectElement>('lt-rules').onchange=()=>{this.get<HTMLOptionElement>('lt-count').querySelector<HTMLOptionElement>('option[value="2"]')!.disabled=this.rules()==='spread';if(this.rules()==='spread'&&this.count()<4)this.get<HTMLSelectElement>('lt-count').value='4';};
    this.message=this.get('lt-message');this.startButton=this.get('lt-start');this.invite=this.get('lt-invite');
    this.get('lt-refresh-online').onclick=()=>void this.refreshOnline();this.get('lt-rejoin').onclick=()=>void this.rejoin();this.get('lt-offline').onclick=()=>void this.beginOffline();this.get('lt-create').onclick=()=>void this.connect(true);this.get('lt-join').onclick=()=>void this.connect(false);this.get('lt-exit').onclick=()=>void this.exit();this.startButton.onclick=()=>this.room?.send(this.snapshot?.phase==='results'?'rematch':'start',{});
    this.get('lt-resume').onclick=()=>{this.clear();this.paused=false;this.status.textContent='';this.dialog.close();};
    this.get('lt-copy').onclick=async()=>{try{await navigator.clipboard.writeText(this.invite.value);this.say('Invitation copied.');}catch{this.invite.focus();this.invite.select();this.say('Copy the selected invitation link.');}};
    this.dialog.oncancel=e=>{e.preventDefault();this.toggleMenu();};
    this.hud.className='lt-ui lt-hud lt-hidden';this.hud.innerHTML='<div><strong id="lt-role"></strong><output id="lt-info"></output><output id="lt-status" aria-live="polite"></output></div><div><button id="lt-menu">Tag menu</button><button id="lt-pause">Pause offline</button></div>';document.body.append(this.hud);this.role=this.hud.querySelector('#lt-role')!;this.info=this.hud.querySelector('#lt-info')!;this.status=this.hud.querySelector('#lt-status')!;this.hud.querySelector<HTMLElement>('#lt-menu')!.onclick=()=>this.toggleMenu();this.hud.querySelector<HTMLElement>('#lt-pause')!.onclick=()=>{if(this.room){this.status.textContent='Online play continues while you are in the menu.';this.toggleMenu();}else {this.paused=!this.paused;this.clear();}};
    if(host.mountDisplay){this.display.className='lt-ui lt-dialog';this.display.setAttribute('aria-label','My display settings');const title=document.createElement('h2');title.textContent='My display';const scope=document.createElement('p');scope.textContent='Saved on this device. Other players choose their own graphics. Online play continues while you adjust these controls.';const close=document.createElement('button');close.textContent='Back to ride';close.onclick=()=>this.display.close();this.display.append(title,scope);host.mountDisplay(this.display);this.display.append(close);document.body.append(this.display);this.display.onclose=()=>{this.clear();host.canvas.focus();};const b=document.createElement('button');b.textContent='My display';b.onclick=()=>{this.clear();document.exitPointerLock();this.display.showModal();close.focus();};this.hud.lastElementChild!.append(b);}
    this.ui.className='lt-ui lt-crosshair lt-hidden';this.ui.textContent='+';document.body.append(this.ui);
    this.pads.className='lt-ui lt-touch lt-hidden';this.pads.innerHTML='<div><button data-k="cruise" aria-pressed="false">Cruise</button><button data-k="KeyW" aria-label="Ride forward">↑</button><span></span><button data-k="KeyA" aria-label="Turn left">←</button><button data-k="KeyS" aria-label="Brake or reverse">↓</button><button data-k="KeyD" aria-label="Turn right">→</button></div><div><button data-k="aimLeft" aria-label="Aim left">Aim ←</button><button data-k="fire">Heart</button><button data-k="aimRight" aria-label="Aim right">Aim →</button><button data-k="Space">Hop</button><button data-k="ShiftLeft">Burst</button><button data-k="menu">Menu</button></div>';document.body.append(this.pads);
    const bCruise=()=>this.pads.querySelector('[data-k=cruise]')?.setAttribute('aria-pressed',String(this.cruise));
    const hold=(key:string,on:boolean)=>{if(on&&key==='cruise'){this.cruise=!this.cruise;bCruise();return;}if(on)this.taps.set(key,Math.max(this.taps.get(key)??0,.18));if(key==='fire')this.fire=on;else if(key==='menu'&&on)this.toggleMenu();else if(on)this.keys.add(key);else this.keys.delete(key);};
    for(const b of this.pads.querySelectorAll<HTMLButtonElement>('button')){b.onclick=e=>{if(e.detail===0){if(b.dataset.k==='cruise'){this.cruise=!this.cruise;bCruise();}else if(b.dataset.k==='menu')this.toggleMenu();else this.taps.set(b.dataset.k!, .18);}};b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);hold(b.dataset.k!,true);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>hold(b.dataset.k!,false);}
    const entry=document.createElement('button');entry.id='love-tag-open';entry.textContent='LOVE TAG · Heart Rush';entry.onclick=()=>void this.open();this.host.menu.append(entry);
    addEventListener('keydown',e=>{if(!this.active)return;if((e.target as HTMLElement)?.matches('input,select,textarea')&&e.code!=='Escape')return;if(['Escape','KeyP'].includes(e.code)){e.preventDefault();e.stopImmediatePropagation();if(!e.repeat){if(this.display.open)this.display.close();else if(this.map.dialog.open)this.map.dialog.close();else this.toggleMenu();}return;}if(['KeyW','KeyS','KeyA','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','ShiftLeft','KeyF','KeyR'].includes(e.code)){e.preventDefault();e.stopImmediatePropagation();if(!this.dialog.open&&!this.map.dialog.open&&!this.display.open)this.keys.add(e.code);if(e.code==='KeyR'&&!e.repeat)this.say('Reset makes runners It and adds a reset penalty. Use Reset rider in the Tag menu.');}},true);
    addEventListener('keyup',e=>{if(this.active){this.keys.delete(e.code);e.stopImmediatePropagation();}},true);
    host.canvas.addEventListener('pointerdown',e=>{if(this.active&&!this.dialog.open&&!this.map.dialog.open&&!this.display.open&&e.pointerType==='mouse'){if(e.button===0)this.fire=true;if(e.button===2)void host.canvas.requestPointerLock();e.preventDefault();e.stopImmediatePropagation();}},true);
    addEventListener('pointerup',()=>this.fire=false);addEventListener('mousemove',e=>{if(this.active&&!this.dialog.open&&!this.map.dialog.open&&!this.display.open&&document.pointerLockElement===host.canvas){const scale=Number(this.get<HTMLInputElement>('lt-sensitivity').value)*.001;this.aimYaw=Math.max(-1.35,Math.min(1.35,this.aimYaw-e.movementX*scale));this.aimPitch=Math.max(-.75,Math.min(.75,this.aimPitch-e.movementY*scale));}});
    host.canvas.addEventListener('contextmenu',e=>{if(this.active)e.preventDefault();});addEventListener('blur',()=>{this.clear();if(this.active&&!this.room)this.paused=true;});document.addEventListener('visibilitychange',()=>{if(document.hidden){this.clear();if(this.active&&!this.room)this.paused=true;}});
    const help=document.createElement('p');help.className='lt-ui lt-controls lt-hidden';help.textContent='WASD / arrows ride · F / click heart · right-click mouse aim · Space hop · Shift burst · Esc menu';document.body.append(help);
    const reset=document.createElement('button');reset.textContent='Reset rider · runner becomes It';reset.onclick=()=>{this.resetRequested=true;this.status.textContent='';this.dialog.close();this.paused=false;};this.get('lt-results').after(reset);
    if(new URLSearchParams(location.search).get('tagReview')==='1'){const test=document.createElement('button');test.textContent='Review: interrupt connection for 5s';test.onclick=()=>void this.reviewReconnect(test);this.get('lt-results').after(test);}
    const params=new URLSearchParams(location.search);if(params.has('tagRoom')){const product=params.get('tagProduct');if(product&&product!==host.product&&['swoop-detroit','elmwood-explorer'].includes(product)){const link=document.createElement('a'),url=new URL(product==='swoop-detroit'?'../swoop-detroit/':'../elmwood-explorer/elmwood.html',location.href);url.search=params.toString();link.href=url.href;link.textContent='Open this LOVE TAG invitation in '+product;host.menu.append(link);}else {this.get<HTMLInputElement>('lt-code').value=params.get('tagRoom')??'';entry.textContent='LOVE TAG · Join invitation';}}
  }
  private get<E extends HTMLElement=HTMLElement>(id:string){return this.dialog.querySelector<E>('#'+id)!;}
  private say(message:string){this.message.textContent=errors[message]??message;}
  private rules(){return this.get<HTMLSelectElement>('lt-rules').value as TagRuleset;}
  private count(){return Math.max(this.rules()==='spread'?4:2,Number(this.get<HTMLSelectElement>('lt-count').value));}
  private launchReady(ready:boolean){this.arenaReady=ready;this.get<HTMLButtonElement>('lt-offline').disabled=!ready;for(const id of ['lt-create','lt-join','lt-rejoin']){const button=this.get<HTMLButtonElement>(id);button.disabled=!ready||!this.onlineEndpoint;button.setAttribute('aria-describedby','lt-online-status');}}
  private async refreshOnline(){
    const button=this.get<HTMLButtonElement>('lt-refresh-online');button.disabled=true;this.onlineEndpoint='';this.launchReady(this.arenaReady);this.get('lt-online-status').textContent='Checking online availability…';
    try{const response=await fetch(this.host.configUrl,{cache:'no-store',signal:AbortSignal.timeout(8000)});if(!response.ok)throw Error('configuration unavailable');const config=await response.json();const service=onlineService(config?.serverUrl,location.hostname);this.onlineEndpoint=service.endpoint;this.get('lt-online-status').textContent=service.message;}
    catch{this.get('lt-online-status').textContent='Could not check online availability. Play offline, or try checking again.';}
    finally{button.disabled=false;this.launchReady(this.arenaReady);}
  }
  private clear(){this.keys.clear();this.taps.clear();this.cruise=false;this.pads.querySelector('[data-k=cruise]')?.setAttribute('aria-pressed','false');this.fire=this.hop=this.burst=false;this.room?.send('release',{});}
  async open(){
    if(!this.active){this.active=true;this.disposed=false;this.restoring=this.host.suspend();this.cameraSaved={position:this.host.camera.position.clone(),rotation:this.host.camera.quaternion.clone(),fov:this.host.camera.fov};document.body.classList.add('love-tag');this.host.canvas.classList.add('lt-game-canvas');document.querySelectorAll<HTMLDialogElement>('dialog[open]').forEach(d=>d.close());this.dialog.showModal();this.say('Loading the verified arena…');
      this.launchReady(false);void this.refreshOnline();const generation=this.generation;
      try{await this.host.prepare?.();const fixture:TagFixture=await loadFixture(this.host.fixtureUrl);if(fixture.product!==this.host.product)throw Error('Wrong product fixture');const terrain=await TagTerrain.create(fixture);if(!this.active||generation!==this.generation){terrain.dispose();return;}this.fixture=fixture;this.terrain=terrain;this.map.prepare(fixture,terrain);this.get('lt-rejoin').hidden=!this.savedSeat();this.launchReady(true);this.say('Full map: run and hide on safe open ground. Water and solid scenery stay blocked. Offline works without a server.');}catch(e){if(this.active)this.say((e as Error).message);return;}
    }else if(!this.dialog.open)this.dialog.showModal();
  }
  private async prepare(){this.resetRequested=false;this.lastEvent='';this.status.textContent='';this.say('');for(const id of ['lt-invite-label','lt-copy','lt-start'])this.get(id).hidden=true;this.get('lt-resume').hidden=true;await this.open();if(!this.terrain)throw Error('Arena not ready');this.clear();if(this.room){this.disposed=true;await this.room.leave();this.room=undefined;this.disposed=false;}this.match=undefined;this.local=undefined;this.snapshot=this.previous=undefined;this.generation++;this.disposeViews();this.get('lt-results').replaceChildren();this.get('lt-roster').replaceChildren();this.seq=this.shot=0;this.pending=[];this.resultRound='';this.accumulator=0;}
  private async beginOffline(){try{await this.prepare();if(this.room){await this.room.leave();this.room=undefined;}this.me='offline-human';this.match=new TagMatch(this.fixture!,this.terrain!,this.rules(),this.get<HTMLSelectElement>('lt-difficulty').value as 'easy'|'normal'|'hard'|'expert');this.match.addActor(this.me,this.get<HTMLInputElement>('lt-name').value);
      for(let i=1;i<this.count();i++)this.match.addActor('bot-'+i,'Bot '+i,true);this.match.start(crypto.randomUUID());this.snapshot=this.match.snapshot();this.local=undefined;this.paused=false;this.dialog.close();this.setHud(true);await this.makeViews();}catch(e){this.say((e as Error).message);}}
  private async backend(){if(!this.onlineEndpoint)await this.refreshOnline();if(!this.onlineEndpoint)throw Error(this.get('lt-online-status').textContent??'Online is unavailable. Play offline.');this.endpoint=this.onlineEndpoint.replace(/^ws/,'http');this.sdk=new Client(this.onlineEndpoint);return this.sdk;}
  private async connect(create:boolean){try{await this.prepare();this.say('Connecting to the real LOVE TAG server…');const sdk=await this.backend();const options={product:this.host.product,version:TAG_VERSION,hash:this.fixture!.hash,name:this.get<HTMLInputElement>('lt-name').value,ruleset:this.rules(),difficulty:this.get<HTMLSelectElement>('lt-difficulty').value,target:this.count(),botFill:this.get<HTMLInputElement>('lt-fill').checked,spectate:this.get<HTMLInputElement>('lt-spectate').checked};
      let room:Room;if(create)room=await sdk.create('love-tag',options);else {const code=this.get<HTMLInputElement>('lt-code').value.trim().toUpperCase(),data=await fetch(this.endpoint+'/v1/room/'+encodeURIComponent(code)).then(r=>r.json());if(data.error)throw Error(data.error);if(data.product!==this.host.product)throw Error('INCOMPATIBLE_MAP_OR_BUILD');room=await sdk.joinById(data.roomId,options);}
      this.bindRoom(room);
    }catch(e){this.say((e as Error).message||'Online server unavailable. Choose offline explicitly.');}}

  private seatKey(){return 'love-tag-seat-'+this.host.product;}
  private savedSeat(){try{const value=JSON.parse(sessionStorage.getItem(this.seatKey())||'null');return value?.version===TAG_VERSION&&value?.hash===this.fixture?.hash&&typeof value?.token==='string'?value:null;}catch{return null;}}
  private saveSeat(room:Room){try{sessionStorage.setItem(this.seatKey(),JSON.stringify({version:TAG_VERSION,hash:this.fixture!.hash,token:room.reconnectionToken}));this.get('lt-rejoin').hidden=true;}catch{}}
  private async rejoin(){const seat=this.savedSeat();if(!seat){this.say('No compatible saved seat. Join with the room code.');return;}try{await this.prepare();const sdk=await this.backend();this.say('Rejoining your existing online seat…');const room=await sdk.reconnect(seat.token);this.bindRoom(room);}catch(e){try{sessionStorage.removeItem(this.seatKey());}catch{}this.get('lt-rejoin').hidden=true;this.say('The reconnect window ended. Join the room code again: '+(e as Error).message);}}
  /** Opt-in local browser review: closes the actual socket, then reclaims the same seat. */
  private async reviewReconnect(button:HTMLButtonElement){
    if(!this.room||!this.sdk){this.say('Create or join an online room first.');return;}
    button.disabled=true;const old=this.room,token=old.reconnectionToken,sdk=this.sdk,generation=this.generation;
    this.clear();this.disposed=true;old.reconnection.enabled=false;old.connection.close();this.room=undefined;this.local=undefined;
    this.status.textContent='Review interruption · real socket disconnected for five seconds';
    await new Promise<void>(resolve=>setTimeout(resolve,5000));
    try{
      if(!this.active||generation!==this.generation)return;
      const room=await sdk.reconnect(token);
      if(!this.active||generation!==this.generation){await room.leave();return;}
      this.disposed=false;this.bindRoom(room);this.status.textContent='Review reconnect complete · authoritative seat reclaimed.';
    }catch(e){if(this.active&&generation===this.generation){this.disposed=false;this.say('Reconnect failed: '+(e as Error).message);}}
    finally{button.disabled=false;}
  }
  private bindRoom(room:Room){
      this.match=undefined;this.room=room;this.me=room.sessionId;this.local=new RideController(this.terrain!);this.snapshot=undefined;
      room.onMessage('welcome',data=>{this.saveSeat(room);this.code=data.code;this.hostId=data.host;this.get<HTMLInputElement>('lt-code').value=this.code;const url=new URL(location.href);url.search='';url.hash='';url.searchParams.set('tagRoom',this.code);url.searchParams.set('tagProduct',this.host.product);url.searchParams.set('tagVersion',TAG_VERSION);url.searchParams.set('tagArena',this.fixture!.arena);this.invite.value=url.href;this.get('lt-invite-label').hidden=false;this.get('lt-copy').hidden=false;this.say((data.spectator?'Spectating. Join active seats next round. ':'Room '+this.code+' · ')+(this.hostId===this.me?'Invite a friend, then start.':'Waiting for the host.'));this.startButton.hidden=this.hostId!==this.me;room.send('ready',{hash:this.fixture!.hash});});
      this.chat.clear();this.chat.show(true);room.onMessage('chat',m=>this.chat.receive(m));
      room.onMessage('host',id=>{this.hostId=id;this.startButton.hidden=id!==this.me;this.say('The room host changed. The server continues the match.');});room.onMessage('notice',m=>this.say(m));room.onMessage('snapshot',s=>void this.receive(s));room.onDrop(()=>{this.clear();this.pending=[];this.snapshot=undefined;this.status.textContent='Connection lost · reconnecting for up to 20 seconds · bot takeover remains taggable.';});room.onReconnect(()=>{this.saveSeat(room);this.pending=[];this.status.textContent='Reconnected to your existing seat.';room.send('hello',{});});room.onLeave(()=>{if(!this.disposed){this.room=undefined;this.chat.show(false);this.local=undefined;this.toggleMenu(true);this.say('Online session ended. Select Play offline explicitly, or create/join another room.');}});
      this.setHud(true);room.send('hello',{});
  }
  private async receive(s:TagSnapshot){if(s.version!==TAG_VERSION||s.hash!==this.fixture!.hash){this.say('INCOMPATIBLE_BUILD');await this.exit();return;}
    if(this.room&&!this.snapshot){this.get<HTMLSelectElement>('lt-rules').value=s.ruleset;this.get<HTMLSelectElement>('lt-count').querySelector<HTMLOptionElement>('option[value="2"]')!.disabled=s.ruleset==='spread';}
    const launching=(!this.snapshot||this.snapshot.phase==='lobby'||this.snapshot.round!==s.round)&&s.phase!=='lobby';if(this.snapshot?.round!==s.round){this.seq=this.shot=0;this.pending=[];this.resultRound='';this.lastEvent='';this.status.textContent='';this.get('lt-results').replaceChildren();}this.previous=this.snapshot;this.snapshot=s;this.received=performance.now();
    if(s.owner&&this.local){const before=this.local.poseValue;const auth=s.actors.find(a=>a.id===this.me);if(auth){if(!this.previous||this.previous.round!==s.round){const cursor=resumeTagInput(auth.ack);this.seq=cursor.seq;this.shot=cursor.shot;this.pending=[];}this.predictionErrors.push(Math.hypot(before.x-auth.pose.x,before.z-auth.pose.z));if(this.predictionErrors.length>240)this.predictionErrors.shift();this.pending=this.pending.filter(c=>c.seq>auth.ack&&c.round===s.round);this.local.restoreState(s.owner.state);for(const c of this.pending)this.predict(c);}}
    await this.makeViews();if(s.phase==='lobby'){const names=s.actors.map(a=>a.name+(a.bot?' [BOT]':' [HUMAN]'));this.get('lt-roster').textContent=names.join(' · ');}else if(launching&&this.dialog.open&&s.phase!=='results'){this.dialog.close();this.paused=false;}
  }
  private disposeViews(){for(const {view,weapon,label}of this.views.values()){weapon.traverse(o=>{const m=o as T.Mesh;if(m.isMesh){m.geometry.dispose();(m.material as T.Material).dispose();}});(label.material as T.SpriteMaterial).map?.dispose();label.material.dispose();view.dispose();view.root.removeFromParent();}this.views.clear();this.viewPending.clear();for(const m of this.heartMeshes){m.removeFromParent();m.geometry.dispose();(m.material as T.Material).dispose();}this.heartMeshes=[];}
  private setHud(show:boolean){this.map.show(show);this.chat.show(show&&!!this.room&&!this.disposed);for(const ui of [this.hud,this.ui,this.pads,...Array.from(document.querySelectorAll('.lt-controls'))])ui.classList.toggle('lt-hidden',!show);}
  private async makeViews(){const generation=this.generation;
    for(const a of this.snapshot?.actors??[]){if(this.views.has(a.id)||this.viewPending.has(a.id))continue;this.viewPending.add(a.id);let view:RiderView;try{view=await this.host.createView(this.terrain!);}catch(e){this.viewPending.delete(a.id);this.say('Rider asset unavailable: '+(e as Error).message);continue;}if(generation!==this.generation){view.dispose();return;}this.viewPending.delete(a.id);const weapon=new T.Group();weapon.name='Heart caster';
      const body=new T.Mesh(new T.BoxGeometry(.11,.13,.24),new T.MeshStandardMaterial({color:'#ff6fa8',metalness:.35,roughness:.3})),barrel=new T.Mesh(new T.CylinderGeometry(.045,.055,.22,12),new T.MeshStandardMaterial({color:'#efe5bd',metalness:.65,roughness:.25}));barrel.rotation.x=Math.PI/2;barrel.position.z=.16;weapon.add(body,barrel);weapon.position.set(.24,1.05,.3);view.root.add(weapon);
      const label=this.label(a.role.toUpperCase()+' · '+a.name+(a.bot?' · BOT':' · HUMAN'));label.visible=a.id!==this.me;label.position.y=2.15;view.root.add(label);this.views.set(a.id,{view,weapon,label});this.host.scene.add(view.root);}
  }
  private label(text:string){const c=document.createElement('canvas');c.width=512;c.height=80;const ctx=c.getContext('2d')!;ctx.fillStyle='#071623dd';ctx.fillRect(0,0,512,80);ctx.fillStyle='#ffffff';ctx.font='bold 28px system-ui';ctx.textAlign='center';ctx.fillText(text,256,48);const texture=new T.CanvasTexture(c),s=new T.Sprite(new T.SpriteMaterial({map:texture,depthTest:true}));s.scale.set(1.9,.30,1);return s;}
  private command():TagCommand{const held=(k:string)=>this.keys.has(k)||(this.taps.get(k)??0)>0;for(const [k,time]of this.taps)this.taps.set(k,Math.max(0,time-1/60));const c=neutralCommand(this.snapshot?.round??'',++this.seq,this.snapshot?.tick??0);c.throttle=(this.cruise||held('KeyW')||held('ArrowUp')?1:0)-(held('KeyS')||held('ArrowDown')?1:0);c.steer=(held('KeyD')||held('ArrowRight')?1:0)-(held('KeyA')||held('ArrowLeft')?1:0);if(held('aimLeft'))this.aimYaw=Math.min(1.35,this.aimYaw+.025);if(held('aimRight'))this.aimYaw=Math.max(-1.35,this.aimYaw-.025);c.aimYaw=this.aimYaw;c.aimPitch=this.aimPitch;c.fire=this.fire||held('fire')||held('KeyF');c.shot=c.fire?++this.shot:this.shot;c.hop=held('Space')&&!this.hop;this.hop=held('Space');c.burst=held('ShiftLeft')&&!this.burst;this.burst=held('ShiftLeft');c.reset=this.resetRequested;this.resetRequested=false;
    const axis=(n:number)=>Math.abs(n??0)<.16?0:Math.sign(n)*Math.min(1,(Math.abs(n)-.16)/.84);const pad=navigator.getGamepads?.()?.[0];if(pad){c.throttle=Math.max(-1,Math.min(1,c.throttle-axis(pad.axes[1])));c.steer=Math.max(-1,Math.min(1,c.steer+axis(pad.axes[0])));c.aimYaw=Math.max(-1.35,Math.min(1.35,c.aimYaw-(axis(pad.axes[2])??0)*.03));c.aimPitch=Math.max(-.75,Math.min(.75,c.aimPitch-(axis(pad.axes[3])??0)*.03));c.fire=c.fire||!!pad.buttons[7]?.pressed;if(c.fire&&c.shot===this.shot)c.shot=++this.shot;c.hop=c.hop||!!pad.buttons[0]?.pressed;c.burst=c.burst||!!pad.buttons[1]?.pressed;}return c;}
  private predict(c:TagCommand){if(!this.local||!this.snapshot||!['head_start','active'].includes(this.snapshot.phase))return;const a=this.snapshot.actors.find(a=>a.id===this.me);if(this.snapshot.phase==='head_start'&&a?.role==='it')return;this.local.step(1/60,{...NEUTRAL_ACTIONS,throttle:c.throttle,steer:c.steer,hop:c.hop,hopHeld:c.hop});}
  toggleMenu(force=false){if(this.display.open)this.display.close();if(this.map.dialog.open)this.map.dialog.close();this.get('lt-resume').hidden=!this.snapshot||this.snapshot.phase==='lobby'||this.snapshot.phase==='results';this.clear();document.exitPointerLock();if(force||!this.dialog.open){this.paused=!this.room;this.startButton.textContent=this.snapshot?.phase==='results'?'Rematch':'Start round';this.startButton.hidden=!this.room||this.hostId!==this.me||!['lobby','results'].includes(this.snapshot?.phase??'');if(!this.dialog.open)this.dialog.showModal();if(this.room)this.say('Online play continues. Your rider remains taggable while this menu is open.');}else {this.dialog.close();this.paused=false;this.status.textContent='';}}
  /** Authoritative/predicted local focus for host streaming, light and terrain LOD. */
  get isActive(){return this.active;}
  get sceneFocus(){const p=this.local?.poseValue??this.snapshot?.actors.find(a=>a.id===this.me)?.pose;return p?{x:p.x,y:p.y,z:p.z,headingY:p.headingY}:undefined;}
  update(dt:number){
    if(!this.active)return false;if(!this.snapshot)return true;
    this.accumulator=Math.min(.2,this.accumulator+dt);while(this.accumulator>=1/60){this.accumulator-=1/60;if(this.dialog.open||this.map.dialog.open||this.display.open||this.chat.root.open||this.paused)continue;const c=this.command();
      if(this.match){this.match.command(this.me,c);this.match.step();this.snapshot=this.match.snapshot();}
      else if(this.room&&this.snapshot.phase!=='results'){this.room.send('input',c);this.pending.push(c);if(this.pending.length>240)this.pending.shift();this.predict(c);}
    }
    const s=this.snapshot,me=s.actors.find(a=>a.id===this.me);for(const a of s.actors){const item=this.views.get(a.id);if(!item)continue;const p=createPose(),old=this.previous?.actors.find(b=>b.id===a.id);if(a.id===this.me&&this.local)Object.assign(p,this.local.poseValue);else if(old&&this.previous?.round===s.round)lerpPose(old.pose,a.pose,Math.min(1,(performance.now()-this.received)/50),p);else Object.assign(p,a.pose);item.view.apply(p);item.weapon.rotation.y=a.id===this.me?this.aimYaw:0;item.weapon.rotation.x=a.id===this.me?-this.aimPitch:0;item.weapon.visible=a.role==='it';item.label.material.color.set(a.role==='it'?'#ff93bd':'#70f3dc');item.label.visible=a.id!==this.me;if(item.role!==a.role+String(a.connected)){item.role=a.role+String(a.connected);const texture=(item.label.material as T.SpriteMaterial).map!,canvas=texture.image as HTMLCanvasElement,ctx=canvas.getContext('2d')!;ctx.clearRect(0,0,512,80);ctx.fillStyle='#071623dd';ctx.fillRect(0,0,512,80);ctx.fillStyle='#fff';ctx.font='bold 24px system-ui';ctx.textAlign='center';ctx.fillText((a.role==='it'?'IT':'RUNNER')+' · '+a.name+(a.bot?' · BOT':!a.connected?' · RECONNECT PROXY':' · HUMAN'),256,48,495);texture.needsUpdate=true;}}
    if(me){const p=this.local?.poseValue??me.pose;
      for(const a of s.actors){const item=this.views.get(a.id);if(!item)continue;const q=a.pose,d={x:q.x-p.x,y:q.y-p.y,z:q.z-p.z};item.label.visible=a.id!==this.me&&Math.hypot(d.x,d.z)<=45&&this.terrain!.raycastObstacle({x:p.x,y:p.y+1.05,z:p.z},d,Math.hypot(d.x,d.y,d.z),0)===null;}
      const sin=Math.sin(p.headingY),cos=Math.cos(p.headingY),wanted=new T.Vector3(p.x-sin*5,p.y+3,p.z-cos*5);const focus={x:p.x,y:p.y+1.2,z:p.z},delta=wanted.clone().sub(new T.Vector3(focus.x,focus.y,focus.z)),hit=this.terrain?.raycastObstacle(focus,delta,delta.length(),.18);if(hit!==null&&hit!==undefined)wanted.copy(new T.Vector3(focus.x,focus.y,focus.z).addScaledVector(delta.normalize(),Math.max(.5,hit-.25)));this.host.camera.position.lerp(wanted,1-Math.exp(-8*dt));this.host.camera.lookAt(p.x+sin*2,p.y+1.1,p.z+cos*2);this.host.camera.fov=55;this.host.camera.aspect=this.host.canvas.clientWidth/Math.max(1,this.host.canvas.clientHeight);this.host.camera.updateProjectionMatrix();}
    this.map.update(dt,s,this.me);
    this.renderHearts(s);this.role.textContent=!me?'SPECTATOR':me.role==='it'?'♥ YOU ARE IT':'◇ RUNNER';const pauseButton=this.hud.querySelector<HTMLButtonElement>('#lt-pause')!;pauseButton.textContent=this.room?'Room menu':this.paused?'Resume round':'Pause round';if(this.room)pauseButton.removeAttribute('aria-pressed');else pauseButton.setAttribute('aria-pressed',String(this.paused));this.info.textContent=(this.room?'ONLINE':this.match?'OFFLINE':'RECONNECTING')+' · '+s.ruleset.toUpperCase()+' · '+(this.match&&(this.paused||this.dialog.open||this.map.dialog.open||this.display.open||this.chat.root.open)?'PAUSED':s.phase.replace('_',' '))+' · '+Math.ceil(s.remaining)+'s'+(me?' · Hearts '+me.ammo+'/3 · Burst '+Math.floor(me.burst)+'%':' · SPECTATOR');
    const newest=s.events.at(-1);if(newest&&newest.id!==this.lastEvent){this.lastEvent=newest.id;if(newest.kind==='tag')this.status.textContent='Confirmed tag: '+(s.actors.find(a=>a.id===newest.actor)?.name??'Rider')+' → '+(s.actors.find(a=>a.id===newest.target)?.name??'Rider');else if(newest.kind==='blocked')this.status.textContent='Heart blocked by cover.';}
    if(s.phase==='results'&&this.resultRound!==s.round){this.resultRound=s.round;this.showResults();}this.host.canvas.dataset.loveTag=JSON.stringify({product:this.host.product,phase:s.phase,paused:!!this.match&&(this.paused||this.dialog.open||this.map.dialog.open||this.display.open||this.chat.root.open),rules:s.ruleset,online:!this.match,humans:s.actors.filter(a=>!a.bot).length,bots:s.actors.filter(a=>a.bot).length,round:s.round,tick:s.tick,me:this.me,role:me?.role,pose:me?{x:me.pose.x,y:me.pose.y,z:me.pose.z}:undefined,ack:me?.ack,hash:s.hash,actors:s.actors.map(a=>({id:a.id,name:a.name,connected:a.connected,bot:a.bot,role:a.role,ammo:a.ammo,tags:a.tags,itTime:a.itTime,resets:a.resets,pose:{x:a.pose.x,y:a.pose.y,z:a.pose.z,heading:a.pose.headingY}})),events:s.events,winners:s.winners,remaining:s.remaining,correctionP95:[...this.predictionErrors].sort((a,b)=>a-b)[Math.floor(this.predictionErrors.length*.95)]??0});return true;
  }
  private renderHearts(s:TagSnapshot){while(this.heartMeshes.length<s.hearts.length){const shape=new T.Shape();shape.moveTo(0,-.12);shape.bezierCurveTo(-.32,.10,-.18,.32,0,.15);shape.bezierCurveTo(.18,.32,.32,.10,0,-.12);const m=new T.Mesh(new T.ExtrudeGeometry(shape,{depth:.06,bevelEnabled:false,curveSegments:5}),new T.MeshStandardMaterial({color:'#ff75b3',emissive:'#4a1430',roughness:.4}));this.host.scene.add(m);this.heartMeshes.push(m);}this.heartMeshes.forEach((m,i)=>{const h=s.hearts[i];m.visible=!!h;if(h){m.position.set(h.position.x,h.position.y,h.position.z);m.quaternion.copy(this.host.camera.quaternion);}});}
  private showResults(){this.toggleMenu(true);const s=this.snapshot!,root=this.get('lt-results');root.replaceChildren();const heading=document.createElement('h3');heading.textContent='Round complete · '+s.winners.map(id=>s.actors.find(a=>a.id===id)?.name).join(' & ')+' won';root.append(heading);const table=document.createElement('table');for(const a of s.actors){const row=table.insertRow();for(const text of [a.name+(a.bot?' [BOT]':' [HUMAN]'),a.dnf?'DNF':s.ruleset==='classic'?(a.itTime+3*a.resets).toFixed(1)+'s It + reset penalties':a.role,a.tags+' tags'])row.insertCell().textContent=text;}root.append(table);if(this.match){const b=document.createElement('button');b.textContent='Rematch offline';b.onclick=()=>{this.match!.start(crypto.randomUUID());this.snapshot=this.match!.snapshot();this.resultRound='';this.lastEvent='';this.say('');root.replaceChildren();this.status.textContent='';this.dialog.close();this.paused=false;};root.append(b);}else this.startButton.textContent='Rematch';}
  async exit(){this.display.close();this.chat.show(false);this.chat.clear();this.resetRequested=false;try{sessionStorage.removeItem(this.seatKey());}catch{}this.get('lt-rejoin').hidden=true;this.disposed=true;this.generation++;this.clear();if(this.room){this.room.reconnection.enabled=false;await this.room.leave();}this.room=undefined;this.match=undefined;this.local=undefined;this.snapshot=undefined;this.previous=undefined;this.pending=[];this.dialog.close();this.setHud(false);
    this.disposeViews();this.terrain?.dispose();this.terrain=undefined;this.active=false;this.say('');this.launchReady(false);document.body.classList.remove('love-tag');this.host.canvas.classList.remove('lt-game-canvas');document.exitPointerLock();if(this.cameraSaved){this.host.camera.position.copy(this.cameraSaved.position);this.host.camera.quaternion.copy(this.cameraSaved.rotation);this.host.camera.fov=this.cameraSaved.fov;this.host.camera.updateProjectionMatrix();}this.restoring?.();this.host.canvas.dataset.loveTag='';}
}
