import {voiceChannel,voiceSignal,type VoiceChannel,type VoiceMember,type VoiceSignal} from './voiceProtocol.ts';
type Peer={pc:RTCPeerConnection;audio:HTMLAudioElement;making:boolean;ignore:boolean;setting:boolean;queue:Promise<void>;ice:RTCIceCandidateInit[]};
type Transport={state:(enabled:boolean,channel:VoiceChannel)=>void;signal:(signal:VoiceSignal)=>void};
/** Small-room audio mesh. Capture is opt-in; leaving a room stops every track. */
export class VoiceChat {
 private diagnosticsCounts={sent:0,received:0,rejected:0,errors:[] as string[]};
 readonly root=document.createElement('details');private status=document.createElement('output');private join=document.createElement('button');private mic=document.createElement('button');private talk=document.createElement('button');private channel=document.createElement('select');private list=document.createElement('div');
 private peers=new Map<string,Peer>();private members:VoiceMember[]=[];private muted=new Set<string>();private stream?:MediaStream;private enabled=false;private listening=true;private openMic=false;private pushing=false;private busy=false;private epoch=0;private me='';private transport?:Transport;private volume=1;private iceServers:RTCIceServer[]=[{urls:'stun:stun.l.google.com:19302'}];
 private captureAudio:()=>Promise<MediaStream>;
 constructor(captureAudio=()=>navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false})){
  this.captureAudio=captureAudio;
  this.root.className='rideVoice';this.root.hidden=true;const summary=document.createElement('summary');summary.textContent='Voice';this.root.setAttribute('aria-label','Player voice chat');this.status.setAttribute('role','status');
  const note=document.createElement('p');note.textContent='Audio only. Join to listen; enable your microphone to talk. Squad channels group voice only.';
  this.join.textContent='Join voice';this.join.onclick=()=>{if(this.enabled)this.stop();else {this.enabled=true;this.listening=true;this.status.textContent='Listening · waiting for riders in this channel.';this.transport?.state(true,this.channel.value as VoiceChannel);this.sync();}this.refresh();};
  this.mic.textContent='Mic off';this.mic.onclick=()=>void this.capture(false);this.talk.textContent='Hold to talk';this.talk.onpointerdown=e=>{e.preventDefault();this.talk.setPointerCapture(e.pointerId);this.pushing=true;void this.capture(true);};
  const release=()=>{this.pushing=false;this.applyMic();};this.talk.onpointerup=release;this.talk.onpointercancel=release;this.talk.onlostpointercapture=release;this.talk.onkeydown=e=>{if((e.code==='Space'||e.code==='Enter')&&!e.repeat){e.preventDefault();this.pushing=true;void this.capture(true);}};this.talk.onkeyup=release;
  for(const [id,label]of [['all','All players'],['squad-a','Squad A'],['squad-b','Squad B']])this.channel.add(new Option(label,id));this.channel.setAttribute('aria-label','Voice channel');this.channel.onchange=()=>{this.closePeers();this.transport?.state(this.enabled,this.channel.value as VoiceChannel);this.sync();};
  const speaker=document.createElement('button');speaker.textContent='Sound on';speaker.onclick=()=>{this.listening=!this.listening;speaker.textContent=this.listening?'Sound on':'Mute all';for(const [id,p]of this.peers){p.audio.muted=!this.listening||this.muted.has(id);if(this.listening)void p.audio.play().catch(()=>this.status.textContent='Tap Sound on to hear connected riders.');}};
  const volume=document.createElement('input');volume.type='range';volume.min='0';volume.max='100';volume.value='100';volume.setAttribute('aria-label','Voice volume');volume.oninput=()=>{this.volume=Number(volume.value)/100;for(const p of this.peers.values())p.audio.volume=this.volume;};
  this.root.append(summary,note,this.channel,this.join,this.mic,this.talk,speaker,volume,this.list,this.status);document.body.append(this.root);
  if(!document.getElementById('ride-voice-style')){const css=document.createElement('style');css.id='ride-voice-style';css.textContent='.rideVoice{position:fixed;right:12px;top:70px;z-index:9200;width:92px;padding:6px;background:#102732ed;color:#efffff;border:1px solid #77ada7;border-radius:10px;font:13px system-ui;pointer-events:auto}.rideVoice[open]{width:min(290px,calc(100vw - 24px));max-height:70dvh;overflow:auto}.rideVoice summary{min-height:36px;cursor:pointer;display:grid;place-items:center}.rideVoice p{font-size:11px}.rideVoice button,.rideVoice select{min-height:44px;margin:3px;font:inherit;border:1px solid #77ada7;border-radius:8px;background:#21444a;color:#fff;padding:7px}.rideVoice output{display:block;font-size:11px;padding:5px}.rideVoice label{display:flex;align-items:center;justify-content:space-between}.rideVoice button:focus-visible,.rideVoice summary:focus-visible{outline:3px solid #efcf82}.rideVoice button[aria-pressed=true]{background:#1b7963}.rideVoice[hidden]{display:none!important}dialog .rideVoice{position:static;width:100%;margin-top:12px}';document.head.append(css);}
  window.addEventListener('blur',release);document.addEventListener('visibilitychange',()=>{if(document.hidden){this.openMic=false;release();}});window.addEventListener('pagehide',()=>this.stop());this.refresh();
 }
 bind(me:string,transport:Transport,iceServers?:RTCIceServer[]){this.stop();this.me=me;this.transport=transport;if(iceServers)this.iceServers=iceServers;this.root.hidden=false;this.status.textContent='Voice off. Join when you are ready.';}
 setMembers(members:unknown){this.members=Array.isArray(members)?members.filter((m):m is VoiceMember=>!!m&&typeof m.id==='string'&&m.id.length<=80&&typeof m.name==='string'&&m.name.length<=80&&voiceChannel(m.channel)).slice(0,12):[];this.sync();}
 disconnect(){this.stop();this.transport=undefined;this.me='';this.members=[];this.root.hidden=true;}
 private refresh(){this.join.textContent=this.enabled?'Leave voice':'Join voice';this.mic.disabled=this.talk.disabled=!this.enabled;this.mic.textContent=this.openMic?'Mic on':'Mic off';this.mic.setAttribute('aria-pressed',String(this.openMic));this.talk.setAttribute('aria-pressed',String(this.pushing));}
 private async capture(hold:boolean){
  if(!this.enabled||this.busy)return;if(!hold&&this.openMic){this.openMic=false;this.applyMic();return;}
  const epoch=this.epoch;this.busy=true;try{
   if(!navigator.mediaDevices?.getUserMedia)throw Error('Microphone needs HTTPS and a supported browser.');
   if(!this.stream){const stream=await this.captureAudio();stream.getAudioTracks().forEach(t=>t.enabled=false);if(epoch!==this.epoch||!this.enabled){stream.getTracks().forEach(t=>t.stop());return;}this.stream=stream;for(const peer of this.peers.values())await peer.pc.getTransceivers()[0]?.sender.replaceTrack(stream.getAudioTracks()[0]);}
   if(!hold)this.openMic=true;this.applyMic();this.status.textContent=hold?'Release Hold to talk to mute.':'Microphone enabled.';
  }catch(error){this.pushing=false;this.openMic=false;this.status.textContent=(error as Error).message;this.refresh();}finally{this.busy=false;}
 }
 private applyMic(){for(const t of this.stream?.getAudioTracks()??[])t.enabled=this.enabled&&(this.openMic||this.pushing)&&!document.hidden;this.refresh();}
 private closePeers(){for(const p of this.peers.values()){p.pc.close();p.audio.pause();p.audio.srcObject=null;p.audio.remove();}this.peers.clear();}
 private stop(){this.epoch++;this.enabled=false;this.openMic=this.pushing=false;this.stream?.getTracks().forEach(t=>t.stop());this.stream=undefined;this.closePeers();this.transport?.state(false,this.channel.value as VoiceChannel);this.list.replaceChildren();this.status.textContent='Voice off. Microphone stopped.';this.refresh();}
 private sync(){
  const peers=this.enabled?this.members.filter(m=>m.id!==this.me&&m.channel===this.channel.value):[];const ids=new Set(peers.map(m=>m.id));for(const [id,p]of this.peers)if(!ids.has(id)){p.pc.close();p.audio.pause();p.audio.srcObject=null;p.audio.remove();this.peers.delete(id);}
  for(const m of peers)if(!this.peers.has(m.id))this.createPeer(m.id);
  this.list.replaceChildren(...peers.map(m=>{const row=document.createElement('label');row.append(document.createTextNode(m.name));const button=document.createElement('button');button.textContent=this.muted.has(m.id)?'Unmute':'Mute';button.onclick=()=>{if(this.muted.has(m.id))this.muted.delete(m.id);else this.muted.add(m.id);const p=this.peers.get(m.id);if(p)p.audio.muted=!this.listening||this.muted.has(m.id);this.sync();};row.append(button);return row;}));
 }
 private createPeer(id:string){
  if(typeof RTCPeerConnection==='undefined'){this.status.textContent='Voice is not supported by this browser.';return;}
  const pc=new RTCPeerConnection({iceServers:this.iceServers}),audio=document.createElement('audio');audio.autoplay=false;audio.volume=this.volume;audio.muted=!this.listening||this.muted.has(id);this.root.append(audio);const peer:Peer={pc,audio,making:false,ignore:false,setting:false,queue:Promise.resolve(),ice:[]};this.peers.set(id,peer);
  const track=this.stream?.getAudioTracks()[0];pc.addTransceiver(track??'audio',{direction:'sendrecv',...(track&&this.stream?{streams:[this.stream]}:{})});
  pc.onnegotiationneeded=async()=>{if(this.me>id&&!pc.currentRemoteDescription)return;try{peer.making=true;await pc.setLocalDescription();if(this.peers.get(id)===peer)this.transport?.signal({to:id,description:{type:pc.localDescription!.type,sdp:pc.localDescription!.sdp}});}catch{if(pc.signalingState!=='closed')this.status.textContent='Voice connection failed. Leave voice and retry.';}finally{peer.making=false;}};
  pc.onicecandidate=e=>{if(e.candidate){this.diagnosticsCounts.sent++;this.transport?.signal({to:id,candidate:e.candidate.toJSON()});}};
  pc.ontrack=e=>{audio.srcObject=e.streams[0]??new MediaStream([e.track]);void audio.play().catch(()=>this.status.textContent='Tap Sound on to enable voice playback.');};
  pc.onconnectionstatechange=()=>{if(pc.connectionState==='connected')this.status.textContent='Voice connected · '+this.channel.selectedOptions[0].text;else if(pc.connectionState==='failed')this.status.textContent='Voice could not cross this network. A TURN relay may be needed.';};
 }
 receive(from:string,value:unknown){const signal=voiceSignal(value);const peer=this.peers.get(from);if(!this.enabled||!signal||signal.to!==this.me||!peer){this.diagnosticsCounts.rejected++;return;}if(signal.candidate)this.diagnosticsCounts.received++;
  peer.queue=peer.queue.then(async()=>{const pc=peer.pc;if(pc.signalingState==='closed')return;
   if(signal.description){const d=signal.description,collision=d.type==='offer'&&(peer.making||pc.signalingState!=='stable'&&!peer.setting);peer.ignore=this.me<from&&collision;if(peer.ignore)return;peer.setting=d.type==='answer';try{await pc.setRemoteDescription(d);}finally{peer.setting=false;}for(const candidate of peer.ice.splice(0))await pc.addIceCandidate(candidate);if(d.type==='offer'){await pc.setLocalDescription();this.transport?.signal({to:from,description:{type:pc.localDescription!.type,sdp:pc.localDescription!.sdp}});}}
   else if(signal.candidate){if(!pc.remoteDescription){if(peer.ice.length<32)peer.ice.push(signal.candidate);return;}try{await pc.addIceCandidate(signal.candidate);}catch(e){if(!peer.ignore)throw e;}}
  }).catch(error=>{this.diagnosticsCounts.errors.push(String(error).slice(0,160));this.diagnosticsCounts.errors=this.diagnosticsCounts.errors.slice(-8);if(peer.pc.signalingState!=='closed')this.status.textContent='Voice interrupted. Leave voice and retry.';});
 }
 async diagnostics(){return {enabled:this.enabled,mic:this.openMic,signaling:this.diagnosticsCounts,tracks:this.stream?.getAudioTracks().map(t=>({enabled:t.enabled,state:t.readyState}))??[],peers:await Promise.all([...this.peers].map(async([id,p])=>{const stats=await p.pc.getStats();const values=[...stats.values()],inbound=values.filter(s=>s.type==='inbound-rtp'&&s.kind==='audio');return {id,state:p.pc.connectionState,signaling:p.pc.signalingState,gathering:p.pc.iceGatheringState,candidates:values.filter(s=>s.type==='local-candidate').length,remoteCandidates:values.filter(s=>s.type==='remote-candidate').length,pairs:values.filter(s=>s.type==='candidate-pair').map(s=>s.state),received:inbound.reduce((n,s)=>n+(s.bytesReceived??0),0)};}))};}
}
