// Generated by the pinned Unity Emscripten build; public handshake identity.
export const ENGINE_ID = Object.freeze({ engine: '6b4d4e1f10dee9b1c8932db95f91b92e3eceb7db', module: 'cd0c0d595bb139d275dab145446e813706858634f122a4fea8a63d34075b796e', bridgeAbi: 4, engineRules: 'static-royale-cpp-2' });
