// Generated by the pinned Unity Emscripten build; public handshake identity.
export const ENGINE_ID = Object.freeze({ engine: '6b4d4e1f10dee9b1c8932db95f91b92e3eceb7db', module: '2ac9a1d3a5fb5745e8b37e4411f2e17caadf82944ea0ec7b18ab00b075377136', bridgeAbi: 4, engineRules: 'static-royale-cpp-2' });
