// Generated by the pinned Unity Emscripten build; public handshake identity.
export const ENGINE_ID = Object.freeze({ engine: '6b4d4e1f10dee9b1c8932db95f91b92e3eceb7db', module: '6229a7803cb5c39bba08f9db90f47ea9b44efbaeee2e47d4f41578a1820b975e', bridgeAbi: 4, engineRules: 'static-royale-cpp-2' });
